### ISSUE TITLE
Run Program

### ISSUE THREAD

**Issue by Technologyman00** [SpoinkyNL/Artemis#1]
How is the program Run? It looks awesome I just dont know how to use it.

**Comment by JewsOfHazard** [comment]
Hello! Thanks for taking an interest in the program. At the moment we have no officially bundled binaries as support for some things is not yet implemented. If you would like, you may [download the source code](https://github.com/SpoinkyNL/Artemis/archive/master.zip) and compile it with [visual studio 2015](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx)

**Comment by Technologyman00** [comment]
Well Keep Up the Good Work It looks amazing I would love to test it out!

**Comment by SpoinkyNL** [comment]
Hey, thanks for your interest. Once I've got the all the base features in and added some proper error messages ans exception displays,  I'll start uploading compiled releases regularly :)

**Comment by travisdietrich** [comment]
Looking forward to the release fellas.  :+1:

**Comment by Technologyman00** [comment]
Cant Wait for this Program!

**Comment by JewsOfHazard** [comment]
[I uploaded a short video demonstrating the volume controls and music effect, if you guys wanted to be more excited that is.](https://www.youtube.com/watch?v=X_XYD_sV4pY)
