### ISSUE TITLE
Not sure if the K70 Rapidfire is detected properly

### ISSUE THREAD

**Issue by joeknock90** [SpoinkyNL/Artemis#103]
When setting up Artemis for my K70 rapidfire it doesn't throw an error in the settings, but the Preview screen still says "To get started, please set up a keyboard in the settings menu and enable this effect / game." Effect is also enabled. 

I could just be doing this completely wrong.

**Comment by SpoinkyNL** [comment]
Hello, it could be possible that the Rapidfire identifies itself differently from the old K70 RGB. This would mean Artemis doesn't know what to do with it.

As soon as I know more I'll give you an update.

**Comment by joeknock90** [comment]
That's what I figured too. I've been out of this for a long time but I'll try to see if i can figure anything out in the source as well.

Thanks!

**Comment by DarthAffe** [comment]
There is something in the [Corsair-Forum](http://forum.corsair.com/v3/showpost.php?p=857207&postcount=57) (regarding a different project) and it seems like the rapidfires aren't supported by the SDK.  I'm not 100% sure about it, but it could be something to test.

**Comment by joeknock90** [comment]
Interesting. I wonder if the SDK is outdated? Hopefully that get's fixed. I would hate to have purchased a board that isn't going to be supported by the SDK. 

I have to be honestly though I hate typing on this board. Great for games, horrible for typists. I miss my cherry mx blues.

**Comment by DarthAffe** [comment]
This is somehow a request for my own sake but could you test the SDK by running the color-pulse-example provided with it? (You can use [this binaries](http://wyrez.org/uploads/color_pulse_example.zip) or the source provided with the SDK.)
Please double check that the SDK is enabled in CUE!

**Comment by joeknock90** [comment]
I will do that. Give me just a little bit.

**Comment by DarthAffe** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by joeknock90** [comment]
Yeah I've reinstalled that. Weird. Could be an insider preview thing. =\ I might not be able to test. Maybe I could spin together a VM and pass the USB through to it of a non insider preview thing. Just spit balling now. Gonna try to get this working.

**Comment by SpoinkyNL** [comment]
Don't worry, even if the SDK doesn't support the new K70 right now, I'm sure it will.

Could you also please try to run this: https://www.dropbox.com/s/i1ox3laitzjrl6c/CorsairSdkTest.zip?dl=0
It should output something similar to his:
![output](http://i.imgur.com/d7DMiZN.png)

I'd like to know what it reports back with the K70.

**Comment by joeknock90** [comment]
Surely, I'm re installing VS so I have to wait one moment.

**Comment by SpoinkyNL** [comment]
Thank you! This version should work for you, unless there's an underlying issue with the SDK: https://www.dropbox.com/s/i2fvptgayvnksec/artemis-1.1.2-setup.zip?dl=0

**Comment by joeknock90** [comment]
Holy crap that's amazing. I'll test this out and let you know. Please feel free to get in touch with me if you need any testing.

**Comment by joeknock90** [comment]
![capture](https://cloud.githubusercontent.com/assets/17264883/15986334/ae930852-2fd3-11e6-8548-ba2b862cf58f.PNG)

Well done sir and thanks again.
