### ISSUE TITLE
Artemis Crash g910 

### ISSUE THREAD

**Issue by mrskizzex** [SpoinkyNL/Artemis#104]
Hello, i wasn't using this little program for a long while and decided to come back but unfortunately it doesn't work properly.

Whatever I do, change keyboard in settings, apply effect, change one value in effect, program hangs, it uhangs after like 20 seconds and does the queued action, if i click on the window during the hang, program crashes and after trying to open it again, it doesnt launch. Process stays at 30mb ram and 0% load, keyboard leds are off and keystrokes are laggy. Killing the process fixes the lag but the program still wont start. Only way to launch the program is to either restart pc / relog or reinstall.
Halp !

I'll be happy to provide whatever info you need.
Some info out of the way:
-win 10
-newest logitech gaming software 
-newest artemis
-i reinstalled vcredits from link i found in another closed issue about artemis crashing when effect changed and also i ran the command that was there, didn't work

**Comment by SpoinkyNL** [comment]
Hello, this is very odd behaviour. Could you please upload the log file(s)
located at Documents > Artemis > logs to Pastebin?
Op 12 jun. 2016 01:57 schreef "mrskizzex" <notifications@github.com>:

**Comment by mrskizzex** [comment]
Okay, I reinstalled the program, and it seems that changing the keyboard is hanging the program. This time around I waited a bit after starting the program while looking at log file which resulted in program starting, and working correctly (i could have sworn i waited longer yesterday and it wouldnt launch). Anyhow, after looking at logs it seems that choosing the keyboard is what causes the hang, there was one unexpected crash when exiting through tray > exit option but i don't really care about that.

It seems i overreacted a bit, I'm sorry for that.  Still, if you could fix it, or at least tell me that its not fixable and its on logitech end i will understand and shut up :)


Each number after date means program start.
[2016-06-12-1.txt](https://github.com/SpoinkyNL/Artemis/files/310722/2016-06-12-1.txt)
[2016-06-12-2.txt](https://github.com/SpoinkyNL/Artemis/files/310724/2016-06-12-2.txt)
[2016-06-12-3.txt](https://github.com/SpoinkyNL/Artemis/files/310723/2016-06-12-3.txt)
[2016-06-12-4.txt](https://github.com/SpoinkyNL/Artemis/files/310721/2016-06-12-4.txt)

**Comment by SpoinkyNL** [comment]
Hey, thanks for your logs. I can see there is an 18 second delay right here twice in a row:
```
2016-06-12 12:15:08.0460|DEBUG|Artemis.Managers.DeviceManager|Enabling keyboard: Logitech G910 RGB 
2016-06-12 12:15:26.2989|DEBUG|Artemis.DeviceProviders.Corsair.CorsairMice|Attempted to enable Corsair mice. CanUse: False 
2016-06-12 12:15:44.3066|DEBUG|Artemis.DeviceProviders.Corsair.CorsairHeadsets|Attempted to enable Corsair headset. CanUse: False 
```

That shouldn't be happening, it will be fixed in hopefully the next update, thanks again!

**Comment by mrskizzex** [comment]
No problem. Thanks for fast response !
