### ISSUE TITLE
Overwatch and Rocket League Profile doesn't work

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#108]
Hey there, neiterh the Overwatch Profile nor the Rocket League profil works for me.

In Rocket League the Keyboard stays black and in Overwatch it stays in the menu animation with the orange flow.

I Have Win10 and Logitech G910 Keyboard

**Comment by SpoinkyNL** [comment]
Hi, Overwatch is a known issue. Duplicate the profile and move the main menu layer all the way down.
As for Rocket League, I can't check that right now but I'll get back to you

**Comment by SomaKhaos** [comment]
Thanks for your answer, but moving down the main menu layer doesn't fix that, cause when i move it down it stucks in the next layer^^

**Comment by Thoth2020** [comment]
For overwatch, the layers should be controls, characters, and main menu, in that order.

**Comment by SomaKhaos** [comment]
Yeah, i know. But it doesn't really change anything. The only thing it changes is that i'm not stuck in the main menu layer anymore. Now i stuck in the controls layer animation.

even if i choose your order it only displays this one control layer, but nothing's changing. Not the hero color or anything else. The ultimate ready button isn't even flashing when it's ready. It's just like it stucks for ever in one animation without changing anything

**Comment by SpoinkyNL** [comment]
Just a quick question, when trying this out are you leaving the editor open? I'm asking because both Rocket League and Overwatch (after making the adjustments to the profile) work fine for me.

While the editor is open the actual game is suppressed. Try navigating away to a different tab or closing the Artemis window altogether.

**Comment by SomaKhaos** [comment]
I don't leave the editor open, i close it then i'm on desktop and my windows profile works fine and then i start Overwatch or Rocket League and it happens what i described earlier

**Comment by SpoinkyNL** [comment]
Alright sorry to hear you're having such troubles :(
Could you head over to Documents > Artemis > logs and upload some of the logs in there so I can see what's going on?

We're currently working on the next update which is mainly focussed on performance improvements and a few fixes, I'd like to see what's happening here before that release is done.

**Comment by SomaKhaos** [comment]
http://txt.do/5bbon
http://txt.do/5bbow
http://txt.do/5bboy
http://txt.do/5bbo3

It's ok having troubles with an Application which is still in development ;)
I'm happy that you try to answer and help everyone :)

Above are the Logs from 09. June, 10, June, 12. June and 13. June in this order.

**Comment by SpoinkyNL** [comment]
Thanks for the logs, the huge delay in starting up is fixed in the next update, #104 had the same.
In Overwatch, does the keyboard's background color change at all when you select a different hero?

In your third log, the profile editor was taking control of the keyboard while Overwatch was running, this means you must've had it open. I might change it so it doesn't take control if a game is running since this is not very intuitive.

**Comment by SomaKhaos** [comment]
No problem, ah thats sounds great that the delay will be gone.
Nope in Overwatch nothing really happens. it's just the controls layer that is on, no hero color changing and no ultimate ready flashing or something else, just the standard controls layer.

Yes it could be that i opened the editor while in-game, cause i tried to disable and re-enable the effect to look if this works, but it didn't work either.

**Comment by SpoinkyNL** [comment]
Alrighty, if you go to `C:\Program Files (x86)\Overwatch`, or wherever you have Overwatch installed, is there a file there called `RzChromaSDK64.dll`?

That's what Artemis uses to see what's going on in Overwatch, maybe it's failing to install it.

**Comment by SomaKhaos** [comment]
The file is in the folder

**Comment by SomaKhaos** [comment]
Just installed the newest update to look if it's working now.

In Rocket League nothing changed, same problem as earlier.

In Overwatch something changed. Now only my WASD keys are illuminated when i start the game.

**Comment by SpoinkyNL** [comment]
Hello, if it's OK with you I'd like to make a special debug version that will log everything that's going on in Overwatch and Rocket League. 

I'm at a bit of a loss as to why both these games don't work on your computer, so perhaps this will clear things up. After all Artemis should work on anyone's PC :)

**Comment by SomaKhaos** [comment]
That would be great.

**Comment by SpoinkyNL** [comment]
Hello again, I've added some extra logging functionality to Artemis and you can download the release here: https://github.com/SpoinkyNL/Artemis/releases/tag/1.1.3.2

If you could head over to settings and set the logging level to Trace (don't forget to save the settings) that should give me lots of information on what's going on when you're playing Rocket League / Overwatch.

If you could provide me with a log for both, that would be great. Don't forget to disable Trace and set it back to Info/Debug when you're done, or you'll end up with giant log files :P

**Comment by SomaKhaos** [comment]
for how long should i enable the trace function?

**Comment by SpoinkyNL** [comment]
Half a minute per game will do, preferably in a match

**Comment by SomaKhaos** [comment]
http://pastebin.com/A1mkNATu Overwatch LOG
http://pastebin.com/x2u7NNek Rocket League LOG

hope they're not to long :)

**Comment by SpoinkyNL** [comment]
Thanks, looks like for both games that Artemis is unable to read what's going on, which is odd.

Can you try running Artemis as admin, and what OS are you using?

**Comment by SomaKhaos** [comment]
I'm using Win10 and running artemis always as admin

**Comment by SomaKhaos** [comment]
Could it be that it has something to do with the Gamestate server port?

**Comment by SpoinkyNL** [comment]
Hey, Gamestate server is used for CS:GO and Dota2, so that shouldn't matter. I don't really understand why it's failing without any errors :\

Just a few things, what virus scanner do you use? Could you try disabling it for a moment and seeing if that helps?
Do you have VCRedist 2015 installed? https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145&6B49FDFB-8E5B-4B07-BC31-15695C5A2143=1

I've expanded logging a bit further to hopefully see why Artemis can't read the game data in this release: https://www.dropbox.com/s/5evglyzn6zsglon/artemis-1.1.3.3-setup.zip?dl=0. Could you do the same again?

**Comment by SomaKhaos** [comment]
https://www.dropbox.com/s/tfaymbd9sef37sp/Overwatch.txt?dl=0
https://www.dropbox.com/s/z4x3pq8ifienft3/Rocket%20League.txt?dl=0

Here are the logs, While tracing the games Antivir and Windows Defender were both disabled.
VCRedist 2015 is installed.

Hope you can find the error :)

**Comment by SpoinkyNL** [comment]
These logs got me a lot closer, could you try Rocket League now? No need for a new download just a restart of Artemis (and update pointers must be enabled in settings)

**Comment by SomaKhaos** [comment]
just tested it, and unfortunately nothing changed. Rocket League effect is still not working :\

**Comment by SpoinkyNL** [comment]
Could you try running Overwatch as an administrator?

**Comment by SomaKhaos** [comment]
nope, didn't work

**Comment by SpoinkyNL** [comment]
Well this is getting a bit annoying.. Could you try removing the RzChromaSDK64.dll from the Overwatch directory, installing this version: https://www.dropbox.com/s/42ie2wlzxevjsx3/artemis-1.1.3.4-setup.zip?dl=0 and running Overwatch as admin again.

I've changed the way reading Overwatch works, maybe this'll work for you. If this doesn't do it I'm not sure what will :\

**Comment by SomaKhaos** [comment]
i tried to install your new version and this what happened:

http://pastebin.com/trRg0Hjz

**Comment by SomaKhaos** [comment]
no i can't even install an older version because it always says me that artemis is installed in another location and can not be installed. But i can't deinstall the newest version, because it's not really installed, i still deleted all datas and folders from artemis and it keeps the same...

**Comment by SpoinkyNL** [comment]
Hi, looks like there's the root of the issue. Something on your system is blocking access to Memory Mapped Files and that's why Overwatch doesn't work.

A memory mapped file is a temporary file that exists in your RAM so that Overwatch can tell Artemis what's going on. Whatever is blocking this, is most likely also blocking Rocket League.

Are you trying to install an older version because that works for you? If I'm right an older version such as this one also shouldn't work: https://github.com/SpoinkyNL/Artemis/releases/tag/1.0.3.1

If you're having trouble installing type the following in a command line window as admin:
```rundll32 dfshim CleanOnlineAppCache```

**Comment by SomaKhaos** [comment]
with older version i meant the previous version you send me^^ sry for being unclear :-D

**Comment by SomaKhaos** [comment]
Well, i think now it's finally broken. I have now the problem that everytime i try to enable my g910 keyboard that artemis says i have to install visual c 2012 redistributable. And i have it already installed.... :(

**Comment by SpoinkyNL** [comment]
Nothing changed in Artemis though.. I don't know how I can help you. Only
thing I can think of is a clean Windows installation if that's wroth it to
you, I'm sorry :/
Op 18 jun. 2016 5:41 p.m. schreef "SomaKhaos" <notifications@github.com>:

**Comment by SomaKhaos** [comment]
forget about this^^ had trouble with the visual c installation, reinstalled it and now artemis works again

**Comment by maccydboy** [comment]
I still tried everything on this thread, but i can't get it to read Overwatch's data.

The profile is changing keyboard's color but not depending on what's happening. 

Windows 10 with G910

**Comment by SpoinkyNL** [comment]
@SomaKhaos and @maccydboy, could you both try disabling user account control? (UAC) to see if that helps? http://www.howtogeek.com/howto/windows-vista/disable-user-account-control-uac-the-easy-way-on-windows-vista/

**Comment by maccydboy** [comment]
I will try right now

**Comment by maccydboy** [comment]
i got into something, everytime i add a layer and set, for exemple : display if ... ability 2 is equal to true.

everytime i go again on THAT layer, the true or false is not showing up. maybe it is not saving it? 
![2016-07-09 11_59_21-glowwindow](https://cloud.githubusercontent.com/assets/1550380/16708787/d16a084e-45cc-11e6-9da0-a5940d1bf02c.png)

**Comment by SpoinkyNL** [comment]
Hey, that's just a visual bug. It's actually saving it but not showing it in the editor. I'll have it fixed in the next release

**Comment by maccydboy** [comment]
Alright, thanks.

i still played with the software a lot and tried every combination possible in my profile between layers and files.. 

When the game starts, the keyboard does flash and then it keeps showing up firsts layers.

**Comment by SpoinkyNL** [comment]
I'm closing this in favor of #128, please try the latest version mentioned there
