### ISSUE TITLE
Settings rewrite

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#111]
Currently Artemis uses the default .NET settings library. It sucks and loses settings at weird moments like during updates.

I'd like to either move to a better framework or write something ourselves, since it doesn't need to be rocket science, most stuff is saved in profiles anyway.

**Comment by DarthAffe** [comment]
I'm not 100% sure what you need for your settings but lately I worked on a project using https://github.com/MarioZ/MadMilkman.Ini and this seems to be a quite easy solution if ini-files are functional.
