### ISSUE TITLE
Audio Visualizer 

### ISSUE THREAD

**Issue by stbatuhan** [SpoinkyNL/Artemis#113]
Can you make that as a part of windows profile section for us to arrange keys what we want? As an example i want to use that for the main keys from tab to enter and under that. Esc to f12 i want to use spotify songpercent... and for the numerical part on the right cpu. I want to re-arrange them with Audio Vis. and also it can be enable when playing a song on spotify or other media players. Other times i'd like to use type waves. Auto switch we need on that which you integrated i guess from settings.

**Comment by SpoinkyNL** [comment]
Hello,

Just letting you know I do have plans to turn things like audio visualization into layers instead of separate effects, but there are some other things I want to get done first (such as event-based layers)

**Comment by SpoinkyNL** [comment]
The latest release has support for audio visualization layers now that allow you to do this :)
https://github.com/SpoinkyNL/Artemis/releases/tag/1.3.0.0
