### ISSUE TITLE
G810 Support

### ISSUE THREAD

**Issue by superaznboi** [SpoinkyNL/Artemis#114]
I would like to know if g810 will be usable with Artemis... On the main page, it does say g810 is not tested yet. I just want to know when, please. I also accidentally click g910 option in the settings and now Artemis crashes on launch.

**Comment by SpoinkyNL** [comment]
Hello. I don't have that keyboard. You're free to try it out, just select G910 in Artemis and see how it goes. 

In the layer editor the image won't match but please let me know if the profiles look OK (per example, om overwatch wasd should be lid)

**Comment by superaznboi** [comment]
Okay, I got the program to work with the g810. For some reason, every time I tried to select g910, it would say access denied to profiles and then it would crash. Once I tried to open the application again it would crash immediately after the pop-up message "Loading the previously selected keyboard". To fix this, I had to load the setup.exe as administrator... Don't understand why this works but it does.

The all the profiles seem to work perfectly. Except the overwatch profile where only the wasd keys were lit but nothing else. The audio visualization, by the way, is AMAZING!

The layer editor works fine, all you have to do is move the layers so that it would line up with only the  standard keys and not the g-keys.

Overall, I'm satisfied that I got it to work finally after 2 long hours of frustration... Also I am willing to help you test run this keyboard if you so desire.
