### ISSUE TITLE
Won't install anymore

### ISSUE THREAD

**Issue by superaznboi** [SpoinkyNL/Artemis#116]
After shutting down my computer for one day. I come back to see that Artemis wouldn't run. So I tried to reinstall it but it wasn't being removed. I had to force it by deleting the registry files and every trace of the application from my computer. Now it won't install, it would launch the clickonce but never open the program... I tried to reinstall microsoft frameworks and visual C++ but nothing still...

Edit: Okay so I downgraded to 1.1.2 and now i can install it...

**Comment by SpoinkyNL** [comment]
Hey there, I'm not very happy with our current installer and I'm planning to swap to a different one.
I see you somewhat fixed it by downgrading, but could you try this:

> If you're having issues installing this version,please get rid of all traces of the program using the uninstallers. After that type the following in a command line window:
> ```rundll32 dfshim CleanOnlineAppCache```

**Comment by superaznboi** [comment]
Do I use the windows uninstaller or are there specifically made programs I can use?

**Comment by SpoinkyNL** [comment]
Just the ones that are present in your software list in Windows

**Comment by superaznboi** [comment]
Okay, thanks for replying!

**Comment by SpoinkyNL** [comment]
Did you manage to solve this? Otherwise you could perhaps try this with the [latest version](https://github.com/SpoinkyNL/Artemis/releases/tag/1.2.0)

**Comment by superaznboi** [comment]
I was able to install 1.1.3 somehow. I will try the latest version and get back to you.

**Comment by superaznboi** [comment]
So 1.2 does install! All problems are solved except the overwatch profile... It still doesn't work...

**Comment by SpoinkyNL** [comment]
Ok thanks for reporting back. You're not the only one who's having issues
with Overwatch. I suspect it's a permissions-issue. I'll get back to you on
this, promise!

Op 20 jul. 2016 7:39 a.m. schreef "Andrew Ho" <notifications@github.com>:

**Comment by SpoinkyNL** [comment]
For Overwatch please see #128
