### ISSUE TITLE
High processor usage on Windows 10 randomly

### ISSUE THREAD

**Issue by Praxis459** [SpoinkyNL/Artemis#119]
Hi first off wanted to say love the program have it running all the time. Wanted to report every once in a while I will see high processor usage 25% or higher being used by artemis. I haven't been able to mail it down completely yet as to what might be causing it, but it is something I am seeing on a pretty normal basis. Will update issue when more information is found, please let me know if you have any questions or if I can do anything to help.

**Comment by SpoinkyNL** [comment]
Hey Praxis,

Thanks for the report. I've been hard at work rewriting a lot of the layers code that may just solve this already.

When these CPU usage jumps occur, are you using a profile or one of the other effects?

**Comment by SpoinkyNL** [comment]
Hey, could you try this with the [latest version](https://github.com/SpoinkyNL/Artemis/releases/tag/1.2.0)?
