### ISSUE TITLE
LUA layer type

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#121]
Would be cool to have a LUA layer type in which people can draw on the layer like a canvas.
Could also make layer conditions run a bit of LUA to start with.

**Edit:** Might even be better to extend this to attaching LUA scrips to an entire profile. That way you're not bound to one layer and you could fairly easily interact with the other layers

**Comment by DarthAffe** [comment]
Check https://github.com/xanathar/moonsharp for this - seems like a good and easy solution to integrate lua.

**Comment by SpoinkyNL** [comment]
Yes I've used that before and it worked well for me. I also tried NLua but their docs aren't quite as good, so I think I'll go with Moonsharp again
