### ISSUE TITLE
No profile updates

### ISSUE THREAD

**Issue by HappyDude1213** [SpoinkyNL/Artemis#125]
I just downloaded this program today. I have a corsair STRAFE RGB and a Corsair Scimitar RGB. I used CS:GO and Overwatch. neither of them worked. I have windows 10

EDIT: Nothing Works

**Comment by SpoinkyNL** [comment]
Hello,

Does Artemis color the keyboard at all, or does it stay the way you set it
up in CUE?

Also could you post the logfile found in Documents > Artemis > logs?
Op 11 jul. 2016 02:51 schreef "HappyDude1213" <notifications@github.com>:

**Comment by HappyDude1213** [comment]
I can get it to light up the keyboard but sometimes I need to reselect it for it to work. I used it on the 10th.

[2016-07-10.txt](https://github.com/SpoinkyNL/Artemis/files/357090/2016-07-10.txt)
[2016-07-11.txt](https://github.com/SpoinkyNL/Artemis/files/357091/2016-07-11.txt)

**Comment by HappyDude1213** [comment]
Also, should all the default profiles be configured correctly if I haven't changed them?

**Comment by SpoinkyNL** [comment]
Hey thanks for the logs, I see a few errors that shouldn't be happening. Does the Windows profile show CPU usage properly on the num-keys?

In these logs I don't see Artemis ever detecting CS:GO btw, could you give that another go as well and post the logs?

Oh and please put the debug level to trace for now (under settings), should've mentioned that earlier, sorry

**Comment by HappyDude1213** [comment]
so you want me to set the level to trace then open csgo and give you the logs. Correct?

**Comment by HappyDude1213** [comment]
and for the windows profile I can't get it to use Artemis over CUE

**Comment by SpoinkyNL** [comment]
Ah ok, as long as the Windows profile doesn't work the rest won't work either so best to start there.
In CUE please make sure that:
1. You have SDK access enabled
2. You have synchronized lighting disabled

And in regards to logging, that's indeed what I ment :)

**Comment by HappyDude1213** [comment]
It is showing cpu usage on the numpad

**Comment by HappyDude1213** [comment]
and is there any specific folder I need to set the csgo directory to?

**Comment by HappyDude1213** [comment]
okay csgo works now

**Comment by HappyDude1213** [comment]
let me try overwatch and rocket league

**Comment by SpoinkyNL** [comment]
Ok good. Overwatch should work, Rocket League needs an update and currently wont work

**Comment by HappyDude1213** [comment]
okay, do I still need to move the main menu folder to the bottom for overwatch?

**Comment by SpoinkyNL** [comment]
With the default profile for the Strafe it should be fine by default. To make sure it works you can go to the practice range and check whether the keyboard changes color when you select a different hero

**Comment by HappyDude1213** [comment]
should it change in the hero selection screen?

**Comment by SpoinkyNL** [comment]
Yes, but I gather it does not?

If not you could try running Overwatch as administrator

**Comment by HappyDude1213** [comment]
it still isn't working.

[2016-07-11.txt](https://github.com/SpoinkyNL/Artemis/files/357160/2016-07-11.txt)

**Comment by SpoinkyNL** [comment]
Well it's a bit odd. I can see Artemis detecting Overwatch, but it also disables it again after a while

```
2016-07-11 09:18:34.2510|INFO|Artemis.Managers.MainManager|Detected and enabling game: Overwatch 
2016-07-11 09:18:34.2510|DEBUG|Artemis.Managers.EffectManager|Changed active effect to: Overwatch 
2016-07-11 09:19:06.4189|INFO|Artemis.Managers.MainManager|Disabling game: Overwatch 
2016-07-11 09:19:06.4189|DEBUG|Artemis.Managers.EffectManager|Disabling game: Overwatch
```
In between that time there is no log output :\

Two questions:
1. Does the keyboard turn black as soon as you start Overwatch?
2. Can you check in your Overwatch installation directory (default `C:\Program Files (x86)\Overwatch`) for a file called `RzChromaSDK64.dll`, is it there?

**Comment by HappyDude1213** [comment]
it does turn black when I open overwatch

**Comment by HappyDude1213** [comment]
actually nevermind it doesn't

**Comment by HappyDude1213** [comment]
it just used the windows profile

**Comment by HappyDude1213** [comment]
I do have the RzChromaSDK64.dll file

**Comment by SpoinkyNL** [comment]
Ok then for some reason it's not properly detecting that Overwatch is running. Just to make sure, in the Overwatch tab you have checked the Enabled checkbox?

**Comment by HappyDude1213** [comment]
yes it is checked

**Comment by SpoinkyNL** [comment]
Ok weird, I can't do much more right now until I get home but can you post a screenshot of the Overwatch tab?

You could also try a clean Artemis installation (Remove the program from the Software list and delete the Artemis folder in Documents)

**Comment by HappyDude1213** [comment]
so reinstall it?

**Comment by SpoinkyNL** [comment]
Yes

**Comment by HappyDude1213** [comment]
Here's the screenshot https://gyazo.com/e1ff1597b049cb8bee7f042355613ff4

**Comment by SpoinkyNL** [comment]
Hey, could you try this with the [latest version](https://github.com/SpoinkyNL/Artemis/releases/tag/1.2.0)?

**Comment by HappyDude1213** [comment]
Okay

**Comment by SpoinkyNL** [comment]
I'll close this one in favor of #128

**Comment by SpoinkyNL** [comment]
Please see #128
