### ISSUE TITLE
Game profiles dont stay active after Reboot

### ISSUE THREAD

**Issue by Bluethefurry** [SpoinkyNL/Artemis#126]
See title, Profile goes back to Default even tho ive set my custom one before rebooting my PC

**Comment by SpoinkyNL** [comment]
Hey, could you try this with the [latest version](https://github.com/SpoinkyNL/Artemis/releases/tag/1.2.0)?

I didn't specifically fix it, but many things changed in and around the profile system, so it might be solved. If not I'll get on it next release :)

**Comment by Bluethefurry** [comment]
@SpoinkyNL Not fixed, Windows profile saves, but my games profiles always reset after restarting artemis

**Comment by SpoinkyNL** [comment]
Ok I'll get on this for the next release, thanks for reporting back

**Comment by SpoinkyNL** [comment]
Hey, this should be fixed now, I've rewritten the settings system :) Let me know how it goes
