### ISSUE TITLE
Rocket league boost is not read correctly at some rounds

### ISSUE THREAD

**Issue by Sprayan** [SpoinkyNL/Artemis#129]
Some rounds in rocket league it doesn't display my boost like it's reading something else.
Using v1.2.0

**Comment by SpoinkyNL** [comment]
Hey, it works well in private matches / exhibition matches but in online
matches it's all over the place. I'll fix it tomorrow (won't even require a
Artemis update, just a restart) I'll let you know when it's ready

Op 20 jul. 2016 10:14 p.m. schreef "Sprayan" <notifications@github.com>:

**Comment by SpoinkyNL** [comment]
I've updated the memory address, could you restart Artemis and see how it goes now?
The few matches I played online seemed fine :)

**Comment by Sprayan** [comment]
I have tested it out now and it seems to be working every time now! Thanks for the fix!

**Comment by SpoinkyNL** [comment]
Great, ty for reporting back :)
