### ISSUE TITLE
Version 1.2.0.1 is the same as Version 1.2.0

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#130]
Hey there,

Just downloaded Version 1.2.0.1, installed and started it and it keeps saying me that there is a new version available.

Even in the settings Tab it says that Version 1.2.0 is installed

Did you packed the wrong installer?

**Comment by SpoinkyNL** [comment]
Hey, it's the right one, I forgot to update the version number. I've taken off the 1.2.0.1 release and simply updated the 1.2.0 release to avoid the update message popping up

If you want to make sure it's the fixed version, try duplicating a profile. If that works as expected, you've got the fixed version
