### ISSUE TITLE
[GAME REQUEST] Assetto Corsa and extend Rocket League Support

### ISSUE THREAD

**Issue by Bluethefurry** [SpoinkyNL/Artemis#131]
I've seen multiple racing games that use the LEDs for RPM / Speedo / Gear Display, and i would love to have something like that for Assetto Corsa, it shouldnt be too hard as things like Arduino already does the same ( https://www.youtube.com/watch?v=fk8P9UUxYGI )

Also something that might be good would be Score Display for Rocket league, for example 1 LED means 1 point, and that can be applied for each team so it looks roughly like this:
https://puu.sh/qaoYS/a0229085b1.jpg

Greetings

**Comment by SpoinkyNL** [comment]
Hello, I've been planning to do Project CARS. While at it I might take a look at Assetto Corsa but I don't own that game so it'll need some extra testing

Rocket League stuff is planned as well #65 :)

**Comment by Bluethefurry** [comment]
Great to hear, sadly i dont play project cars as its not worth my time (imo), you could try to make an In-Game app which connects to Artemis, to my knowledge that is possible

**Comment by SpoinkyNL** [comment]
Hi, I've gotten around to adding an Assetto Corsa module but it needs testing and a default profile for atleast one keyboard (I can make the others myself after I have one that looks nice).

If you're feeling creative and want to provide a default profile I'd greatly appreciate it :)

Download: https://github.com/SpoinkyNL/Artemis/releases/tag/1.8.2.0

**Comment by Bluethefurry** [comment]
Great Job!
i'm currently uploading a video of the Preview, i also uploaded the Profile, it only has vehicle functions as i cant seem to find a function to compare lap times or something similair.
Anyways, here is the profile:
[ac.json](https://github.com/SpoinkyNL/Artemis/files/836936/ac.json.txt)

I'll add the video later as it takes a while to upload!

**Comment by Bluethefurry** [comment]
Another thing about the beta version, it crashes, alot.

It just displays "Artemis has stopped working" makes my PC lag until i click close

**Comment by manskou** [comment]
These bugs are known and have been fixed, Spoinky uploaded a fixed version in #276

**Comment by SpoinkyNL** [comment]
Thanks for the profile! I'll take a look at the video when it's ready. I've been short on time but that other version should indeed work better

**Comment by SpoinkyNL** [comment]
Looks great @Bluethefurry I'll get it in the next release with credits of course!
