### ISSUE TITLE
Says keyboard is activated, but not being detected?

### ISSUE THREAD

**Issue by Ellwinx** [SpoinkyNL/Artemis#132]
Hey, I stumbled upon your application and it seems pretty amazing, however I can't seem to get it to work. I just bought a Corsair K70 LUX RGB and this is what I'm getting after installing Artemis:

![image](https://cloud.githubusercontent.com/assets/20711299/17228189/43e6d998-5512-11e6-8eb0-21023c459ef3.png)

Am I just being stupid and missing something? Is there something I forgot to activate/install?

**Comment by SpoinkyNL** [comment]
Hey, could you enable Trace logging and reselect Corsair, and then upload
the log found in Documents > Artemis > logs?

Thanks!

Op 28 jul. 2016 22:27 schreef "Ellwinx" <notifications@github.com>:

**Comment by Ellwinx** [comment]
[2016-07-28.txt](https://github.com/SpoinkyNL/Artemis/files/389368/2016-07-28.txt)

Thanks for the super fast reply!

**Comment by thefabgar** [comment]
Hey there how are you man? I'm having the same issue, same keyboard K70 LUX RGB.

Thanks in advance

**Comment by SpoinkyNL** [comment]
Great stuff, thanks for the log. :)

I've fixed it and I'll hopefully be able to release an update today

**Comment by Ellwinx** [comment]
Downloaded the update and it works flawlessly so far! Thanks for the lightning fast support.

**Comment by SpoinkyNL** [comment]
Alright great, thanks for reporting back!

I'm closing this issue, should you come across anything else please feel free to make a new one
