### ISSUE TITLE
Type Wave Request

### ISSUE THREAD

**Issue by palsgod** [SpoinkyNL/Artemis#134]
Hi! I started to use this program and love it, and as my logitech g810 doesn't come with type waves this feature was very exciting for me. I love everything about the type waves except for the fact that until you press a key nothing is lit up. I was wondering if it is possible to add a background color to the keyboard.  Many keyboards have this feature. For example, the background color could be white while nothing is pressed but when you press a key the wave spreads out. Thanks!

**Comment by SpoinkyNL** [comment]
Hello, I'm glad that you're enjoying Artemis :)

You should be able to head over to Windows profile and create a nice background there, after that put a layer on top and change it's type to 'Keyboard - Key press'. That acts the same as the keywave effect. The keywave effect will be removed in the next version in favor of this, after I've finished the configuration options.

**Comment by palsgod** [comment]
I'm guessing the FN keys wont count as the background because they are the G810's version of G keys? And also, the Key press doesn't have the random color affect as the wave spreads, so I'm guessing that will be in the configuration options. Keep up the good work :)

**Comment by SpoinkyNL** [comment]
Hey, yes sadly Logitech won't let programs assign colors to those keys.

Random colors will indeed be there in the next update along with some other
configuration options :)

Op 1 aug. 2016 11:59 schreef "palsgod" <notifications@github.com>:

**Comment by SpoinkyNL** [comment]
The latest update provides configuration options for stuff like random colors :) 

Should you run into any shortcomings / trouble feel free to open a new issue!
