### ISSUE TITLE
Cannot start application, please contact vendor.

### ISSUE THREAD

**Issue by Shnowz** [SpoinkyNL/Artemis#137]
Everything was working fine when til last night when it abruptly crashed and refuses to start, After trying to reinstall I get a window saying to contact vendor as application cannot start.
![capture](https://cloud.githubusercontent.com/assets/20974535/17596803/78077eaa-5fc9-11e6-955c-6cf50a6b54f3.PNG)

**Comment by SpoinkyNL** [comment]
Hey, what happens when you click details? If it gives you a text file or something similar could you post it please?

**Comment by Shnowz** [comment]
Yeah sorry.
---------------------------------------------------------------------------------------------------------------
PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1078.0 built by: NETFXREL3STAGE
	clr.dll 			: 4.6.1080.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: file:///E:/artemis/Artemis.application
	Application url			: file:///E:/artemis/Application%20Files/Artemis_1_2_2_0/Artemis.exe.manifest

IDENTITIES
	Deployment Identity		: Artemis.application, Version=1.2.2.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64
	Application Identity		: Artemis.exe, Version=1.2.2.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of E:\artemis\Artemis.application resulted in exception. Following failure messages were detected:
		+ Exception occurred during store operation.
		+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	* Transaction at [2016-08-11 5:18:08 PM]
		- Staging of a component file (Artemis.exe) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.Themes.Metro.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.Themes.Metro.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Ninject.dll.genman) did not succeed.
		- Staging of a component file (Ninject.dll) did not succeed.
		- Staging of a component (Caliburn.Micro.Platform.dll.genman) did not succeed.
		- Staging of a component file (Caliburn.Micro.Platform.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.dll) did not succeed.
		- Staging of a component (SpotifyAPI.dll.genman) did not succeed.
		- Staging of a component file (SpotifyAPI.dll) did not succeed.
		- Staging of a component (Process.NET.dll.genman) did not succeed.
		- Staging of a component file (Process.NET.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Ninject.Extensions.Logging.NLog4.dll.genman) did not succeed.
		- Staging of a component file (Ninject.Extensions.Logging.NLog4.dll) did not succeed.
		- Staging of a component (MahApps.Metro.dll.genman) did not succeed.
		- Staging of a component file (MahApps.Metro.dll) did not succeed.
		- Staging of a component (log4net.dll.genman) did not succeed.
		- Staging of a component file (log4net.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Caliburn.Micro.dll.genman) did not succeed.
		- Staging of a component file (Caliburn.Micro.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.Themes.VS2010.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.Themes.VS2010.dll) did not succeed.
		- Staging of a component (System.Windows.Interactivity.dll.genman) did not succeed.
		- Staging of a component file (System.Windows.Interactivity.dll) did not succeed.
		- Staging of a component (Corale.Colore.dll.genman) did not succeed.
		- Staging of a component file (Corale.Colore.dll) did not succeed.
		- Staging of a component (VirtualInput.dll.genman) did not succeed.
		- Staging of a component file (VirtualInput.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Castle.Core.dll.genman) did not succeed.
		- Staging of a component file (Castle.Core.dll) did not succeed.
		- Staging of a component (GongSolutions.Wpf.DragDrop.dll.genman) did not succeed.
		- Staging of a component file (GongSolutions.Wpf.DragDrop.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (NAudio.dll.genman) did not succeed.
		- Staging of a component file (NAudio.dll) did not succeed.
		- Staging of a component (Caliburn.Micro.Platform.Core.dll.genman) did not succeed.
		- Staging of a component file (Caliburn.Micro.Platform.Core.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.Toolkit.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.Toolkit.dll) did not succeed.
		- Staging of a component (Microsoft.QualityTools.Testing.Fakes.dll.genman) did not succeed.
		- Staging of a component file (Microsoft.QualityTools.Testing.Fakes.dll) did not succeed.
		- Staging of a component (VioletTape.WpfExceptionViewer.dll.genman) did not succeed.
		- Staging of a component file (VioletTape.WpfExceptionViewer.dll) did not succeed.
		- Staging of a component (Hardcodet.Wpf.TaskbarNotification.dll.genman) did not succeed.
		- Staging of a component file (Hardcodet.Wpf.TaskbarNotification.dll) did not succeed.
		- Staging of a component (Ninject.Extensions.Logging.dll.genman) did not succeed.
		- Staging of a component file (Ninject.Extensions.Logging.dll) did not succeed.
		- Staging of a component (DynamicExpresso.Core.dll.genman) did not succeed.
		- Staging of a component file (DynamicExpresso.Core.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.resources.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.resources.dll) did not succeed.
		- Staging of a component (CUE.NET.dll.genman) did not succeed.
		- Staging of a component file (CUE.NET.dll) did not succeed.
		- Staging of a component (NLog.dll.genman) did not succeed.
		- Staging of a component file (NLog.dll) did not succeed.
		- Staging of a component (Xceed.Wpf.AvalonDock.Themes.Aero.dll.genman) did not succeed.
		- Staging of a component file (Xceed.Wpf.AvalonDock.Themes.Aero.dll) did not succeed.
		- Installation of deployment (file:///E:/artemis/Artemis.application#Artemis.application, Version=1.2.2.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64) did not succeed.
		- Setting one or more of the deployment metadata did not succeed.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [2016-08-11 5:18:05 PM] : Activation of E:\artemis\Artemis.application has started.
	* [2016-08-11 5:18:05 PM] : Processing of deployment manifest has successfully completed.
	* [2016-08-11 5:18:05 PM] : Installation of the application has started.
	* [2016-08-11 5:18:05 PM] : Processing of application manifest has successfully completed.
	* [2016-08-11 5:18:07 PM] : Found compatible runtime version 4.0.30319.
	* [2016-08-11 5:18:07 PM] : Request of trust and detection of platform is complete.
	* [2016-08-11 5:18:07 PM] : Downloading of subscription dependencies is complete.
	* [2016-08-11 5:18:07 PM] : Commit of the downloaded application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2016-08-11 5:18:08 PM] System.Deployment.Application.DeploymentException (ComponentStore)
		- Exception occurred during store operation.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransactionCheckQuota(StoreTransactionContext storeTxn, SubscriptionState subState)
			at System.Deployment.Application.ComponentStore.CommitApplication(SubscriptionState subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.SubscriptionStore.CommitApplication(SubscriptionState& subState, CommitApplicationParams commitParams)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.UnauthorizedAccessException
		- Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IStore.Transact(IntPtr cOperation, StoreTransactionOperation[] rgOperations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Internal.Isolation.Store.Transact(StoreTransactionOperation[] operations, UInt32[] rgDispositions, Int32[] rgResults)
			at System.Deployment.Application.ComponentStore.SubmitStoreTransaction(StoreTransactionContext storeTxn, SubscriptionState subState)

COMPONENT STORE TRANSACTION DETAILS
	* Transaction at [2016-08-11 5:18:08 PM]
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: B427JKK7.HMR.application
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Set
			- HRESULT: 0x0
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Artemis.exe.manifest
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: LogitechLedEnginesWrapper.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: x64\CUESDK_2013.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: x86\CUESDK_2013.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Resources\CounterStrike\csgoGamestateConfiguration.txt
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Resources\logo.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: logo.ico
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Artemis.exe.config
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Newtonsoft.Json.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Newtonsoft.Json.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Ninject.Extensions.Factory.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Ninject.Extensions.Factory.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Xceed.Wpf.DataGrid.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Xceed.Wpf.DataGrid.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: ColorBox.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Installed
			- HRESULT: 0x0
			- File: ColorBox.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Installed
			- HRESULT: 0x0
			- Manifest: Artemis.exe.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x80070005
			- File: Artemis.exe
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.Themes.Metro.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.Themes.Metro.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Ninject.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Ninject.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Caliburn.Micro.Platform.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Caliburn.Micro.Platform.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: SpotifyAPI.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: SpotifyAPI.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Process.NET.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Process.NET.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Ninject.Extensions.Logging.NLog4.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Ninject.Extensions.Logging.NLog4.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: MahApps.Metro.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: MahApps.Metro.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: log4net.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: log4net.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Caliburn.Micro.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Caliburn.Micro.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.Themes.VS2010.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.Themes.VS2010.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: System.Windows.Interactivity.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: System.Windows.Interactivity.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Corale.Colore.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Corale.Colore.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: VirtualInput.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: VirtualInput.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Castle.Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Castle.Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: GongSolutions.Wpf.DragDrop.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: GongSolutions.Wpf.DragDrop.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: NAudio.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: NAudio.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Caliburn.Micro.Platform.Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Caliburn.Micro.Platform.Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.Toolkit.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.Toolkit.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Microsoft.QualityTools.Testing.Fakes.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Microsoft.QualityTools.Testing.Fakes.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: VioletTape.WpfExceptionViewer.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: VioletTape.WpfExceptionViewer.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Hardcodet.Wpf.TaskbarNotification.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Hardcodet.Wpf.TaskbarNotification.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Ninject.Extensions.Logging.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Ninject.Extensions.Logging.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: DynamicExpresso.Core.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: DynamicExpresso.Core.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.resources.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.resources.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: CUE.NET.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: CUE.NET.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: NLog.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: NLog.dll
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponent
			- Status: Failed
			- HRESULT: 0x1
			- Manifest: Xceed.Wpf.AvalonDock.Themes.Aero.dll.genman
		+ System.Deployment.Internal.Isolation.StoreOperationStageComponentFile
			- Status: Failed
			- HRESULT: 0x1
			- File: Xceed.Wpf.AvalonDock.Themes.Aero.dll
		+ System.Deployment.Internal.Isolation.StoreOperationInstallDeployment
			- Status: Failed
			- HRESULT: 0x1
			- AppId: file:///E:/artemis/Artemis.application#Artemis.application, Version=1.2.2.0, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=amd64
		+ System.Deployment.Internal.Isolation.StoreOperationSetDeploymentMetadata
			- Status: Failed
			- HRESULT: 0x1
		+ System.Deployment.Internal.Isolation.StoreTransactionOperationType (27)
			- HRESULT: 0x1

**Comment by Shnowz** [comment]
Could it have to do with an antivirus?

**Comment by DarthAffe** [comment]
Well,
> + Exception occurred during store operation.
+ Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

sounds like there is a Problem writing files on your E-drive.
Have you tried starting it as administrator?
Or is there any special protection on that drive/folders?

**Comment by SpoinkyNL** [comment]
Can you double-check to make sure Artemis is no longer in the installed programs list?. After that type the following in a command line window ran as administrator:
```rundll32 dfshim CleanOnlineAppCache```

Considering what DarthAffe says, could you then try unpacking the installation .zip to your documents folder and run it from there? Let me know how that goes :)

**Comment by Shnowz** [comment]
That almost worked, it did reinstall but after about 30 seconds it crashed and started doing the same thing again.

**Comment by Shnowz** [comment]
VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1078.0 built by: NETFXREL3STAGE
	clr.dll 			: 4.6.1080.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: file:///C:/Users/Mitch/Desktop/Artemis.appref-ms%7C

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\Mitch\Desktop\Artemis.appref-ms| resulted in exception. Following failure messages were detected:
		+ Activation failed.
		+ The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [2016-08-12 11:15:31 AM] : Activation of C:\Users\Mitch\Desktop\Artemis.appref-ms| has started.
	* [2016-08-12 11:15:31 AM] : Performing necessary update check as specified by the deployment.

ERROR DETAILS
	Following errors were detected during this operation.
	* [2016-08-12 11:15:31 AM] System.Deployment.Application.DeploymentException (Activation)
		- Activation failed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.SubscriptionStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.Activate(DefinitionAppId appId, AssemblyManifest appManifest, String activationParameter, Boolean useActivationParameter)
			at System.Deployment.Application.ApplicationActivator.ProcessOrFollowShortcut(String shortcutFile, String& errorPageUrl, TempFile& deployFile)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.NativeMethods.CorLaunchApplication(UInt32 hostType, String applicationFullName, Int32 manifestPathsCount, String[] manifestPaths, Int32 activationDataCount, String[] activationData, PROCESS_INFORMATION processInformation)
			at System.Deployment.Application.ComponentStore.ActivateApplication(DefinitionAppId appId, String activationParameter, Boolean useActivationParameter)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by SpoinkyNL** [comment]
That's strange, could you post the logs in Documents > Artemis > logs?

Op 12 aug. 2016 4:26 p.m. schreef "Shnowz" <notifications@github.com>:

**Comment by Shnowz** [comment]
Ive gotten it to work, uninstall, quit out of logitech software, run setup as admin, start logitch software, and it works. Heres the log from when i was getting errors I believe.

2016-08-12 11:15:15.0131|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
2016-08-12 11:15:15.4062|INFO|Artemis.Managers.DeviceManager|Intialized DeviceManager with 7 device providers 
2016-08-12 11:15:15.4062|INFO|Artemis.Managers.EffectManager|Intialized EffectManager 
2016-08-12 11:15:15.4132|INFO|Artemis.Managers.LoopManager|Intialized LoopManager 
2016-08-12 11:15:15.4132|INFO|Artemis.Managers.ProfileManager|Intialized ProfileManager 
2016-08-12 11:15:15.4272|INFO|Artemis.Managers.MainManager|Intialized MainManager 
2016-08-12 11:15:16.9409|INFO|Artemis.Utilities.Updater|Checking for updates - Current version: 1.2.2.0 
2016-08-12 11:15:16.9862|INFO|Artemis.Utilities.Updater|No update found. 
2016-08-12 11:21:08.2400|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
2016-08-12 11:21:08.6374|INFO|Artemis.Managers.DeviceManager|Intialized DeviceManager with 7 device providers 
2016-08-12 11:21:08.6374|INFO|Artemis.Managers.EffectManager|Intialized EffectManager 
2016-08-12 11:21:08.6374|INFO|Artemis.Managers.LoopManager|Intialized LoopManager 
2016-08-12 11:21:08.6374|INFO|Artemis.Managers.ProfileManager|Intialized ProfileManager 
2016-08-12 11:21:08.6614|INFO|Artemis.Managers.MainManager|Intialized MainManager 
2016-08-12 11:21:09.7867|INFO|Artemis.Utilities.Updater|Checking for updates - Current version: 1.2.2.0 
2016-08-12 11:21:09.9898|INFO|Artemis.Utilities.Updater|No update found.

**Comment by SpoinkyNL** [comment]
Ok that's interesting o.O 
Perhaps it has something to do with the installer we use.. hence #112 I'm not sure. Anyway, I'm closing this, should something come up again feel free to make a new issue

Thanks for reporting back!
