### ISSUE TITLE
[GAME REQUEST] Mirror's Edge Catalyst

### ISSUE THREAD

**Issue by mohsin-mulla** [SpoinkyNL/Artemis#138]
Hey :)

This game already has partial support for RGB lighting with Logitech mice, as can be seen here:
https://www.youtube.com/watch?v=Vucva55DJGA

Maybe this could be extended to include keyboards too? Going further, maybe it's also possible to expand it so that the keyboard lights up based on the colours of the area you are situated in. e.g. The View District has a very pink/purple theme associated with it.

Thanks and keep up the excellent work!

**Comment by SpoinkyNL** [comment]
Hey, I wouldn't mind taking a look but I sadly don't own Mirror's Edge Catalyst, perhaps if it goes on sale I'll get it and try to add support
