### ISSUE TITLE
[REQUEST] Compatability for Logitech G19s

### ISSUE THREAD

**Issue by Pallaxis** [SpoinkyNL/Artemis#141]

**Comment by SpoinkyNL** [comment]
Hi, this is technically already supported using the Generic Device layertype. However, you can't do this without selecting a keyboard. 

I hope to change this, so that you can also create profiles (and include the Generic Device layer in them) without a keyboard

**Comment by SpoinkyNL** [comment]
If you set keyboard to None and create generic layers, it should work with the G19 now just fine :)
