### ISSUE TITLE
[GAME REQUEST] Euro Truck Simulator 2

### ISSUE THREAD

**Issue by mohsin-mulla** [SpoinkyNL/Artemis#142]
Hello,

I feel like I may be annoying you slightly with the request I've already made but... I have a suggestion to add support for Euro Truck Simulator 2.

I've done some research myself, and the game provides an SDK which allows for streaming of telemetry data from the game to a text file. Someone has kindly developed a plugin which "transports the telemetry stream via a Memory Mapped File", available [here](https://github.com/nlhans/ets2-sdk-plugin). I figured this could be used to change the keyboard lights depending on the current output of the telemetry.

For example, gears could be mapped to the F1-F12 keys, with each key highlighting the current gear selected, especially as the 12-speed transmission is the most common configuration. So if you are in 5th gear, the F5 key will be lit.

Another example could be RPM, driving at 500 rpm (also idle speed) can highlight the keys as green, and as you go up in the rev range, the keys change from a green to a gradual red, similarly to how you've developed the CS:GO health keyboard lights.

Other examples could include dimming and flickering the keyboard lights when the engine state is changed to on, similarly to how a real vehicle works where the lights flicker slightly as the engine is started. Changing the brightness key to mimic that of a light indicator, so low beams have a green light and high beams have a blue light. There's probably more useful examples too, but that's all I can think of for now.

A free demo is available on Steam for this game, and in theory, adding support for this game will also add support for American Truck Simulator, as they share the same platform.

Hope you can consider this!

Thank you

**Comment by SpoinkyNL** [comment]
Looks very easy to implement. I'll get the demo and see what I can do :)

**Comment by mohsin-mulla** [comment]
Awesome! Looking forward to it! :smile:

**Comment by SpoinkyNL** [comment]
Just a quick update: That SDK sadly was broken on 64 bit but I fixed it.

I'm currently confusing people by playing with my blinkers all the time because the show up on the keyboard ^^

**Comment by mohsin-mulla** [comment]
Wow, that sounds like you've already made some good progress :open_mouth:

**Comment by SpoinkyNL** [comment]
The latest release has support now: https://github.com/SpoinkyNL/Artemis/releases/tag/1.3.0.0
I've not had time to make a good default profile yet but I'll include it in the next update later this week

**Comment by mohsin-mulla** [comment]
You are an absolute saint! :) Can't believe you did it this quickly as well.

There's a few bugs I've found which I'll create a new issue for, and maybe I might share my profile once I've fine tuned it
