### ISSUE TITLE
Couldn't connect to your Razer BlackWidow Chroma

### ISSUE THREAD

**Issue by schokkya** [SpoinkyNL/Artemis#146]
Hi,

Today I have just received my Razer BlackWidow Chroma and installed Razer Synapse. 
Whenever I try to launch Artemis I get 'Couldn't connect to your Razer BlackWidow Chroma. 
Please check your cables and try updating Razer Synapse.

If needed, you can select a different keyboard in Artemis under settings."

I tried other keyboards, but it doesn't seem to work. This program used to work when I used my Logitech G810 though. My Razer Synapse is updated to the most recent version as well. If you need any logs/files, let me know!

**Comment by SpoinkyNL** [comment]
Hey, can you double check that you have Chroma Apps enabled? Like so: https://rzr-insider-assets.s3.amazonaws.com/2015/11/175869_4ec0b309cb8f3b9284c26eb5c864ee97.PNG

**Comment by schokkya** [comment]
Can confirm this fixed it, thanks for the reply!
