### ISSUE TITLE
Unable to add additional animated layer to the Overwatch profile 

### ISSUE THREAD

**Issue by ddstevens** [SpoinkyNL/Artemis#149]
I copied the default profile and added a layer which is conditionally displayed when the "CanChangeHero" condition is true.  I enabled pulse animation and set an animation speed.  The layer is animated in the preview UI, but the layer isn't animated in game.  I see the layer at the correct times in the game but the animation doesn't play.

Attached is the profile I modified.  I changed the extension to txt so I could attach it.

I'm using version 1.3.1.0 of Artemis.  My keyboard is a K70 RGB Rapidfire.

[Overwatch.txt](https://github.com/SpoinkyNL/Artemis/files/441449/Overwatch.txt)

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you earlier. Looks like I broke the pulse animation in the last update, I've fixed for the next release.

Let me know if this solved your issue :)

**Comment by ddstevens** [comment]
Works great in game. Thanks! I noticed the preview UI does not display the animation properly any more though.
