### ISSUE TITLE
Pulsing Effect is broken

### ISSUE THREAD

**Issue by Bluethefurry** [SpoinkyNL/Artemis#153]
Using the pulsing effect makes it flicker, no change on the keyboard itself

**Comment by SpoinkyNL** [comment]
Hi, I've just pushed an update that should resolve this, what version of Artemis are you running (it's in the bottom when you open settings)

If it's not 1.3.2.0, please restart Artemis to let it update and try again

**Comment by Bluethefurry** [comment]
Just Updated, fixed when using it, but the preview is broken for me!

**Comment by SpoinkyNL** [comment]
Hello, this is fixed with the latest update. If you restart Artemis it should be applied :)
