### ISSUE TITLE
Settings in Audio Visualizer don't seem to work properly

### ISSUE THREAD

**Issue by Shadow091995** [SpoinkyNL/Artemis#155]
Hey,

I downloaded the program a few days ago and I am really happy with it! 
But I encountered that the Audio Visualizer settings don't change anything on my g810. I changed the colors (violet, magenta, red) but they still remain standard (green, yellow, red). Also the "grow bars bottom"-, "Volume sensitivity multiplier"- and "Bar fade-out speed"-options change nothing, also not after saving the changes. 
It also resets the settings after closing and reopening the program. Administator mode doesn't change anything. My OS is Windows 10 Enterprise 64-Bit.

I hope you can help :)

**Comment by SpoinkyNL** [comment]
Hey, this could be a bug but just to be sure, are you on the latest version
where audio visualizer and type waves are layer types?

In older versions these were separate effects but now they are part of the
layer system

Op 5 sep. 2016 12:34 schreef "Shadow091995" <notifications@github.com>:

**Comment by Shadow091995** [comment]
I'm not sure what you mean by "Layer types" but it says my version number is 1.3.2.0
The program looks like this: http://prntscr.com/cec9bq

**Comment by SpoinkyNL** [comment]
Alright I see what's confusing, my bad!
The audio visualization tab is obsolete, I'll remove that in the next update.
Instead you can go to Windows Profile and make a new profile, add a layer and change the type to 'Keyboard - Audio visualization' or 'Keyboard - Key press' like so:

![Layer types](http://i.imgur.com/Ct6oKD6.png "Layer types")

**Comment by Shadow091995** [comment]
Oh! Hehe! Thank you for helping! That works quite good and I'll also keep testing other stuff in your program :)
