### ISSUE TITLE
Skype integration?

### ISSUE THREAD

**Issue by Shadow091995** [SpoinkyNL/Artemis#156]
Hey, Aurora has this Skype integration thing, where some keys pulse in colors if someone calls and some other keys pulse if you get a message. Is it possible to include something like this into Artemis? 
I mean like Aurora very much too, but it misses the stuff that Artemis has.

Greetings :)

**Comment by antonpup** [comment]
@Shadow091995 I would love to improve Aurora as much as I can. What features do you find it lacking?

**Comment by SpoinkyNL** [comment]
Hey, I'll look into adding Skype to the Windows Profile datamodel, so you can create your own layers that pulse/light up when Skype calls/messages occur :).

**Comment by Shadow091995** [comment]
@SpoinkyNL Thank you! :D 

@antonpup Aurora unfortunately has no audio visualizer and I can't really use real custom effects. It's mostly limited to Rainbow Shift, Color Breathing or Single Color. I really like the feature in Artemis, where you can customize coloring and position, and create custom effects. (Eg.: http://prntscr.com/cfxkdr )
But I really love the CS:GO Profile in Aurora, didn't come to testing the Artemis one yet though

**Comment by SpoinkyNL** [comment]
I'm not sure what Aurora offers when it comes to CS:GO, but Artemis has a datamodel that contains nearly all the data CS:GO outputs through their API. 

This means you could likely make a profile that exactly matches Aurora's CS:GO support. But let's please keep discussion about other applications within their own repositories.

**Comment by Sokonomi** [comment]
I would love to see a "pending call/message" blinker! I often have my headset on its stand when im AFK, so the incoming call ringer doesn't alert me. My entire machine blinking would do it though. :P

**Comment by SpoinkyNL** [comment]
I've been looking into it, sadly the Skype SDK is 32 bits only so I'll have
to make a tiny app that automatically runs in the background for it to work

Op 23 okt. 2016 4:32 p.m. schreef "Sokonomi" <notifications@github.com>:
