### ISSUE TITLE
Color Customization in Audio Visualization

### ISSUE THREAD

**Issue by brando132** [SpoinkyNL/Artemis#157]
Hi, I've been using this program for several days now and I love it, lately I have been using the visualization effect while listening to music and working on my pc and notice that now matter what I try I can't change the colors used for the effect.

I've tried changing the colors, saving changes, disabling effect, re-enabling, saving again and nothing seems to help. When I try to reset the effect I get an exception as follows:

```
An unexpected error occurred in Artemis.

Object reference not set to an instance of an object.
____________________________________________________
System.NullReferenceException

Message:
Object reference not set to an instance of an object.

Stack Trace:
   at Artemis.ViewModels.Abstract.EffectViewModel.<ResetSettings>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void MoveNext()

Source:
Artemis

HResult:
-2147467261
```

Thanks for your time and keep up the great work!

**Comment by SpoinkyNL** [comment]
Hey, sorry for the late reply, I've been super busy :c

Audio Visualization is no longer a separate effect but part of the layer system. In the next update I've replaced the old tab with an explanation on where it went. I should've done that right away, my bad!

To use it, you can go to Windows Profile and make a new profile, add a layer and change the type to 'Keyboard - Audio visualization' like so:

![Layer types](http://i.imgur.com/Ct6oKD6.png "Layer types")
