### ISSUE TITLE
Switching Profiles/Modes with Keyboard

### ISSUE THREAD

**Issue by mrjindal** [SpoinkyNL/Artemis#158]
Hi there!

Could it be possible to allow switching between profiles and/or Effects modes through the physical keyboard keys (like in the case of profiles set up with the Corsair utility engine). 

I would love to be able to switch between say the Audio Visualisation and the Windows Profile mode by using M1,M2,M3 keys or any of the Macro keys. 

I appreciate the work and effort 

Thanks

**Comment by SpoinkyNL** [comment]
Hey, hotkeys is something I'd like to do. That way you could have a macro key press a hotkey and Artemis would then select that profile. Modes are going away (everything the modes do can also be done wit profile layers, including audio/key press stuff) so those won't really be interesting

**Comment by mrjindal** [comment]
Fantastic! It would be cool to see those changes. 

Best of luck. I will be tuned in
