### ISSUE TITLE
Witcher 3 Artemis mod not working with the update

### ISSUE THREAD

**Issue by mrjindal** [SpoinkyNL/Artemis#159]
Hi

The mod that Artemis installs for Witcher 3 does not seem to be working after I updated my game to 1.31. Is there any way that could be fixed? 

I am getting the following errors:

Error [content0]game\gui\hud\modules\hudmoduleradialmenu.ws(615): Could not find function 'ShouldUseInfiniteWaterBolts'
Error [content0]game\gui\menus\charactermenu.ws(253): Function 'MutationResearchWithItem' does not take 3 param(s)
Error [content0]game\gui\menus\charactermenu.ws(1093): Could not find function 'MoveMutagenToSlot'
Error [content0]game\gui\menus\alchemymenu.ws(62): Could not find function 'GetAlchemyFilters'
Error [content0]game\gui\menus\alchemymenu.ws(126): Could not find function 'SetAlchemyFilters'
Error [content0]game\gui\menus\alchemymenu.ws(189): Could not find function 'AddExpandedAlchemyCategory'
Error [content0]game\gui\menus\alchemymenu.ws(193): Could not find function 'RemoveExpandedAlchemyCategory'
Error [content0]game\gui\menus\alchemymenu.ws(307): Could not find function 'GetExpandedAlchemyCategories'
Error [content0]game\gui\menus\craftingmenu.ws(103): Could not find function 'GetCraftingFilters'
Error [content0]game\gui\menus\craftingmenu.ws(170): Could not find function 'SetCraftingFilters'
Error [content0]game\gui\menus\craftingmenu.ws(266): Could not find function 'AddExpandedCraftingCategory'
Error [content0]game\gui\menus\craftingmenu.ws(270): Could not find function 'RemoveExpandedCraftingCategory'
Error [content0]game\gui\menus\craftingmenu.ws(474): Could not find function 'GetExpandedCraftingCategories'
Error [content0]game\gui\menus\glossarybestiarymenu.ws(103): Could not find function 'AddExpandedBestiaryCategory'
Error [content0]game\gui\menus\glossarybestiarymenu.ws(107): Could not find function 'RemoveExpandedBestiaryCategory'
Error [content0]game\gui\menus\glossarybestiarymenu.ws(162): Could not find function 'GetExpandedBestiaryCategories'

Warning [content0]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [content0]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

Thanks in advance. PS: I have no other mods installed.

**Comment by SpoinkyNL** [comment]
Hi, usually a Witcher 3 update breaks any mods you have, including the one Artemis relies on.

I'll update it and hopefully have it ready in a day or two. When I do I'll let you know, Artemis should automatically update the next time you start the program as well.

**Comment by mrjindal** [comment]
Thanks, appreciate the help :) Will be on the lookout.

**Comment by SpoinkyNL** [comment]
Hello, this is fixed with the latest update. If you restart Artemis it should be applied :)

**Comment by mrjindal** [comment]
Thanks!! My life just got better 👍  :)

**Comment by SpoinkyNL** [comment]
Haha great to hear :)
