### ISSUE TITLE
mouse and keyboard disconnect randomly

### ISSUE THREAD

**Issue by lolitsjohn** [SpoinkyNL/Artemis#160]
Amazing software first of all, many thanks @SpoinkyNL . Using a Logitech G810 and a Razer Chroma mouse. I'll hop into Overwatch or Starcraft 2 and sometimes my mouse and keyboard will disconnect and I'll get the window boop sound that something was disconnected, then after a few seconds they will reconnect and I hear the windows boop sound that they are reconnected. Any idea why this might be happening and how to fix? Thanks

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you earlier, does this only occur with Artemis running?

**Comment by lolitsjohn** [comment]
No worries at all I'm sure you have a busy schedule. Yes it only occurs with Artemis running.

**Comment by SpoinkyNL** [comment]
Hello, the latest version of Artemis uses the new Logitech SDK. Could you see how it goes with that?

Thanks!
