### ISSUE TITLE
Ripple effect not working on Azerty

### ISSUE THREAD

**Issue by Dangoke** [SpoinkyNL/Artemis#164]
I live in one of the few countries who like to be "special" and use Azerty instead of Qwerty. Now I made myself a simple ripple effect but the ripples appear from the places where the buttons would be if the keyboard I used would be Qwerty. So say I press A, the effects appear from where Q is on my keyboard. Or when I press W, the effects appear from Z. Is there any way for me to fix this or am I out of luck?

**Comment by SpoinkyNL** [comment]
Hey, which keyboard are you using? :)

Op 20 sep. 2016 16:29 schreef "Dangoke" <notifications@github.com>:

**Comment by Dangoke** [comment]
Oh, sorry, forgot to mention that. Derp! I'm using the Logitech G910!

**Comment by JewsOfHazard** [comment]
It seems like that would most likely be an issue on Logitech's end. I know with corsair the API works based on the key but logitech does it based on a bitmap. I assume the bitmap is mapped to qwerty keyboards and doesn't adjust for Azerty. We can look more into fixing this but it might be a hack.

**Comment by SpoinkyNL** [comment]
I've got it fixed in the next version, it's drawing fine but the key positions were off. 
Might need a bit of testing though, Belgian keyboards are full or subtle differences to 'normal (:p)' ones.

**Comment by Dangoke** [comment]
Haha, thanks! And yeah, I guess we just like being special... in the wrong/strange ways! :p Thank you!

**Comment by Dangoke** [comment]
It's working now (with the newest 1.4 update), thanks a lot :)
