### ISSUE TITLE
G910 Orion Spark Issues

### ISSUE THREAD

**Issue by cheeze97** [SpoinkyNL/Artemis#165]
Enabling my g910 orion spark won't work.

I Installed Visual C 2012
I reinstalled lgs
I reinstalled Artemis 

I keep getting the error that I should install Visual C 2012 even though it is installed

**Comment by SpoinkyNL** [comment]
Hello, sorry for not getting back to you sooner, I've been so busy lately :c

Did you install the Visual C++ 2012 Redistributable using the following link? https://www.microsoft.com/download/confirmation.aspx?id=30679

Make sure you download and install both the x64 and the x86 version just to be sure
