### ISSUE TITLE
Type Wave off center.

### ISSUE THREAD

**Issue by Quinntox** [SpoinkyNL/Artemis#166]
Striking a key to initiate a wave Initiates the wave one key left of the initially struck key. When I slow it down it looks as if it is even in the upper part of the left key causing the timing to be off.  It happens in in all types wave affect. 

Windows 10 64 bit English US keyboard
G910 Orion Spark running Logitech Gaming Software  8.87.116
Artemits 1.3.3.0 full

**Comment by SpoinkyNL** [comment]
Hello,

I also noticed that the key positions are off for the G910. I've adjusted them for the next version. It might not be 100% accurate on very small effect sizes, but should match a lot better.
