### ISSUE TITLE
Logitech G910 Issues

### ISSUE THREAD

**Issue by CSgower** [SpoinkyNL/Artemis#167]
Program seems to not detect CSGO and launch the overlay, Logitech Gaming software is overtaking it

**Comment by LokeYourLord** [comment]
Try disabling the following options in the Logitech Gaming Software (options are in German, but they are the only two checkboxes anyways, so don't worry, you can't do anything wrong here):

From this:
![image](https://cloud.githubusercontent.com/assets/5807595/19097605/516f4658-8aa6-11e6-8ae8-2c71d6558129.png)

To this:
![image](https://cloud.githubusercontent.com/assets/5807595/19097618/63491480-8aa6-11e6-84d4-d85629edca16.png)

That should work, feedback is welcome :)

**Comment by SpoinkyNL** [comment]
Hello, did this resolve your issue? :)

**Comment by CSgower** [comment]
yes
