### ISSUE TITLE
Request: Use color cycling for Audio Visualization (Any Keyboard)

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#168]
So basically i would like it if there was a feature that just used the standard Logitech Gaming Software its "Light (Rainbow) Wave" for the color selection of various effects like Audio Visualization or alike, as i would want to use the Rainbow and not having to worry about choosing all rainbow colors on the gradient bar (also because the colors in gradient only change where the gradient is defined, though i would want the colors to be random everytime).

**Comment by LokeYourLord** [comment]
Something nice to also have would for the Audio Visualization (or any profile for that matter) the G1-G9 keys to be lit and also the "G" and "G910" logo to be lit as well, that would be cool.

**Comment by SpoinkyNL** [comment]
Hey, Logitech has recently release an update to their SDK that should allow me to color more keys, not sure about the G-logo. I'll soon update Artemis to use that new SDK.

I'm not quite sure what you mean with color cycling? Could you perhaps illustrate this?

**Comment by LokeYourLord** [comment]
Oh god thanks for replying, thought i was never getting a reply (not meant offensive, thanks again :D ). I mean this function here, i made a short Video for it:

https://youtu.be/k5L9VGiTCF4

Also, if not the G logo, maybe the opaque G910 logo? I hope you can illuminate them all at some point :D

**Comment by LokeYourLord** [comment]
It might also be somewhat hard to understand what i mean, but what i in very basic terms mean, is that while Audio Visualization is going on, and each individual key is being lit when a sound comes on, i want that key color of that key (every key that is being lit) to be a rainbow wave, but for the entire keyboard, so like the wave moves across the keyboard somewhat (you can imagine) in the background, and the second a key is being lit due to Audio Visualization, that rainbow wave comes to view. Try the Logitech Spectrogram. It works quite well for testing my idea, though the second you press a key the program freezes and so does your keyboard lighting.

**Comment by SpoinkyNL** [comment]
What you showed is already possible :)
Check out de demo profile, it should include an animated layer that does
what you showed in the video.

To create one yourself, create a new layers, set the animation to Slide
Right and put the animation speed slides to halfway.

Then you create a gradient brush by clicking on colors and selecting
gradient in the top, add multiple colors and make sure you end with the
same color you started with to create a smooth transition.

For some examples you can check out the demo windows profile that's
included by default

Op 5 okt. 2016 12:08 schreef "LokeYourLord" <notifications@github.com>:

**Comment by LokeYourLord** [comment]
I see. But wouldn't it then be easier making like a little checkbox that automatically adds this for you? See it then more as a recommendation instead of requested feature :)

**Comment by Deyta** [comment]
I would really love to have a checkbox like that, been sitting on creating a proper color brush for hours now and I haven't even figured out how to create a third color for the gradient... What I've also not been able to find and what would be my suggestion: (rainbow-)color waves for the spectrogram. 
Other than that, huge thanks to you spoinky for doing this incredible stuff! :)

**Comment by LokeYourLord** [comment]
@Deyta Ye, it would take hours creating a proper brush for that, easier to just implement the standard SDK values like from the LGS instead.

**Comment by SpoinkyNL** [comment]
Hey folks, I feel like the color selection tools aren't very intuitive right now. It kinda sucks because it's hard to find a good color selector, I'll look into improving this one myself.

In the meanwhile this is how I create brushes fairly quickly:
https://www.youtube.com/watch?v=DH4XWd5KRho

The confusing parts are the start and end points, the numbers work like described on this page: https://wpf.2000things.com/2011/02/10/213-changing-the-gradient-line-in-a-linear-gradient-brush/ 

But that's not ideal for end users to be dealing with, so I'll be looking into simplifying this and including a bunch of presets.
