### ISSUE TITLE
"Checking if keyboard "Corsair RGB Keyboards" can be enabled", unable to connect.

### ISSUE THREAD

**Issue by AaronMickDee** [SpoinkyNL/Artemis#169]
I've updated Artemis to the latest release (1.3.3.0), and Corsair CUE (1.16.42) and still the same.

Keyboard is a Corsair Strafe RGB.

**Comment by SpoinkyNL** [comment]
Hello, could you try it with the latest CUE2 instead?

You can find it over here: http://www.corsair.com/en-us/landing/cue

**Comment by AaronMickDee** [comment]
I tried that, and it doesn't fix it.
Strangely enough, using version 1.0.2 of Artemis works.

**Comment by AaronMickDee** [comment]
Ok. I've wiped my Windows 10, started from scratch. Installed CUE2, then Artemis. Still doesn't work. Could it be the new CUE2 update that was released a few days ago that did it in?

**Comment by SpoinkyNL** [comment]
Hmm that's odd. I'm running CUE 2.5.66 and Artemis functions fine, could you double-check to see if the SDK is enabled like so:
![image](https://cloud.githubusercontent.com/assets/8858506/19161884/d8df446c-8bf5-11e6-8e65-9c143081905f.png)

Also it might be worth installing [Visual Studio C++ Redistibutable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) be sure to grab the x64 version :>

Should that still not work could you head to Settings and set the log level to debug. Then reselect the keyboard an post the log(s) in Documents > Artemis > logs

**Comment by SpoinkyNL** [comment]
Great :) I'm sorry you head to clear your Windows for that :c

**Comment by AaronMickDee** [comment]
It was planned!

**Comment by JewsOfHazard** [comment]
Everyone should clear their windows machine every few years anyways /shrug

**Comment by Teascade** [comment]
I have this issue currently, what I've done so far:
- Checked that I'm currently running iCUE 3.12
- I have Microsoft Visual C++ 2017 installed and cannot therefore install the 2015 version
- Checked also that Enable SDK in iCUE is enabled

Loops between "Checking if ´corsair rgb keyboard´ can be enabled´ and `Enabling keyboard: Corsair RGB keyboard`

For context I have Corsair K70 Mk.2
