### ISSUE TITLE
Connection error with Logitech G810

### ISSUE THREAD

**Issue by medifin** [SpoinkyNL/Artemis#170]
https://gyazo.com/fb10fc9b1ac4e3a8ee3b187728b1a31c

I have reconnected the cable, rebooted my PC and reinstalled LGS.

**Comment by SpoinkyNL** [comment]
Hey, this can happen when you updated LGS while Artemis was running.

Could you try shutting down Artemis and any game that might support the
G810 (such as GTA V), uninstalling LGS and reinstalling it again?

Op 5 okt. 2016 14:14 schreef "medifin" <notifications@github.com>:

**Comment by medifin** [comment]
Thank you, it worked

**Comment by SpoinkyNL** [comment]
Great, thanks for letting me know :)

I'll add it to the FAQ as well
