### ISSUE TITLE
Suggestion: Change the audio device to the current audio device for the Keyboard Audio Visualization

### ISSUE THREAD

**Issue by AaronMickDee** [SpoinkyNL/Artemis#175]
I was showing my buddy Artemis, and he loved the keyboard visualization. However, he uses different audio outputs throughout the day. So throughout the day, his keyboard visualization only works whenever he's using the device used to set up Artemis.

Is it possible to add in the program to change the audio device based on whatever device output is being used? Whether is listens to whatever audio device is in use and changes on the fly, or listens to all at once?

**Comment by SpoinkyNL** [comment]
Hey, 

That shouldn't be too di

**Comment by SpoinkyNL** [comment]
Hey, I'll work on this in #228
