### ISSUE TITLE
Request: More variable

### ISSUE THREAD

**Issue by Baanor** [SpoinkyNL/Artemis#176]
Hi, i've used your soft for some days now, and i have to say it it's really great.

But it would be wonderful if we can have more variable possible for configuration.

For example, I would like that when i press my ulti key in Overwatch a "glow" effect start from this key, i've been able to limit the key press only when the ulti is Ready but i would like to make this option when the Ulti key is press too. So put precise key press as trigger would be great... and at best the implementation of our own Variable (Whanted to make a pulse effect at Headshot in CS but couldn't without using some variable has a "limiter").

And at last, being able to put premade variable (like UltiReady in OW) as an answer  for condition.

i don't know enought about coding to know if this can be done without problem or if it's hard to implement.

**Comment by SpoinkyNL** [comment]
Hey,

I can probably expand the key waves to include trigger conditions (so you can select one or more keys on which it'll trigger).

I don't quite understand what you mean by a variable having a limiter, could you elaborate?

**Comment by Baanor** [comment]
What i was trying to do was to make a wave on my keyboard everytime i put an headshot, but what you receive from CS api is just a number of headshot done during the round.

So to make it happen only once and not going in an infinite loop, I think i would have needed something like that:

 if 
       roudkillHS = 1
and  
        V(ariable)= 0
V=V+1

So like that only when i put the headshot the effect start for some time, and at the second check (Frame?) the variable who is now at 1 block the infinite loop.

**Comment by SpoinkyNL** [comment]
Seems like this could easily done in LUA once I've implemented that. 
In the meanwhile I'll look into adding MadeKill and MadeHeadshot variables that will be true for 0.5 sec after you made a kill/headshot so you can make an event with them.

P.S.: Events themselves are currently buggy, I hope to have time to look into that very soon

**Comment by Baanor** [comment]
Well good luck then!

**Comment by Baanor** [comment]
Thanks for the made_kill and made_kill_hs variable in th 1.4.0.

Wish you good luck for the futur.
