### ISSUE TITLE
G910 Audio Visualization Issue

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#178]
So since the Logitech SDK has been updated, a new row of buttons has been added to the animation layer, however, because of the size increase, the entire right row has been left out of the animation layer (for Audio Visulization, probably others too), see here: 
![image](https://cloud.githubusercontent.com/assets/5807595/19431167/96196580-9457-11e6-99e1-4669ed5f05da.png)

The entire row upwards from the right ENTER button to the - (MINUS) button is never lighting up, not a single time, and i tried very high frequenzy tones/songs.

PS: Thanks for the Rainbow preset, but is there any possibility in adding an animation to it to? So like that it moves across the keyboard from top to bottom or left to right like in the LGS presets (while the AUDIO layer is being used at the same time)?

**Comment by SpoinkyNL** [comment]
Hey, if those keys aren't lighting up please shutdown Artemis and update LGS

The editor isn't a 100% accurate for every keyboard, so it might not cover those keys while in reality it does. 

I'll look into the animation as well, I thought that was already possible

**Comment by LokeYourLord** [comment]
LOL i just updated LGS a little over a few hours ago, and now there is a new update again, my fault. I was at version 88.2, that is why it didn't cover them. And ye i know, the button positioning is a bit of, but i know they are being covered (i am often testing out every key for itself).

About the animation thing, you did add the possibility to change direction of the colors (horizontal, etc), but not if they can also move across the keyboard. It is there for other types of profiles, but not for the Audio Visulization.

**Comment by LokeYourLord** [comment]
EDIT: Actually, the keys are being covered, but not by the animation itself. You see, the background (if enabled) lights up the keys, but when disabled, the keys aren't being lit by the actual animation layer. I upload a short vid.

**Comment by LokeYourLord** [comment]
Here, you will see what i mean: https://youtu.be/k2hVXriLK34?t=58s

**Comment by SpoinkyNL** [comment]
Hey, I've quickly hacked it in to see if it's possible, and I can add it as an option in the next update.
This is how it looks:
https://gfycat.com/ValidImpoliteAfricanpiedkingfisher

**Comment by LokeYourLord** [comment]
AWESOME, that is exactly what i wanted :D 👍 

So did you see the video i uploaded?

**Comment by LokeYourLord** [comment]
Since you have been so helpful, and the software is totally bonkers, is there any possibility we can donate to you?

**Comment by SpoinkyNL** [comment]
I saw your video yeah, I figured that's what you meant. I thought the audio visualization layer already supported that but it doesn't :p

I've never really thought about donations since it's just a hobby project, but maybe when the website is done :) 

For now the biggest help you can give is letting your friends know about Artemis! :>

**Comment by LokeYourLord** [comment]
Funny because i did, i showed this to 13 friends now :) But you should make a PayPal donations button on the GitHub main page :)

**Comment by SpoinkyNL** [comment]
Hey, I couldn't fit this into the next update, it's been over a month already since the last update so I didn't want to delay it any further :c I'll be sure to add it to the next update though!

**Comment by LokeYourLord** [comment]
@SpoinkyNL Seems that it is already fixed, the bar now lights up just fine :)

**Comment by SpoinkyNL** [comment]
Closing this in favor of #228
