### ISSUE TITLE
Feature Request: Per key | Cap/Scroll/Num lock Conditions

### ISSUE THREAD

**Issue by techy105** [SpoinkyNL/Artemis#179]
Hey,
Would it be possible to add conditions for "When Key X is pressed" or "Caps lock is true/false" ?

p.s. I cant believe I hadn't discovered your software earlier. Great work!

**Comment by SpoinkyNL** [comment]
Hello, I'm planning to add a filter option to the key press layer type, would that suit your needs? 

Caps lock could be a good addition as well, I might look into a few generic conditions that work in every game, this could be one of them

**Comment by techy105** [comment]
That sounds like it would be perfect!

**Comment by SpoinkyNL** [comment]
Hey, in 1.5.0.2 I've added the Cap/Scroll/Num lock conditions to the WindowsProfile. I'll expand the Key press as well in the next update
