### ISSUE TITLE
Ambilight effect?

### ISSUE THREAD

**Issue by Sokonomi** [SpoinkyNL/Artemis#180]
Not so much an issue as it is a feature request.

I was wondering if it would be difficult to develop a feature that will match your lights to the monitor (or part of it). Looking at the blue sky in a game turns everything blue, looking at a red truck turns everything red, etz.

No need to analyze an entire screen though, maybe you can have it make rapid snapshots of a specified set of pixels to attempt to average out an RGB value to be passed on.

**Comment by LokeYourLord** [comment]
You mean like some RGB leds on the backside of some Smart-TVs do? I know my parents have one, a Panasonic Smart TV which has RGB leds on the back side, which change color to whatever is closest to the border of the actual screen, so if there is sky visible, the upper TV side will turn light-blue, and if there is grass in the picture at the bottom, the back side bottom RGB will turn green.

**Comment by Sokonomi** [comment]
Yup, thats the stuff. If I could get my Logitech G13 / G910 / G600 to color match my monitor it would look pretty cool. ;)

**Comment by Sokonomi** [comment]
Check it out, Razer already has the capability for it!
https://youtu.be/jrTWqH6886w

Please try to make this happen in Artemis, I would legit pay for it. :')
Imagine being able to use this as a background layer, so many possibilities.

**Comment by Sokonomi** [comment]
Setup tutorial; https://youtu.be/nGSE_yX__ww

I like how it lets you "zone out" your devices. Would be cool if I could stretch my effects across multiple devices rather than just separately.

**Comment by DarthAffe** [comment]
@SpoinkyNL If you don't want to do this on your own you could assign it to me.
Next weekend I should have enough time to do this :)

**Comment by SpoinkyNL** [comment]
@DarthAffe appreciate that, I've done something like this in the past using SharpDX but I had a memory leak I couldn't get rid of.

If you'd like to check it out: https://github.com/SpoinkyNL/Artemis/tree/e2b449cd02338df64725d9c493ff1af196b879d5/Artemis/Artemis/Modules/Effects/AmbientLightning

You can also just start from scratch of course. That solution used about 8% CPU iirc.

Look forward to what you come up with :)

**Comment by DarthAffe** [comment]
@SpoinkyNL Could you take a look at [this](https://github.com/DarthAffe/Artemis/blob/b5fb799f2e8fe7018f403e5c2489a1dd4b6dbee1/Artemis/Artemis/Profiles/Layers/Types/AmbientLight/AmbientLightType.cs) and check if this is a correct layer implementation? It works so far (still tons of work to do), but I'm not sure if I didn't miss something.

**Comment by SpoinkyNL** [comment]
Looks great!

Using expression bodies for Name, ShowInEditor and DrawType makes a lot more sense too, I'll change mine to that s well :)

Make sure you put a [JsonIgnore] attribute on properties you don't want saved to disk (probably like line 23 and 24)

Look forward to the result already ^^

**Comment by DarthAffe** [comment]
I thought it's possible to link pull requests without resolving the issue ... well: https://github.com/SpoinkyNL/Artemis/pull/187

**Comment by SpoinkyNL** [comment]
Update with this included is live, thanks again!
