### ISSUE TITLE
Cooler Master Masterkeys Pro L support

### ISSUE THREAD

**Issue by jassalmithu** [SpoinkyNL/Artemis#184]
Any chance the keyboard could be supported. it's full RGB and has SDK download available here 

http://www.coolermaster.com/peripheral/keyboards/masterkeys-pro-l/

**Comment by SpoinkyNL** [comment]
Hey, I do not own this keyboard so it's difficult for me to add support (these things are kind of trial and error since the SDK isn't meant for C#, the language Artemis is written in, although it can be done.)

I'll see what I can do though!

**Comment by SpoinkyNL** [comment]
Hey, you'll find support for this in the next update :)

**Comment by jassalmithu** [comment]
Thanks a lot for your work, I am watching this everyday for an update and will also post to reddit when it is. Again, thanks man the whole CM community definitely gonna love this.

**Comment by SpoinkyNL** [comment]
You're welcome, update is live!
