### ISSUE TITLE
Audio-Spectrograph causes high CPU-load even if not used

### ISSUE THREAD

**Issue by DarthAffe** [SpoinkyNL/Artemis#186]
I just profiles to find the cause of the high (5-7% on my PC) CPU-load of Artemis even if no profile or anything is active.
It seems like the Audio-Spectrograph is doing a lot of stuff all the time.

I haven't looked at the code so far but it should not be too hard to prevent that - I'll open a pull-request or comment again in the next days.

**Comment by SpoinkyNL** [comment]
Hey, I've been cleaning up quite a bit (Spotify support was also using 2% CPU when active).

The profile editor needs some refactoring. For each module the profile editor is always loaded, with one profile, this is wasting memory but might also waste CPU on some layer types. It's not as bad as it was, before I cleaned up all profiles were loaded at all times.. 

Currently I'm down to hovering between 0-1% CPU/100,3MB RAM with the audio visualization profile and a LUA script drawing a line on the keyboard. This goes up quite a bit when you open the UI but it goes down again when the GC cleans up.

Might be different on your machine though, could you give it a shot with the latest development commit?

**Comment by DarthAffe** [comment]
> hovering between 0-1% CPU

Confirmed - sorry for bothering you with this without syncing my branch first ...
