### ISSUE TITLE
G910 Lighting Bleed

### ISSUE THREAD

**Issue by KIN0025** [SpoinkyNL/Artemis#189]
There seems to be (a weird) form of light bleed between keys. With the attached profiles, there is slight light bleed between keys. Light seems to bleed from the numbers row down to the row below it, even though no overlap is visible in the layer visualization.
![number bleed](https://cloud.githubusercontent.com/assets/2134914/20030329/f4ca6bb0-a3b6-11e6-88b1-75a4cfc95496.jpg)

The weirdness seems to come from an interaction with the right control key and the down arrow key. If there is no lighting on the down arrow, the light from the right control does not bleed into the left arrow. If the right control layer is disabled, no bleed occurs.
![arrowsa](https://cloud.githubusercontent.com/assets/2134914/20030330/f68e6d98-a3b6-11e6-84ed-cc86471b901f.jpg)

This cannot be reproduced in LGS.

[Profiles.zip](https://github.com/SpoinkyNL/Artemis/files/573209/Profiles.zip)

**Comment by SpoinkyNL** [comment]
Hey, thanks for the detailed report. I'll try to reproduce it when I get home

**Comment by SpoinkyNL** [comment]
Was able to reproduce and fix this, bit of a nasty side-effect of downsizing the rendered image to fit the G910, it was interpolating the colors, resulting in a few pixels being semi transparent (and thus coloring the nearby keys)

You'll find a fix in the upcoming update :)
