### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by kin0025** [SpoinkyNL/Artemis#190]
- Google Play Music Desktop Player Support
I was wondering if it was possible to integrate GPMD support similar to that of Spotify.
[It has an API](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#integrating-with-gpmdp-from-external-applications) that allows for collection of playback information via web sockets or simply reading a json file.

I understand if you don't have time or inclination to implement it (lots of other things to do), might try to apply my mediocre programming skills and learn C# to attempt it myself.

- Support for reading system temperatures. 
Is it possible to integrate with another application or use a library to read system temperatures and use them as a DataModel?

**Comment by SpoinkyNL** [comment]
Hey, I've added the Google Play Music support. System temps are a bit of a different story, I know AIDA64 has some sort of API but a free alternative would be better.

**Comment by DarthAffe** [comment]
System temps and stuff like that should be readable without 3rd party tools through [WMI](https://msdn.microsoft.com/en-us/library/aa394582%28v=vs.85%29.aspx). But querying this is a bit ... well awkward?

**Comment by SpoinkyNL** [comment]
Latest release has Google Play Music support now :)
