### ISSUE TITLE
LUA examples

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#191]
I've made major steps in LUA support (#121)
A big part of the work went into the docs https://github.com/SpoinkyNL/Artemis/wiki/LUA.

Would be neat if @DarthAffe @Thoth2020 and @JewsOfHazard (and anyone else who can pull and compile development) could play around with it a bit, I'd like some feedback on the docs and I could use a few examples to include.

One thing I'm missing and want to add is mouse position, anything else you guys come up with let me know

**Comment by DarthAffe** [comment]
I'm currently testing a bit and it just failed at saving back my script.

Null reference exception at **LuaWrapper 105** _(LuaScript.Globals.RegisterCoreModules(CoreModules.Preset_SoftSandbox);)_
caused by **LuaWrapper 155** _(ProfileModel.LuaScript = sr.ReadToEnd();)_
Stacktrace shows only _"at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)"_

it didn't crash but it reseted the script back to the default one.

**Comment by SpoinkyNL** [comment]
Hey, do you have Just My Code enabled or disabled? 

When I disable it I do get one exception within Moonsharp (and CUE.NET actually) but without it was fine last time I checked, I'll look into it further when I get home

**Comment by DarthAffe** [comment]
JustMyCode is disabled, but I first tested without debugger got this problem (resetting scripts) and a crash I couldn't reproduce until now. It seems to me like there is some relation to invalid scripts. I have no idea how lua syntax works and the debug output shows lots of errors like (LuaWrapper - ERROR: [Test-LUA]: Error: chunk_11:(15,1-6): 'end' expected near 'local') but I think this shouldn't be a problem except that it won't work.

One more thing: Is there a way to get this debug-output and maybe lua prints without the debugger?

**Comment by SpoinkyNL** [comment]
Ok thanks, I'll take a look :)

All output is sent to Visual Studio's program output, the log files in Documents > Artemis > logs and the debug window in Artemis (found under settings)

Oh, and scripts with invalid syntax indeed shouldn't crash Artemis but simply log their errors

**Comment by SpoinkyNL** [comment]
I can't seem to reproduce this, could you give me the LUA script you're using to break it? :p

**Comment by DarthAffe** [comment]
It happened quite often to me. I tried to make it work (which it does now :p) and commented/uncommented & saved quite a lot. 
I use Notepad++ to edit the file.

The script

```lua
lastUpdate = os.time();

function updateHandler(profile, eventArgs)
    if eventArgs.DeviceType != "keyboard" then
        return;
    end
	
	local currentUpdate = os.time();
	if (currentUpdate - lastUpdate) < 1 then
		return;
	end
	
	lastUpdate = currentUpdate;
		
	local layer = Profile.GetLayerByName("Ambilight");
	layer.Enabled = not layer.Enabled;
end

Events.DeviceUpdating.add(updateHandler);
```

**Comment by SpoinkyNL** [comment]
I've wrapped the loading mechanism in a try-catch to make sure the script is atleast always saved.
I'm not sure where the null-reference is coming from, LuaScript itself is static readonly and initialized on construction, so that's not it

**Comment by DarthAffe** [comment]
Ah, I just remembered something I forgot to mention. If you enable/disable layers (like my code above) the UI won't reflect that changes. This was a bit confusing while testing, since I expected the checkbox to change according to the real state.

**Comment by SpoinkyNL** [comment]
I see what you mean, I've changed how that works so that it'll update after a short while, can't make it real time because WPF isn't great

**Comment by Cr4xy** [comment]
Rain:
```lua
-- Corsair K95 RGB
local KEYBOARD_WIDTH = 25
local KEYBOARD_HEIGHT = 7

local MINIMAL_NEW_RAIN = 1

local keyMap = {}
local globalCounter = 0
function drawHandler(profile, eventArgs)
  if eventArgs.DeviceType != "keyboard" then
    return
  end
  globalCounter = globalCounter + 1
  if globalCounter % 3 == 0 then
    local newRainAmount = math.floor(math.random() * 3) + MINIMAL_NEW_RAIN
    for i = 0, newRainAmount do
      local x = math.floor(math.random() * KEYBOARD_WIDTH)
      table.insert(keyMap, {
        X = x,
        Y = 0,
        ColorBrush = Brushes.GetSolidColorBrush(Brushes.GetRandomColor()),
        Counter = newRainAmount
      })
    end
  end

  for i = #keyMap, 1, -1 do
    local obj = keyMap[i]
    eventArgs.Drawing.DrawRectangle(obj.ColorBrush, obj.X, obj.Y, 1, 1)
    obj.Counter = obj.Counter + 1
    if obj.Counter % 5 == 0 then
      obj.Y = obj.Y + 1
      if obj.Y > KEYBOARD_HEIGHT then
        table.remove(keyMap, i)
      end
    end
  end
end
´´´
