### ISSUE TITLE
G910 light bleed issue

### ISSUE THREAD

**Issue by keyford** [SpoinkyNL/Artemis#193]
hey on my g910 i have red and green keys, but the red keys that are dirictly next to the green ones are orange, i think this might be some weird interpolation issue. i tried takeing a picture, but the diffrence wasnt clear enough

**Comment by SpoinkyNL** [comment]
Hey, this'll be fixed in the next update, assuming it's the same as #189

**Comment by keyford** [comment]
It is, sorry i didnt think to look in the closed issues tab

**Comment by SpoinkyNL** [comment]
Fixed in the latest release!
