### ISSUE TITLE
Copying layers inbetween profiles

### ISSUE THREAD

**Issue by keyford** [SpoinkyNL/Artemis#194]
Would it be possable to allow copying layer or layer folders from on profile to anouther? So i can get the same back round in evey profile(my backround is about 12 layers) or save time not haveing to remake complacated event based layers(my friend set up somthing to change coulor with cpu usage and that uses quite a few layers)

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you any sooner, been stuck on #182 since wednesday or so :C

I think after this release I'll retire duplicating layers in favor of just copying them with Ctrl+C / Ctrl+V. That would mean you can just switch profiles and paste them in a different profile.
