### ISSUE TITLE
Artemis has stoped working

### ISSUE THREAD

**Issue by Baanor** [SpoinkyNL/Artemis#198]
Hi,

Since the 1.5.0 artemis doesn't want to start, everytime the window appear and Windows pop-out an error message saying that artemis has crashed.

I don't know why, i've uninstall Artemis and reinstall the 1.4.0 version and it worked fine. So i've retry the update with update.exe (restarting artemis) and error message again...

I've tried to look into the logs so:

----------------------------------------------------------------------------------------------------------------------
SquirrelSetup.log

> 2016-11-17 00:11:16> Program: Starting Squirrel Updater: --processStart Artemis.exe
> 2016-11-17 00:11:16> Program: Want to launch 'C:\Users\Pr0m\AppData\Local\Artemis\app-1.5.0.1\Artemis.exe'
> 2016-11-17 00:11:16> Program: About to launch: 'C:\Users\Pr0m\AppData\Local\Artemis\app-1.5.0.1\Artemis.exe': 
> 2016-11-17 00:14:03> Program: Starting Squirrel Updater: --processStart Artemis.exe
> 2016-11-17 00:14:03> Program: Want to launch 'C:\Users\Pr0m\AppData\Local\Artemis\app-1.5.0.1\Artemis.exe'
> 2016-11-17 00:14:03> Program: About to launch: 'C:\Users\Pr0m\AppData\Local\Artemis\app-1.5.0.1\Artemis.exe': 

----------------------------------------------------------------------------------------------------------------------
And the log when it try to lunch artemis just after

> 2016-11-17 00:14:04.5329|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Info 
> 2016-11-17 00:14:05.0024|INFO|Artemis.Managers.DeviceManager|Intialized DeviceManager with 9 device providers 
> 2016-11-17 00:14:05.7960|INFO|Artemis.Managers.EffectManager|Intialized EffectManager 
> 2016-11-17 00:14:05.7960|INFO|Artemis.Managers.LoopManager|Intialized LoopManager 
> 2016-11-17 00:14:05.7960|INFO|Artemis.Managers.ProfileManager|Intialized ProfileManager 
> 2016-11-17 00:14:05.7960|INFO|Artemis.Utilities.DataReaders.PipeServer|Opened named pipe 'artemis' 
> 2016-11-17 00:14:05.8125|INFO|Artemis.Managers.MainManager|Intialized MainManager 
> 2016-11-17 00:14:05.8125|INFO|Artemis.Managers.MainManager|Artemis version 1.5.0.1 is ready! 
> 2016-11-17 00:14:05.8125|INFO|Artemis.Utilities.Updater|Update check enabled: True 
> 2016-11-17 00:14:06.7443|INFO|Artemis.Utilities.Updater|Updated from 1.4.0.0 to 1.5.0.1, showing changelog.

-------------------------------------------------------------------------------------------------------------------
I don't know why it happen.

If you have time to look after it, i would be happy with some help finding the reason.

**Comment by Baanor** [comment]
And in my event observer:

> Application : Artemis.exe
> Version du Framework : v4.0.30319
> Description : le processus a été arrêté en raison d'une exception non gérée.
> Informations sur l'exception : System.InvalidOperationException
>    à System.Windows.Threading.Dispatcher.VerifyAccess()
>    à MahApps.Metro.Controls.Dialogs.DialogManager.ShowMessageAsync(MahApps.Metro.Controls.MetroWindow, System.String, System.String, MahApps.Metro.Controls.Dialogs.MessageDialogStyle, MahApps.Metro.Controls.Dialogs.MetroDialogSettings)
>    à Artemis.Services.MetroDialogService+<ShowQuestionMessageBox>d__3.MoveNext()
>    à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    à Artemis.Utilities.Updater+<CheckChangelog>d__2.MoveNext()
>    à System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
>    à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    à System.Threading.ThreadPoolWorkQueue.Dispatch()

> Nom de l’application défaillante Artemis.exe, version : 1.5.0.1, horodatage : 0x582b9d2e
> Nom du module défaillant : KERNELBASE.dll, version : 10.0.14393.321, horodatage : 0x57f4c4f0
> Code d’exception : 0xe0434352
> Décalage d’erreur : 0x0000000000017788
> ID du processus défaillant : 0x428
> Heure de début de l’application défaillante : 0x01d2405f1f3b6042
> Chemin d’accès de l’application défaillante : C:\Users\Pr0m\AppData\Local\Artemis\app-1.5.0.1\Artemis.exe
> Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
> ID de rapport : ffafe16f-047d-443b-a45c-b7a50045677c
> Nom complet du package défaillant : 
> ID de l’application relative au package défaillant : 
>

**Comment by SpoinkyNL** [comment]
Hey, thanks for your report, looks like I made a mistake. Until I can fix this (I'll try to bring out an update when I get back from college) this should fix it for you

1. Head into Documents > Artemis > settings
2. Open up Artemis.Settings.GeneralSettings.json
3. Paste the following into the JSON file:
```json
{
  "LastEffect": "WindowsProfile",
  "LastKeyboard": "Corsair RGB Keyboards",
  "Layout": "Qwerty",
  "EnablePointersUpdate": true,
  "GamestatePort": 62574,
  "Autorun": true,
  "Suspended": false,
  "ShowOnStartup": true,
  "AutoUpdate": true,
  "Theme": "Corsair Dark",
  "ScreenCaptureFPS": 20,
  "LogLevel": "Info",
  "LastRanVersion": {
    "Major": 1,
    "Minor": 5,
    "Build": 0,
    "Revision": 1,
    "MajorRevision": 0,
    "MinorRevision": 1
  }
}
```

Then the program should start properly until I can fix it

**Comment by SpoinkyNL** [comment]
I uploaded a new version where this is fixed, if you uninstall the current and install that one you should be fine :)

**Comment by Baanor** [comment]
Thanks for your works, i've tried the new version with a clean install (no old config) and Artemis start fine now. But the backlight of the keyboard don't work, for my mouse and headset everything fine (they're corsair gear too).

Nothing appear abnormal in the log of the updater, artemis or windows. I use the last version of CUE (2.6.79) for information.

**Comment by SpoinkyNL** [comment]
Hmm that's weird. Does the profile editor show rje correct keyboard image?

**Comment by Baanor** [comment]
Yep, corsair strafe as it should.

**Comment by SpoinkyNL** [comment]
Ok that's odd, I've not changed anything to the Strafe since 1.4 but I'll test it with my own when I can. In the meanwhile could you try removing the Documents > Artemis folder and rebooting, perhaps that'll help.

If not could you set logging to Trace, wait for a few seconds and set it back to Info and then upload the log? 

Thank you!

**Comment by Baanor** [comment]
Ok i will try, and i will test later on another computer to be sure it's not mine.

**Comment by Baanor** [comment]
So i've delete the config folder and restart (i've done it twice to be sure), and still the same.
So i've put the log in trace:

> 2016-11-17 20:21:51.8129|FATAL|Artemis.Utilities.Logging|INFO: Set log level to Trace 
> 2016-11-17 20:21:52.1594|INFO|Artemis.Managers.DeviceManager|Intialized DeviceManager with 9 device providers 
> 2016-11-17 20:21:52.8501|INFO|Artemis.Managers.EffectManager|Intialized EffectManager 
> 2016-11-17 20:21:52.8501|INFO|Artemis.Managers.LoopManager|Intialized LoopManager 
> 2016-11-17 20:21:52.8571|INFO|Artemis.Managers.ProfileManager|Intialized ProfileManager 
> 2016-11-17 20:21:52.8571|INFO|Artemis.Utilities.DataReaders.PipeServer|Opened named pipe 'artemis' 
> 2016-11-17 20:21:52.8731|INFO|Artemis.Managers.MainManager|Intialized MainManager 
> 2016-11-17 20:21:52.8731|INFO|Artemis.Managers.MainManager|Artemis version 1.5.0.2 is ready! 
> 2016-11-17 20:21:52.8731|INFO|Artemis.Utilities.Updater|Update check enabled: True 
> 2016-11-17 20:21:54.3170|DEBUG|Artemis.Managers.MainManager|Enabling program 
> 2016-11-17 20:21:54.3170|DEBUG|Artemis.Managers.LoopManager|Starting LoopManager 
> 2016-11-17 20:21:54.3170|DEBUG|Artemis.Managers.DeviceManager|Getting last keyboard: Corsair RGB Keyboards 
> 2016-11-17 20:21:54.3290|DEBUG|Artemis.Managers.DeviceManager|Trying to enable keyboard: Corsair RGB Keyboards 
> 2016-11-17 20:21:54.9616|DEBUG|Artemis.DeviceProviders.Corsair.CorsairKeyboards|Corsair SDK reported device as: STRAFE RGB 
> 2016-11-17 20:21:54.9666|DEBUG|Artemis.DeviceProviders.Corsair.CorsairHeadsets|Attempted to enable Corsair headset. CanUse: True 
> 2016-11-17 20:21:54.9666|DEBUG|Artemis.DeviceProviders.Logitech.LogitechGeneric|Attempted to enable Logitech generic device. CanUse: False 
> 2016-11-17 20:21:54.9666|DEBUG|Artemis.DeviceProviders.Corsair.CorsairMice|Attempted to enable Corsair mice. CanUse: True 
> 2016-11-17 20:21:54.9666|DEBUG|Artemis.DeviceProviders.Corsair.CorsairMousemats|Attempted to enable Corsair mousemat. CanUse: False 
> 2016-11-17 20:21:55.6823|DEBUG|Artemis.Managers.DeviceManager|Enabled keyboard: Corsair RGB Keyboards 
> 2016-11-17 20:21:55.6998|INFO|Artemis.Utilities.Updater|Update check complete 
> 2016-11-17 20:21:55.9709|DEBUG|Artemis.Managers.EffectManager|Getting last effect: WindowsProfile 
> 2016-11-17 20:21:57.4774|DEBUG|Artemis.Managers.EffectManager|Changed active effect to: WindowsProfile 
> 2016-11-17 20:21:57.5592|TRACE|Artemis.Models.EffectModel|Effect datamodel as JSON: 
> {
>   "Cpu": {
>     "TotalUsage": 0,
>     "Core1Usage": 0,
>     "Core2Usage": 0,
>     "Core3Usage": 0,
>     "Core4Usage": 0,
>     "Core5Usage": 0,
>     "Core6Usage": 0,
>     "Core7Usage": 0,
>     "Core8Usage": 0
>   },
>   "Performance": {
>     "RAMUsage": 0
>   },
>   "Spotify": {
>     "Running": false,
>     "Artist": null,
>     "SongName": null,
>     "SongPercentCompleted": 0,
>     "SpotifyVolume": 0,
>     "Album": null,
>     "Repeat": false,
>     "Shuffle": false,
>     "Playing": false,
>     "SongLength": 0
>   },
>   "GooglePlayMusic": {
>     "playing": false,
>     "song": null,
>     "rating": null,
>     "time": null,
>     "shuffle": null,
>     "repeat": null,
>     "volume": 0
>   },
>   "CurrentTime": {
>     "Hours24": 20,
>     "Hours12": 8,
>     "Minutes": 21,
>     "Seconds": 57
>   },
>   "Keyboard": {
>     "NumLock": true,
>     "CapsLock": false,
>     "ScrollLock": false
>   }
> } 

After that it continue monitoring cpu,ram,etc...

I really think i need to test it on another computer nothing seems to go wrong.

I will update you when i've test it.

**Comment by Baanor** [comment]
I've tried it on another computer, this one is on Windows 7 (Win 10 on my main), and still the same problem no backlight...

I've put the log in trace mode, and i've the exact same output as the one upside.

**Comment by SpoinkyNL** [comment]
Thanks for all your testing, I found some time and I think I fixed it. 
Could you try this version: https://github.com/SpoinkyNL/Artemis/releases/download/1.5.0.3/Setup.exe

**Comment by Baanor** [comment]
Thanks, work like a charm. I will test further during the night to see if i found something else not working.

A big thanks to your reactivity.

**Comment by SpoinkyNL** [comment]
Ok thanks a lot of helping out, I'll close this issue now. Should anything else not work properly feel free to create a new one :)
