### ISSUE TITLE
Setup session won't start!

### ISSUE THREAD

**Issue by fotis016** [SpoinkyNL/Artemis#200]
I'm trying to setup the program, but the setup file force closes (the process disappears after about 5 seconds I open the file). I've tried a few different versions and none of them worked. Help me please!
Edit: The setup is actually finished, it's the program that force closes.

**Comment by SpoinkyNL** [comment]
Hello, could you head into Documents > Artemis > logs and give me the log file if it's there at all

**Comment by fotis016** [comment]
Hello, thanks for the quick reply. Yes, I did find plenty of log files, they all report the same lines. I have provided one of them for you to see what's going on. [http://pastebin.com/J6mk9JLp](url)

**Comment by SpoinkyNL** [comment]
Not much in there sadly.

It might be worth installing [Visual Studio C++ Redistibutable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) be sure to grab the x64 version

And  [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679) as well

Let me know if that helps :)

**Comment by fotis016** [comment]
Tried both of these, unfortunately there were no changes :/

**Comment by SpoinkyNL** [comment]
Oh hm that's tricky, usually when these odd crashes without any output appear that fixes it.

This is a bit more of a pain but could you head into: 
Documents > Artemis > Settings and open up Artemis.Settings.GeneralSettings.json with a text editor

Find "LogLevel": "Info"
And change it to "LogLevel": "Trace"

That will make Artemis do a whole lot more logging which might give me an indication of whats wrong. So if you run the program again you should get a better log, can you post that here for me? 

Cheers

**Comment by fotis016** [comment]
I'm going to dissappoint you as nothing new appears in the fresh logs [http://pastebin.com/FxcYUsY7](url)

**Comment by SpoinkyNL** [comment]
Hmm it still says Info in the top of the log, did you save the file?

**Comment by fotis016** [comment]
Yes, I did save the json file. The new logs now report this: "Set log level to Trace" instead of "Set log level to Info".

**Comment by SpoinkyNL** [comment]
I see, I thought you uploaded the new log but it was the same link, my bad.

What device(s) are you attempting to use Artemis with?

**Comment by fotis016** [comment]
I'm using the Corsair Strafe RGB. Tried using Artemis with both CUE opened and closed.

**Comment by SpoinkyNL** [comment]
Ok, last think I can try today, after this I need to go but should it not help I'll get back to you ASAP.

It could be the auto-update failing, can you reopen the settings file and set AutoUpdate to false?

**Comment by fotis016** [comment]
No changes :(

**Comment by SpoinkyNL** [comment]
Ok one last thing, perhaps you could check your Windows Event Log, there might be something related to Artemis there, especially the Application Logs

**Comment by fotis016** [comment]
Hey, yes I was able to find 2 errors!
Hope the text is translated to English [https://mega.nz/#!v0MUjB6b!bGIddl-tiu9RXIY8t8W1Uum48vrJSutmFBFBd9WjWjA](url)

**Comment by SpoinkyNL** [comment]
Ah great, that should help a lot. I'll take a look at them tonight :)

**Comment by fotis016** [comment]
Thanks for your commitment to helping me :)

**Comment by SpoinkyNL** [comment]
I had a good look at the errors and this is the key point:

```
Εφαρμογή: Artemis.exe
Έκδοση Framework: v4.0.30319
Περιγραφή: Η διεργασία τερματίστηκε λόγω μιας εξαίρεσης που δεν αντιμετωπίστηκε.
Πληροφορίες εξαίρεσης: System.AccessViolationException
   σε System.Net.UnsafeNclNativeMethods.SetFileCompletionNotificationModes(System.Runtime.InteropServices.CriticalHandle, FileCompletionNotificationModes)
   σε System.Net.HttpListener.CreateRequestQueueHandle()
   σε System.Net.HttpListener.Start()
   σε Artemis.Utilities.GameState.GameStateWebServer.Start()
```

For some reason Artemis is unable to create it's tiny HttpServer (webserver) which is used as a way of communication for games such as CS:GO and DoTA2.

This shouldn't be crashing Artemis though, so I've made sure that that won't happen in the future.

[This version](https://www.dropbox.com/s/2a89086hq6a2g46/artemis-beta-1504.zip?dl=0) will work for you but unless you can figure out what's causing the HttpServer to fail to start, CS:GO and DoTA2 won't work. 

Access violations usually indicates a virus scanner blocking it, so perhaps you could try disabling it for a moment to see if it helps, and if so you might want to add Artemis as an exception. With Artemis working you could also try changing the Game state port to something else in the settings menu. Also, I Googled a bit and it seems the 'Lavasoft Web Companion' can also cause this issue, do you have that installed?

**Comment by fotis016** [comment]
I'm going to drive you crazy as I still didn't manage to open the program dispite disabling windows defender and adding the program as an exception. The new error log seems to be different though [https://mega.nz/#!L4dUGYAZ!k5o6DSN8AbhE5ZyBxz3rhJ-2JtK4f84_rFJjEL585Gk](url)

**Comment by SpoinkyNL** [comment]
No problem, I have a near infinite supply of patience :p

This seems to be a different problem, looks like a permission issue with the extracted files from the ZIP I provided, try this setup instead: https://www.dropbox.com/s/ycidagldibxg0wj/artemis-beta-1504-setup.exe?dl=0

**Comment by fotis016** [comment]
Exact same error. Should I try and boot into safe mode and see what happens?

**Comment by SpoinkyNL** [comment]
I'm at a bid of a loss tbh.. Artemis runs itself as admin but could you try disabling user account control and excplicitly run it as administrator?

Might also be worth trying a new user profile just to see it makes a difference. Every Windows installation becomes a bit different over time, so this is a hard issue to track down. I personally haven't seen this happen before, so I'm just trying random things

Safe mode might also do the trick, worth a shot

**Comment by fotis016** [comment]
Formatted my pc and now the program runs perfectly. Thanks for your help anyways!

**Comment by SpoinkyNL** [comment]
Well that's one way to fix it haha, Windows installs do go a bit iffy over time. Enjoy the program :)
