### ISSUE TITLE
[Request] Add Sombra value

### ISSUE THREAD

**Issue by Baanor** [SpoinkyNL/Artemis#201]
Hi,

I was looking how to add Sombra of Overwatch has a value, but... yeah, i don't understand Github enough to make a pull request -.-" (i understand that will not put it directly in the program).

Could you do it ?  I'm trying to do a simple profile with her, but i don't understand how you implement it in your code and, has i've seen, the profiles in "my document" are categorized for keyboard. So i imagine it's not done by lua script ?

Thanks in advance ;)

**Comment by SpoinkyNL** [comment]
Hello,

You can use LUA to create your own custom stuff but reading the Overwatch character data is a bit too advanced for just LUA and therefore done by Artemis in C# code. [Right here if you're curious](https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/Modules/Games/Overwatch/OverwatchModel.cs#L207). 

When they added Ana she didn't actually have her own color in the native Razer support so I couldn't read her, but now both Ana and Sombra have a color and I've added them to Artemis :) You'll find it in the next update

**Comment by Baanor** [comment]
Ok so if i understand well, you transform what commands should receive the razer keyboard into values ?
But i think we go off subject ^^ i will continue to look myself in your code and try do understand with my newbie level.
And thanks for adding her.

**Comment by SpoinkyNL** [comment]
Yup that's it and you're welcome :)
