### ISSUE TITLE
[Request] Masterkeys Pro S (Tenkeyless) Support

### ISSUE THREAD

**Issue by AidDun** [SpoinkyNL/Artemis#202]
In Artemis, there is support for the Cooler Master Masterkeys Pro L, the full sized variant of the product line, but there is no support for the Masterkeys Pro S, the tenkeyless version of the keyboard. 

Since both keyboards use the same SDK and Artemis already uses the SDK for the Pro L, it should be possible to easily add support for the keyboard by modifying the code for the Pro L. 

This wouldn't take much time and would be awesome for the many people including myself who use the Pro S! 

[Keyboard Link](http://www.coolermaster.com/peripheral/keyboards/masterkeys-pro-s/)

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you earlier.

Did you try running Artemis and selecting the Pro L to see if it works at all? The SDK doesn't really differentiate between the too as far as I know

**Comment by laurenwb** [comment]
Tried it out on my Pro S, and it seems to do nothing. I opened Overwatch and the program recognized that it was open, but the keyboard itself stayed on what I had it on originally. I also tried a Windows profile, still nothing. I also shut off the Cooler Master background utility. I'm on the most recent firmware version.

**Comment by SpoinkyNL** [comment]
Hey, I've got a test version here that should support the Pro S, could either of you download it and select the Pro S under settings, create a new profile and see if the layers position correctly? Thanks!

[Test version download](https://github.com/SpoinkyNL/Artemis/files/625371/pro-s-test.zip)
PS: Extract the whole ZIP and run Artemis.exe in the Debug folder

**Comment by AidDun** [comment]
Hi, the test version isn't opening for me. It shows up on task manager for a brief second then disappears. It also looks like a new window is going to open during that time as it de-focuses on the previous window.

**Comment by laurenwb** [comment]
Just tried it, same issue here. Also ran as administrator.

**Comment by SpoinkyNL** [comment]
Hmm ok dev builds do act funny sometimes, I'll get a better build for you guys tomorrow (midnight here and work in the morning, sorry!)

**Comment by SpoinkyNL** [comment]
I've got a beta setup for the next version [here](https://www.dropbox.com/s/xm78wpm2qg89fpn/artemis-beta-1504-setup.exe?dl=0) let me know if that works :)

**Comment by laurenwb** [comment]
Just tried it, and it works! The only problem I can see right now is that there seems to be some kind of alignment issues with the keys. The right column of keys (pgup pgdown right arrow) won't light up no matter what, and the rest of the keys don't quite seem to match up with the profile. 
![Here's what it looks like](https://cloud.githubusercontent.com/assets/24286228/20861777/8f0127ae-b966-11e6-9cc0-530cefb4d669.jpg)

**Comment by SpoinkyNL** [comment]
Progress!

This one should be the correct width: https://www.dropbox.com/s/7tvx5au66b1lgld/artemis-beta-15041-setup.exe?dl=0

Make sure you remove the old profile and create a new one :)

**Comment by SpoinkyNL** [comment]
Any luck with that version? If so I'll make default profiles for it and push out an update

**Comment by laurenwb** [comment]
Yes, it works. Sorry, meant to respond earlier. Thanks for the help!

**Comment by AidDun** [comment]
Yeah, the version also worked for me. Thank you so much!

**Comment by yokuyuki** [comment]
Just tried this on my Masterkeys S as well and it works perfectly. Not sure if it's related, but I did notice that if I select no color for a keyboard light, it crashes. I was just trying to make a mask for a layer, but I ended just making the color black.

**Comment by SpoinkyNL** [comment]
Thanks for the feedback folks, I'll create default profiles and push an update this week

@yokuyuki looks like that's a bug, you shouldn't be able to set no color at all, a transparent or black brush is indeed the intended way to go instead.

**Comment by SpoinkyNL** [comment]
This is included in the latest release, I've also added default profiles. Enjoy!

Should there be any issues with it, please create a new thread
