### ISSUE TITLE
Corsair Strafe does not come back on after waking up

### ISSUE THREAD

**Issue by ZanyIllusions** [SpoinkyNL/Artemis#204]
I have a Strafe and when I wake my computer up, the LED's do not come back on until I open Artemis and click on the effect. Is there a setting I'm not seeing or anything anyone can point out to help with this issue? Thanks in advance.

**Comment by SpoinkyNL** [comment]
Hey, I can confirm that it doesn't recover from sleep mode very well currently. It's something I'll look in to, thanks for the report!

**Comment by ZanyIllusions** [comment]
Awesome thank you! I also heard something about the next update having Ana and Sombra?

**Comment by SpoinkyNL** [comment]
Hey, should be fixed in the latest version. I've also added Ana and Sombra to Overwatch :)
