### ISSUE TITLE
Audio Visualizer Changing Colours won't save

### ISSUE THREAD

**Issue by Bluethefurry** [SpoinkyNL/Artemis#205]
Hey i'm back!

Here's my issue, everytime i have the audio visualizer running, when i change its colour it won't apply until i completely restart Artemis or change profiles!
http://puu.sh/syIHy/bf712b91a4.jpg

**Comment by SpoinkyNL** [comment]
Hey, thanks for the Report. Ill look into it for the next update :)

Op 29 nov. 2016 10:12 p.m. schreef "Blue" <notifications@github.com>:

**Comment by Arttumiro** [comment]
You can just change the volume sensitivity and it will change. I have noticed the same bug.

**Comment by SpoinkyNL** [comment]
Fixed in 1.6.0.0 :)
