### ISSUE TITLE
BSOD when 'Enabling Logitech G910 RGB'

### ISSUE THREAD

**Issue by ProjectSynchro** [SpoinkyNL/Artemis#209]
Hi,

I had Artemis open for the first time and I chose to enable the keyboard. This was all well until the computer BSOD'd some time later.

After that I attempted to open Artemis, and each time it 'enables the keyboard' the computer BSODs.

Any help on this issue would be much appreciated

ALSO Using Aurora, which is another third party RGB control application works as intended without the BSOD.

**Comment by SpoinkyNL** [comment]
Hello,

That's really odd, .NET applications can't cause a BSOD, but the SDK's we use might. I read that similary software works alright but could you try shutting down any RGB software, uninstalling Logitech Gaming Software and reinstalling it?

It might be worth (re)installing [Visual Studio C++ Redistibutable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) be sure to grab the x64 version  
And  [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679) as well

**Comment by WalrusCode** [comment]
I will attempt this and add the results to the end of this answer at that point.

I have a suspicion that Logitech's driver/ SDK doesn't like something.I did forget to mention earlier that the BSOD code in question was WHEA_UNCORRECTABLE_ERROR, and at the time of testing Artemis I had disabled Aurora.

**Comment by WalrusCode** [comment]
Well apparently I lied.

Whist editing some events within the CSGO game options, the WHEA UNCORRECTABLE ERROR appeared again.

Any information I can provide as to helping you find the issue is at the ready just say the word

Cheers

**Comment by SpoinkyNL** [comment]
Ah that's too bad, always nice if stuff fixes itself :p

That BSOD indicates a physical hardware failure according to MSDN but I can't imagine that being the case since it only occurs with Artemis. Perhaps we can get some more info out of it using [BlueScreenView](http://www.nirsoft.net/utils/bluescreenview-x64.zip)

When you run the .exe you can select the dump containing the WHEA_UNCORRECTABLE_ERROR and press Ctrl+S. That'll give you a .txt, if you can post it's contents here that would hopefully get is a bit further :)

**Comment by WalrusCode** [comment]
Looking over the details the 'Bug check string' makes no mention of the WHEA_UNCORRECTABLE_ERROR, however those times were the times of the BSODs.

I also saw that HAL.dll was involved, and to my knowledge that DLL refers to the Hardware Abstraction Layer, which is odd but still points to my suspicions that the Logitech driver is being funky.
Here is a gist with all of the txt files that you requested: 

[https://gist.github.com/WalrusCode/6ee3a2d5dd2bba0af4ef7526ef8643ec](url)

Cheers

**Comment by SpoinkyNL** [comment]
I think to take a better look you'd need to upload the dump files, those apparently contain more info. It puzzles me how it worked fine for a while though :c. 

One thing that comes to mind is that you mentioned it breaking after playing around with CS:GO. Could you head into the Logitech Gaming Software and disable the built in supper for games? They might be conflicting with Artemis in some strange way

**Comment by WalrusCode** [comment]
So after reinstalling LGS again, and disabling any wrappers or whatever they are called, Artemis opened.

This time after enabling the bubbles effect and leaving it running for a bit, The wonderful BSOD showed up again with the exact same error code I wasn't able to test CSGO without an immidiate BSOD when the keyboard initializes. 

I uploaded the minidumps to a folder on google drive and the link is below. I honestly am lost as to what is causing this 

[(This includes the latest BSOD with the filename 120516-23281-01.dmp)
](https://drive.google.com/drive/folders/0B5O817iHUl4ARElOUmRqWWVmMDQ?usp=sharing)

**Comment by SpoinkyNL** [comment]
Thanks for the dumps, I had hoped to get some info out of them but Windgb isn't exactly at the pinnacle of debugging software :\

Maybe you could give version [1.3.3.0](https://github.com/SpoinkyNL/Artemis/releases/tag/1.3.3.0) a shot, it uses the previous version of the Logitech driver. 

PS: If you want to disable auto-update, set ```"AutoUpdate": false ``` in ```Documents\Artemis\settings\Artemis.Settings.GeneralSettings.json```. 

I'll also send an email to Logitech's dev tech support linking to this, perhaps they can shed some light on the issue
