### ISSUE TITLE
Game Request and CPU Maxing Out when i use aretmis

### ISSUE THREAD

**Issue by Aelacit** [SpoinkyNL/Artemis#212]
Would love to see a graphical interface for when i play heroes something like how much of an objective each team posses basic moba keys or those tailored to your ingame hotkeys how many kills and assists each team has yea also any idea why my cpu maxes out when i use aretmis openly

im running an overclocked AMD A10-7700K Radeon R7, 10 Compute Core 4C+6G
16.0GB Ram Corsiar Vengence Pro
using a Logitech G910 Orion Spectrum Keyboard and a Logitech G600 Mouse

**Comment by SpoinkyNL** [comment]
Hey, I'll look into Heroes of The Storm support, it's tricky because Blizzard doesn't offer a live API. 

The CPU usage isn't normal though, does it happen all the time or only with the UI open or playing a certain game?

**Comment by Aelacit** [comment]
It's when the app is open running bubbles effect and I tried running as
admin and everything I tried it still overloaded my cpu

**Comment by SpoinkyNL** [comment]
Could you head into settings and set the logging level to debug. Then head
into Documents > Artemis > logs and drag the newest log file into the
comment box on GitHub?

Op 7 dec. 2016 09:18 schreef "Aelacit" <notifications@github.com>:

**Comment by Aelacit** [comment]
[2016-12-07.txt](https://github.com/SpoinkyNL/Artemis/files/636100/2016-12-07.txt)

**Comment by SpoinkyNL** [comment]
Tried using that effect and didn't get the high CPU usage myself. If you set the active keyboard to none, does the usage go down?

**Comment by Aelacit** [comment]
It seems to be very picky when it wants to work im not sure but I think
it's after I've been customizing the keyboard over and over is when I get
really high cpu usage

**Comment by SpoinkyNL** [comment]
Ah I see, are you using audio visualization layers?

**Comment by Aelacit** [comment]
I was

**Comment by SpoinkyNL** [comment]
Ok that's almost certainly the cause, I was vaguely aware of an issue with CPU usage on audio layers but now I've fixed it for good. I'll let you know when the update containing the fix is ready

**Comment by Aelacit** [comment]
Thanks

**Comment by SpoinkyNL** [comment]
Hey, please let me know if the latest release resolves the issue for you :)

**Comment by Aelacit** [comment]
Awesome if the patch is out I'll head over and dl it tonite thanks

**Comment by SpoinkyNL** [comment]
Any luck with this?

**Comment by Zegura** [comment]
Not sure if this is any help but previously Artemis was using 5 - 10% CPU but since one of the last updates, it has dramatically decreased (less than 1%)

**Comment by Aelacit** [comment]
I haven't had problems yet
