### ISSUE TITLE
Masterkeys L Support

### ISSUE THREAD

**Issue by yeungmoney** [SpoinkyNL/Artemis#213]
Hi, just trying the Artemis software for the first time. Been playing around with the settings, every seems to be fine so far, but in the default effects, I don't see that the Spotify song completion is working? What triggers this to actually work? And I tried CurrentTime, but the values don't seem to make sense as its showing 4 keys when its 8pm. Just wondering maybe I understand it incorrectly

**Comment by SpoinkyNL** [comment]
Hello, I've added some documentation on how the dynamic properties work: https://github.com/SpoinkyNL/Artemis/wiki/Dynamic-properties

Let me know if this clears it up a little

**Comment by yeungmoney** [comment]
Well, I have the Spotify desktop app, and I just don't think the software is detecting it, or maybe it hasn't been implemented with the keyboard yet, because there it shows no progress when its in the middle of a song. Might work with a keyboard you're testing

**Comment by SpoinkyNL** [comment]
Generally every keyboard uses exactly the same program functionality as all the others, up until the point of actually controlling the LEDs, so it shouldn't matter which keyboard you use ^^.

Can you confirm that the SpotifyWebHelper.exe process is running on your PC? It's what Spotify uses to allow other programs to read/control the player.

**Comment by yeungmoney** [comment]
Yeah, I can confirm that its running, although I have edited the registry that disables ads from popping up.. so maybe that would affect it? 

Unrelated, my auto-start up doesn't work anymore! All options are ticked on (auto-startup, show on start up). It was working I believe the first day I installed Artemis.

**Comment by yeungmoney** [comment]
Yeah! There's a shortcut to Artemis.. so im not sure why its behaving like so

**Comment by yeungmoney** [comment]
Update: Tried deleting Artemis and reinstalling the setup... now it gives me an error when I select the keyboard :/

> An unexpected error occurred in Artemis.

An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
____________________________________________________
System.BadImageFormatException

Message:
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Stack Trace:
   at Artemis.DeviceProviders.CoolerMaster.Utilities.CmSdk.SetControlDevice(DEVICE_INDEX devIndex)
   at Artemis.DeviceProviders.CoolerMaster.MasterkeysProL.CanEnable()
   at Artemis.DeviceProviders.KeyboardProvider.<>c__DisplayClass31_0.<CanEnableAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Artemis.Managers.DeviceManager.<EnableKeyboard>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void SetControlDevice(Artemis.DeviceProviders.CoolerMaster.Utilities.DEVICE_INDEX)

Source:
Artemis

HResult:
-2147024885

**Comment by SpoinkyNL** [comment]
Could you try making sure you're on 1.6.0.1 and then disable auto-run, click save settings, enable auto-update again and once more click save.

That'll recreate the shortcut and hopefully fix that issue. As for Spotify I'm not sure what to do, you could try reinstalling Spotify

**Comment by yeungmoney** [comment]
I don't think the Spotify is a big deal for me, but I did as you said about the startup, and its still not working :/

**Comment by yeungmoney** [comment]
Figured it out. I had the shortcut for some reason "Run as Administrator" and that would cause it to not start up. As for spotify, I think I can live without that feature. Some day I'll update Spotify and let you know. 

I have another issue (last one for now), and its about Rocket League. I am always stuck with the Boost 0% animation in the menu and in game, even when I have more than 0% boost. Is this a known issue?

**Comment by SpoinkyNL** [comment]
Hey, I've fixed the Rocket League issue :)
