### ISSUE TITLE
Logitech G810 Can't change logo and media button buttons

### ISSUE THREAD

**Issue by TurntWaga** [SpoinkyNL/Artemis#215]
By the default, they are set to green and I can't seem to find any way to change them. I tried making another background color but it doesn't reach them other than the media buttons but those don't change colors either. I've seen pictures that they reach on cosiar keyboards which where I got the idea to stretch the background. As shown the lock indicators, game mode, RGB, and mute button also can't be changed. Would this be fixed with a later update or is LGS interfering?

EDIT: In LGS, Change Key Press Color or change to a different effect mode

![](http://image.prntscr.com/image/38df74be5b9c4d67a1340d08715a9180.png)

**Comment by SpoinkyNL** [comment]
Hi, I don't believe LGS let's us color those. Their colors can be changed in regular LGS?

**Comment by TurntWaga** [comment]
~~Yes, they can be changed through LGS, but as soon I close out of LGS it doesn't save them and it goes back to being green.~~ 
I found out the problem. On LGS, the effect mode was on keypress and the background color was green making them green. After changing it to Fixed Color mode, I'm now able to change their colors.

**Comment by manskou** [comment]
Hi, I also have the G810 and I can confirm that the logo and media keys are changeable. Aurora has support for the logo, so at least that can be changed for sure. I can also help you in testing with my G810 ;)

**Comment by manskou** [comment]
Found this today...
![image](https://cloud.githubusercontent.com/assets/24620427/25779261/9be38a0e-331c-11e7-8f52-4ec4b1623351.png)
[Source](https://gaming.logitech.com/en-us/developers)

**Comment by SpoinkyNL** [comment]
I cannot for the life of me remember if I added this or not.

If you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )
