### ISSUE TITLE
Game Request: League of Legends (LightFx)

### ISSUE THREAD

**Issue by MikeUNtested** [SpoinkyNL/Artemis#218]
Hello I read the FAQ and you were already excluding LoL in Game Requests but there is a way to get light from Lol because it have's a LightFx integration. You can't Read Information direct out of  the Game but through LightFx.

A Few more Games uses LightFx like "Guild Wars 2" and "Dying Light".
I searched up, there are already working wrappers like [lightfx-extender](https://github.com/Archomeda/lightfx-extender), but all in one programm would be much better.

**Comment by SpoinkyNL** [comment]
Hey, games supporting LightFX is something I'd like to support as well, seems quite a few games use it. I'll see what I can do

**Comment by MikeUNtested** [comment]
Just read old Issues and there were already a LightFx request, even with exact the same link.
Sorry for that. ^^
