### ISSUE TITLE
Crash on trying to select any keyboard

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#221]
Im using the Logitech G910 and its crashing when i try to select any of the keyboards.

**Comment by SpoinkyNL** [comment]
Hey, I've pushed a new update that fixes this, I made a mistake compiling the final update.

[This version](https://github.com/SpoinkyNL/Artemis/releases/download/1.6.0.1/Setup.exe) should work just fine for you, sorry for the inconvenience!
