### ISSUE TITLE
[Latest Update] Software instantly crashes

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#222]
So i think Artemis updated itself for me (i had the option enabled). I started my PC today, and Artemis asked for Admin, i confirmed as usual, but it never really did anything after that. I checked in my Task Tray, and Artemis didn't run. I checked with Process Hacker 2, and it seems to just kill itself right after having started. I tried uninstalling Artemis and reinstalling it, but that didn't work either, same problem, start program, and it instantly just kills itself.

Here the latest log from the Artemis logs folder:
http://pastebin.com/D3FRpDSA

And here a log from the Windows Event Viewer (sorry, it is in German, but since you are from the Netherlands you should understand most of it :P ):
http://pastebin.com/vUe9ENWq
http://pastebin.com/yGCxBgBM
http://pastebin.com/JFdUu1sQ

If you need any more logs, just tell me :)

**Comment by SpoinkyNL** [comment]
Hey thanks for the logs, turns out I accidentally compiled the new update as 32-bits, oops..

[This version](https://github.com/SpoinkyNL/Artemis/releases/download/1.6.0.1/Setup.exe) should work just fine for you, sorry for the inconvenience!

**Comment by LokeYourLord** [comment]
Ah, thank you Master, i appreciate your work Sir'e :D. Issue closed.

**Comment by LokeYourLord** [comment]
Not exactly, there is a problem now: You remember the issue i told you about the one line from ENTER upwards on the right of the keyboard, where it didn't light up at all and then it did light up all the time (99% of the time)? Well, now that has "spread" and lights up the ENTIRE NUMPAD 98% of the time, looks like this:
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/21182111/b6bcb4e0-c201-11e6-8185-949de33951c6.PNG)

Sorry to bother :/

**Comment by LokeYourLord** [comment]
Here is a video which demonstrates this issue for you (it might still be doing some "optimizations", so sorry for low quality, it is 1440p after YouTube is done doing its hours of work of uploading a video that already is at the right codec :/ ):

https://youtu.be/YojepR_xsYU

**Comment by SpoinkyNL** [comment]
I see what you mean thanks for the video. I still feel like the audio visualization could use some more polishing overall. 

It uses the fast fourier transform (FFT) algorithm to visualizes the audio but I think I've not implemented it very well. I'll look around for some examples of others and try to improve it. Can't say when though. I'll make a separate issue for it later today describing what I want to do
