### ISSUE TITLE
Press key Artemis crash (g910 orion spark)

### ISSUE THREAD

**Issue by Armenel** [SpoinkyNL/Artemis#225]
![artemis effect](https://cloud.githubusercontent.com/assets/24577677/21211694/e794c326-c285-11e6-8549-316edcda3a93.png)
Good evening, good morning

When I press the key continuously (Example w to go ahead (csgo), The crash software directly  (
Here is the error code)

```
![artemis effect](https://cloud.githubusercontent.com/assets/24577677/21206798/86c7e1c0-c264-11e6-968b-1bde06219edd.png)
System.InvalidOperationException

Message:
`The collection has been modified; The enumeration operation may not run. 

Stack Trace:
   à System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   à System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   à Artemis.Profiles.Layers.Types.KeyPress.KeyPressType.Update(LayerModel layerModel, IDataModel dataModel, Boolean isPreview)
   à Artemis.Profiles.Layers.Models.LayerModel.Update(IDataModel dataModel, Boolean preview, Boolean updateAnimations)
   à Artemis.Profiles.ProfileModel.DrawLayers(Graphics g, IEnumerable`1 renderLayers, IDataModel dataModel, Rect rect, Boolean preview, Boolean updateAnimations, String updateType)
   à Artemis.Models.EffectModel.Render(RenderFrame frame, Boolean keyboardOnly)
   à Artemis.Managers.LoopManager.Render()
   à Artemis.Managers.LoopManager.LoopTimerOnElapsed(Object sender, ElapsedEventArgs elapsedEventArgs)

TargetSite:
Void ThrowInvalidOperationException(System.ExceptionResource)

Source:
mscorlib

HResult:
-2146233079`
```
Here is what I put on my keyboard 

sorry i'm french my english is very very bad :p , thanks :) Good job for software <3

**Comment by yokuyuki** [comment]
I got the same except I wasn't typing a key continuously.

**Comment by Armenel** [comment]
It's a shame because I like the keyboard press (effect) ^^'  Have you solved the problem?

**Comment by SpoinkyNL** [comment]
Thanks for the log, in 1.6 I made error catching a lot stricter and this seems to be an error that was there all along but didn't trigger an error popup in earlier versions.

I'll get an update out fixing this today or tomorrow depending on how easily I can fix #224

**Comment by Armenel** [comment]
hi :) Ok Thank you for answering Good luck and thanks again <3

**Comment by SpoinkyNL** [comment]
Hey, I've pushed an update that resolves this. If you restart Artemis it'll auto-update, restart again to launch the new version.

Should you still have any issues, don't hesitate to open a new thread :)
