### ISSUE TITLE
Logitech G910 Orion Spectrum

### ISSUE THREAD

**Issue by NaCl-Lily** [SpoinkyNL/Artemis#226]
I have the G910 Spectrum, and while Artemis picks up the keyboard as compatible, none of the settings apply. I've tried deactivating the default software and rebooting Artemis, but it crashes when I disable then enable Artemis. Am I just doing this wrong?

**Comment by SpoinkyNL** [comment]
Hey, is Artemis coloring your keyboard at all or does it just black out?

**Comment by piwoszjr** [comment]
Hi, I have the same problem. My logitech software is switched off, and keyboard is blue from the  beginning. Sadly, none of the effects i switch on work :(

**Comment by SpoinkyNL** [comment]
@piwoszjr LGS needs to be running when you start Artemis.
Also make sure that in LGS under settings you have "Allow games to interact with lighting" enabled

**Comment by piwoszjr** [comment]
Thanks! It all works now :)

**Comment by NaCl-Lily** [comment]
@SpoinkyNL 
It uses the default wave pattern. I made sure to set LGS to 'Allow games'''" and the Bubbles effect worked. However, when I tried to disable the effect so I could activate 'Type Waves,' it crashed. It crashed on launch a few times, but now everything works? I'm not sure what happened, and I unfortunately lack the error reports. But thanks for your help.

**Comment by SpoinkyNL** [comment]
Hey, I'm curious what happened, could you upload the logs found in Documents > Artemis > logs?

Cheers

**Comment by NaCl-Lily** [comment]
[2016-12-15.0.txt](https://github.com/SpoinkyNL/Artemis/files/655930/2016-12-15.0.txt)

**Comment by NaCl-Lily** [comment]
Is that what you need?

**Comment by SpoinkyNL** [comment]
Yes, thank you

**Comment by Kimchibokkeumbap** [comment]
Hi, sorry for the late response, but yes, my keyboard's RGB works just fine. I have it set to 'ripple' and the effect works perfectly, along with any color changes I make.

**Comment by SpoinkyNL** [comment]
Fixed in 1.7, thanks again
