### ISSUE TITLE
Logitech G600 Mouse

### ISSUE THREAD

**Issue by Kimchibokkeumbap** [SpoinkyNL/Artemis#227]
Hi there,

For some reason running Artemis disables the LED effects on my Logitech G600 mouse. Sometimes the LEDs are blacked out altogether, other times they are stuck on one color.

I am currently using the Artemis software in conjunction with a G910 Orion Spectrum keyboard and the latest version of Logitech Gaming Software.

If this issue has been mentioned before, I apologize.

**Comment by Arttumiro** [comment]
The generic device lights are a bit bugged in this version. you have to change it to another lightning type, apply and then make it a generic device again. That's what works for me.

**Comment by SpoinkyNL** [comment]
Hey, closing this in favor of #224 since it's the same issue :)
