### ISSUE TITLE
Audio visualization layer improvements

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#228]
Current version of the layer uses NAudio in combination with an copy-paste fast Fourier transform to come up with the audio visualization.

I think I'll swap to [CSCore](https://github.com/filoe/cscore) instead since it has less features we're not using anyway, and built-in FFT. 
That'll hopefully mean this won't happen: https://youtu.be/YojepR_xsYU (as reported by [LokeYourLord](https://github.com/LokeYourLord) in #222 )

**Besides that I want the following:**
- [x] Easing
- [x] Auto-sensitivity
- [x] Audio device selection (#175)
- [x] Microphone support (kinda goes hand in hand with device selection I'd say)
- [x] Default device change detection (#278)

**Comment by LokeYourLord** [comment]
I mean, you had it almost perfect just some updates back, if you remember, the only bug was that the right line of buttons didn't light up at all, and then the next update it was constantly lit. Then the next update (current), the entire numpad (and a little more) lights up. If you check 3-4 versions back and see how you had it then, maybe you figure it out :) Good luck and thanks for the awesome support and software (Get PayPal m8).

**Comment by SpoinkyNL** [comment]
Hey, I'm releasing an update today and when that's done I'm going to look
into this one

Op 31 dec. 2016 1:34 p.m. schreef "Mrwebente" <notifications@github.com>:

**Comment by SpoinkyNL** [comment]
Soon™

https://www.youtube.com/watch?v=8R_Onx3bLIU

**Comment by SpoinkyNL** [comment]
This is included in [1.8.0.0](https://github.com/SpoinkyNL/Artemis/releases/tag/1.8.0.0).
