### ISSUE TITLE
Mouse lights blinking

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#229]
Sometimes when i have a Display if.. (for me scroll lock) on when i try to turn off the mouse lights it tries to turn off the lights but cant, so it just blinks the lights continuously. Here's a video of the bug (sorry for potato quality but it might help)

Edit: I mean that if i try to turn off my mouse lights with a keybind they break and start blinking even thought it should just turn off

https://www.youtube.com/watch?v=ribkZxsdFSk

**Comment by SpoinkyNL** [comment]
Hey, I just happened to push an update. Could you restart Artemis twice (once to trigger the auto-update, and once to start the new version) and see if it's gone with that version?

If not, I've added a display to the debug window. If you open up the debug window does the flickering also occur in the display underneath Generic?

This is the window I mean:
![image](https://cloud.githubusercontent.com/assets/8858506/21234439/ef0edf3e-c2f2-11e6-933c-7761509d175f.png)

**Comment by Arttumiro** [comment]
It works now. ill make a new issue if it continues. Thanks for the help.
