### ISSUE TITLE
"display if..." variables still seem a bit broken on generic devices

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#232]
Sometimes turning them off takes like 2 seconds. Also they get stuck sometimes and i have to restart Artemis.

**Comment by SpoinkyNL** [comment]
This is probably related to the other issue you posted. I don't own a Logitech device other than the G910 but I'll try to get my hands on one from a friend. The Logitech implementation is a bit iffy, and I've not been able to test it myself. Can you supply the profile that's giving these issues?
