### ISSUE TITLE
G900 Chaos Spectrum Generic Support

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#234]
So i know that the mouse "seems" to be supported in some way under the Generic Logitech devices, however the RGB leds barely ever light up, even without using any kind of Audio Visualization Profile (just standard lighting, one color). For them to light up, i need to switch from Generic Logitech devices to Mouse, save, exit, edit profile again, set it to Mousepad, save, exit again, edit profile once more and set it back to Generic Logitech devices, then the Mouse lights up UNTIL you either reboot the PC, kill/exit Artemis and boot it up again OR play any kind of game that is supported by either Artemis or LGS and that takes control of the Keyboard and Mouse RGB lighting (Battlefield 1 for example). 

The mouse is lit when the game/software (other than Artemis) takes complete control over the RGB lighting (again, Battlefield 1, not supported by Artemis but takes control over both G910 Orion Spark and G900 Chaos Spectrum). The second you exit the game/software and Artemis returns to the normal profile, the Mouse is once again not lit until you repeat the process of switching between devices multiple times. I do not know if the G900 is supported, but it would be nice if so, because Artemis takes full control over the Mouse as well, the Mouse is 95% of the time just unlit/black for me because LGS cannot control it due to Artemis taking full control of both it and my Keyboard.

Thanks for reading this stupidity, i tried keeping it as clean as possible :)

**Comment by joeknock90** [comment]
I was just coming to post about my Corsair Mouse. 

I'll be willing to help in anyway (although my experience is pretty lacking) to get some mouse support in this program as well. Feels like a waste of pretty lights!

**Comment by SpoinkyNL** [comment]
@LokeYourLord is this with 1.6.1.0? all the issues you described I fixed in that
@joeknock90 my Corsair Mouse never had these issues, what's going wrong for you?

**Comment by LokeYourLord** [comment]
Yes it is with 1.6.1.0, my mouse is barely ever lit unless i either quit/exit Artemis or fiddle with it for quite a while, only for it to be unlit again once i play a game (so it switches profile) or exit Artemis.

**Comment by SpoinkyNL** [comment]
Alright, if you're sure it was 1.6.1.0 and not 1.6.0.1 (I released a quick fix on tuesday, that was 1.6.0.1, yesterday I added an update with new features and fixes to the generic layer, 1.6.1.0).

Can you head into settings and set logging to Trace and see if it breaks again. After that can you upload the trace log? It's in Documents > Artemis > logs. Be sure to set logging back to Info afterwards or you'll end up with huge files

**Comment by LokeYourLord** [comment]
Nevermind, sorry about the mix-up, i thought 1.6.1.0 was the latest that i downloaded, didn't notice that from 1.6.0.1 you updated to 1.6.1.0. Issue closed.
