### ISSUE TITLE
How to animate to create words

### ISSUE THREAD

**Issue by AltOfCtrl** [SpoinkyNL/Artemis#235]
How would I go about animating letters to say the words, for example if I wanted the word hello, how could I animate each letter to appear then fade.

Currently using the Logitech G910 Orion Spectrum

Thanks ;)

**Comment by Arttumiro** [comment]
You can create a gif and make it run across the keyboard.

**Comment by SpoinkyNL** [comment]
Would be fairly easy to do in [LUA](https://github.com/SpoinkyNL/Artemis/wiki/LUA) if the API let you get a key's position. I'll add this to LUA for the next update and post an example in this thread
