### ISSUE TITLE
Active Windows Title and Process Name don't work

### ISSUE THREAD

**Issue by manskou** [SpoinkyNL/Artemis#242]
The first time I downloaded the update I set an Ambilight layer to be visible when my windows title contained 'YouTube'.
And it worked, for a while, after many restarts and a night later nothing works, I've set the process name to contain VLC and when I have vlc in focus, nothing happens.

Should I share some logs?

**Comment by DarthAffe** [comment]
Yes, please add logs and if possible export the profile you use and add this too.

**Comment by SpoinkyNL** [comment]
Looks to me as if it's not reflecting title updates to applications when they are in focus. Per example, Chrome changes it's window title when changing tab but this doesn't show in Artemis until you focus a different window and then focus Chrome again. The same goes for VLC, it adds the current filename to the window title but that's not shown until you shift focus to something else first.

LUA file that's useful for testing:
```lua
local update = 0;
-- This event is raised after every profile update, before drawing.
function updateHandler(profile, eventArgs)
    if eventArgs.DeviceType != "keyboard" then
        return
    end	

	-- Don't spam the logs
	update = update + 1;
	if (update < 40) then
		return
	end

	update = 0;
	print("Process: " .. eventArgs.DataModel.ActiveWindow.ProcessName);
	print("Title:   " .. eventArgs.DataModel.ActiveWindow.WindowTitle);
end

Events.DeviceUpdating.add(updateHandler);
```

**Comment by DarthAffe** [comment]
> Looks to me as if it's not reflecting title updates to applications when they are in focus.

It won't do this, that's right. I'll look into this, but 

> I've set the process name to contain VLC and when I have vlc in focus, nothing happens.

is a bit weird

**Comment by SpoinkyNL** [comment]
Ah in Windows 10 it breaks when you do this:

1. Focus VLC
2. Click VLC in your task bar while it's focused, minimizing it.
3. Click VLC in your task bar again, this brings the window back. Now it shows your previously active window in Artemis

**Comment by DarthAffe** [comment]
Same problem in windows 7 - I'll look into this too

**Comment by manskou** [comment]
so... i'm guessing there's no need for logs now right?

**Comment by DarthAffe** [comment]
Well, could you re-test and verify that your issue is really the one we're describing here? 
Everything should work fine if you un- and reselect vlc.

**Comment by DarthAffe** [comment]
> bringing another window in focus and then focusing back to vlc?

Focusing a "new" window should always work.

The second one is a bug which needs to be updated first.

**Comment by manskou** [comment]
Found the problem, see issue #244

**Comment by SpoinkyNL** [comment]
I've pushed the update with these fixes included, thanks for the help everyone
