### ISSUE TITLE
Conditions 'display if one/all met' toggle

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#244]
Currently a layer is displayed if it has no conditions, or all its conditions are met.
Would be nice to also display a layer if any of the conditions are met.

That way you can make an ambilight layer that shows if either YouTube **or** VLC is active, etc.

**Comment by manskou** [comment]
That should have been my issue in the first place. The layer I was using had 2 conditions (YouTube and VLC) 
That's why it wouldn't work at all

**Comment by SpoinkyNL** [comment]
Aahaaa I see, yes it's not very clear right now which one of the two it is, but it's currently only if all conditions are met.

I'll get this in with high prio
