### ISSUE TITLE
Artemis doesn't launch on startup

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#245]
Auto startup is on but it doesn't even seem to try to launch. Is it because the LGS is slow to launch?

**Comment by SpoinkyNL** [comment]
If you press ```Win+R``` and type ```shell:startup``` is there a shortcut to Artemis in there?
And if so, does clicking it run Artemis correctly?

If it's not there try disabling auto-run, clicking save and enabling it again

**Comment by Arttumiro** [comment]
Re enabling autorun fixed it thanks.
