### ISSUE TITLE
Logitech G910 audio visual issue

### ISSUE THREAD

**Issue by morganmcp2001** [SpoinkyNL/Artemis#246]
Hi, 
i updated artemis to the latest version today, and in doing so, i realised the whole numpad, no matter what song is fully lit, with occasional drops, i know this is wrong as no song i play goes that high and playing the same song before the update, and now after has completely different light patterns,
i recently got new speakers, could this be the cause?
thanks
and will provide video soon

**Comment by SpoinkyNL** [comment]
Hey, this is a know issue see #228 for more info :)

Happy holidays! 🎄

**Comment by morganmcp2001** [comment]
Oh, sorry didn't know
and thanks
happy holidays to you 🎄

**Comment by SpoinkyNL** [comment]
Hey, update with the new audio visualization soon, here's a little preview: https://www.youtube.com/watch?v=8R_Onx3bLIU

**Comment by morganmcp2001** [comment]
Thanks!
Much Appriciated

**Comment by SpoinkyNL** [comment]
Rewrite is done and included in the latest release :>
