### ISSUE TITLE
LGS version

### ISSUE THREAD

**Issue by Olliechu** [SpoinkyNL/Artemis#247]
I am currently running the newest version of LGS but Artemis seems to think I am running 8.,75.30 so won't work. I have redownloaded LGS and restarted the PC as asked.

**Comment by SpoinkyNL** [comment]
Hello and happy holidays 🎆 

Please try the following:
1. Close Artemis
2. Uninstall LGS
3. Make sure the LGS install directory is completely removed (its in Program Files > Logitech) 
4. Install LGS again
5. Start Artemis 

What probably went wrong is that Artemis was still running when you updated LGS. When that happens the LGS setup fails to update the SDK Artemis uses to talk to your keyboard 

Let me know if this helped :)

**Comment by Olliechu** [comment]
Thanks it found my g910 now :D

**Comment by SpoinkyNL** [comment]
OK great :)
