### ISSUE TITLE
Overwatch new chars

### ISSUE THREAD

**Issue by Olliechu** [SpoinkyNL/Artemis#248]
So I was looking through the customization to not see the new chars that have been added and then tried them to see, Would love for them to be added.

**Comment by SpoinkyNL** [comment]
Hey, they should show up as an option when creating condtions like this:
![Condition](http://i.imgur.com/ePZjCKY.png)

I've not updated the default profiles yet to include them, but here you can find the G910 profile with Ana and Sombra added for you: [Default - updated.json](https://www.dropbox.com/s/rlgnfx4g3wog7iq/Default%20-%20updated.json?dl=1)

To use that, just save it somewhere, click on Import Profile in Artemis and select the downloaded file

**Comment by Olliechu** [comment]
Alright, thanks a bunch for the file. Works amazing.
