### ISSUE TITLE
G910 G-keys and logo's not coloring

### ISSUE THREAD

**Issue by netzodus** [SpoinkyNL/Artemis#249]
Hello, 

It seems that I'm not able to get my G-keys and logo's working on my G910. The Artemis GUI allows me to put layers and effects on the G-keys and logo's, but they don't work. they will only show what setting they have in the LGS. I tried playing with all the profiles in LGS to see if maybe a specific mode was required but that also didn't fix the issue. 

I did read in the revision history that the G-keys and logo's are supported from 1.4.0.0 and up, so I presume they should work.

Perhaps I'm doing something wrong?

Hope you can help me :-)

Thanks!

**Comment by SpoinkyNL** [comment]
Hey, what version of LGS are you running? If it's not the latest (8.89.68) could you try shutting down Artemis and updating LGS?

Let me know how that goes :)

**Comment by netzodus** [comment]
Well. That was a simple fix.. Updating LGS did the trick! 

I thought that I was already running the latest.. Obviously I wasn't.. :-)

Thanks a lot!

**Comment by SpoinkyNL** [comment]
Great, you're welcome. Enjoy the application ^^
