### ISSUE TITLE
Not working with Corsair CUE when the setting "Enable SDK" is turned off

### ISSUE THREAD

**Issue by laurenz1337** [SpoinkyNL/Artemis#25]
You guys should add that to the error message so people know.

**Comment by SpoinkyNL** [comment]
Will do, thanks!

**Comment by JewsOfHazard** [comment]
Spoinky I can fix this tonight when I get home don't worry

**Comment by JewsOfHazard** [comment]
I am willing to bet CUE has an error message for it

**Comment by DarthAffe** [comment]
In that case you should get a CUEException containing the error code 'ServerNotFound' (https://github.com/DarthAffe/CUE.NET/blob/master/Devices/Generic/Enums/CorsairError.cs)

**Comment by JewsOfHazard** [comment]
Actually that's interesting [we check for that here](https://github.com/SpoinkyNL/Artemis/blob/master/Artemis/Artemis/KeyboardProviders/Corsair/CorsairRGB.cs)

I guess we just assumed the only way that would happen is if CUE hasn't started. I'll edit that when I get home today
