### ISSUE TITLE
[Request] TitanFall 2 support? 

### ISSUE THREAD

**Issue by deadman96385** [SpoinkyNL/Artemis#252]
I do not think it has any light support currently but it would be amazing to have!

**Comment by SpoinkyNL** [comment]
Hey, I don't own the game so I can't be sure but I doubt they provide a way of getting game data :(

**Comment by deadman96385** [comment]
Anyway I can check? But yeah they probably don't want you getting data.

**Comment by SpoinkyNL** [comment]
I did a bit of Googling and I can't really find anything. One option is reading and interpreting lighting support for other manufacturers (Like, Overwatch supports Razer keyboards so I can intercept that) but if Titanfall doesn't do this it's going to be hard
