### ISSUE TITLE
Lua log API

### ISSUE THREAD

**Issue by Cr4xy** [SpoinkyNL/Artemis#253]
Hey Spoinky,
I was wondering if you could add a `Log` function, where the message gets written into the debugger.

Thanks, and keep up the awesome work!! :+1:

**Comment by DarthAffe** [comment]
As far as I know the 'print'-function is what you're looking for.

**Comment by Cr4xy** [comment]
I had to set the log-level to debug.. Thanks anyways :P

**Comment by DarthAffe** [comment]
That's exactly what the print-function is doing. Please check if you have set the log-level to debug.

**Comment by SpoinkyNL** [comment]
Hey, the following should indeed print a message to the debugger, **if you have logging set to debug**:
```lua
print("Hello debugger, this is LUA speaking!");
```

In the next version print will simply print as Info
