### ISSUE TITLE
Key press modifiers?/Conditon

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#254]
Hi, is it possible, that you add support for custom key modifiers? if i am Working with Photoshop i would really like to light up certain keys when i press for example the CTRL key i want  U , V and C to light up 
if this software gets that kind of support it would be THE ULTIMATE tool! also if you could select single keys for one layer instead of having to make a new Layer every time i want to mark a single key. 
I know you are most likely very busy and won't have a lot of time to do that but it would be really awesome. Mind you Artemis is already awesome! 
If i can help in any way i'll gladly do so.

**Comment by LokeYourLord** [comment]
I agree, that would make it really nice and easy to see/remember keybinds, that way you always know what you can and cannot press when holding down that specific button (like in Photoshop or After Effects).

**Comment by SpoinkyNL** [comment]
Hey, I think this has been requested before and I feel like it would be a good thing to have. Will get on it after the upcoming update.

**Comment by Mrwebente** [comment]
uh this gon be gud!!

**Comment by SpoinkyNL** [comment]
I think I'll push this back one update because otherwise I'll have to push back the update itself.

The update includes a lot of rewritten code which will make implementing this easier though

**Comment by SpoinkyNL** [comment]
Here's a little preview of what I currently have.

Alongside regular conditions you can now add key-press conditions. They work together with normal conditions. This means you can have a layer activate when a hotkey is pressed and a different condition is also met.

**You can toggle a layer on and off with the same key**
![image](https://cloud.githubusercontent.com/assets/8858506/22650294/d89cffb4-ec7e-11e6-80f7-5bec91e62836.png)

**You can show a layer as long as you hold down a certain key, or combination of keys**
![image](https://cloud.githubusercontent.com/assets/8858506/22650298/dbe8e462-ec7e-11e6-9006-aff78fdbf94b.png)

**An example of how you can combine multiple keybinds. This layer activates after you press Ctrl+C and stays active until you press Ctrl+V**
![image](https://cloud.githubusercontent.com/assets/8858506/22650362/3ab0427e-ec7f-11e6-84bc-179273b0a1b1.png)

**Comment by SpoinkyNL** [comment]
Leaving this open for now as Ctrl isn't yet supported

**Comment by Mrwebente** [comment]
@SpoinkyNL so the keybinds tab is awesome, but what would be even more awesome would be if Alt and ctrl and shift would be supported as single keybinds like i said at the beginning of the thread, so if i want to display all the keys that can be pressed in combination with CTRL i just to make an overlay that that tells me exactly that by dimming the rest and lighting up those. Thank you for all this awesome work on this, i'll be sending something your way soon!
