### ISSUE TITLE
After high cpu load display if commands stop working right.

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#255]
It causes them to slow down and makes led's flicker when they are turned off with the keybind. Can be fixed with relaunching Artemis.

**Comment by SpoinkyNL** [comment]
Hi, I'm not quite sure what you mean.

I've never had any flickering, with or without high CPU load. Do you mean that you have layers displaying when scroll lock is enabled, and it's giving false positives?

**Comment by Arttumiro** [comment]
My Generic device (Logitech G303) lights and my ripple effects flicker sometimes even though they should be off after leaving from high cpu activity but its easily fixable and doesn't happen often. ill open a new issue when i can replicate it.
