### ISSUE TITLE
Issue: No PayPal Donate button

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#256]
I have found a big issue, and it's that there is no PayPal Donate button anywhere on this page or in the Software. That bug has to be fixed asap, because it is a potentially software breaking bug.

Ok but seriously, i have started having the "ARTEMIS Download" page as 2nd Home Page Tab, just to check for updates every time i start the Web Browser, it has almost become an addiction, and i haven't been hyped for a Game/Software to get updates for quite a while :)

Keep up the good work, and go get a PayPal Donate button 👍

**Comment by SpoinkyNL** [comment]
Haha thank you for your kind words, I'm glad you enjoy the program. I've got a few cool badges and a donate button on the [main page](https://github.com/SpoinkyNL/Artemis) now :).

Happy new year!

**Comment by LokeYourLord** [comment]
Thanks mate, i have been waiting for it. I will donate the second i can (waiting for my payroll in January). Issue closed i guess :P
