### ISSUE TITLE
Rocket League support G910

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#259]
So i've tried the new version 1.7.1.0 of Artemis with Rocketleague and it doesn't work, it's black and i've also tried playing around with some options with a custom Rocketleague profile using layers with boost>70 blue and boost < 20 red pulse effect and it seems like artemis is not able to get any read on Rocketleague boost the keyboard just stayed black i also disabled the generic keyboard layer and all the other layers since i don't need them so the boost display layer is not working and the other layers aren't either (i had boost display layer enabled of course ) if you need any data from me (setup etc gameversion maybe a log file or something like that) just let me know  (i also did restart my PC )

**Comment by SpoinkyNL** [comment]
Hey, I've changed the Rocket League pointers (the data that points to the boost amount in memory). Your Artemis will pick it up on a application restart if you have pointer updates enabled in settings. Let me know if it works now :)

**Comment by djzock** [comment]
Having that same original issue here, even after the pointer update. G810 is black. Settings slideout shows Rocket League as the active profile. Only other game I own that is supported is Overwatch and it works perfectly.

**Comment by SpoinkyNL** [comment]
Hey, I believe I've fixed this.

What happened is that I recently reinstalled Windows and thus Rocket League, which defaulted back to my native language, Dutch. This in turn messed up the boost readings, making them only work Rocket League when it was set to Dutch, would've thought, heh.

Let me know if it works well for you guys now :)

**Comment by djzock** [comment]
Uninstall and reinstall of Rocket League fixed the issue. Good to know for the future, thanks!

**Comment by Mrwebente** [comment]
I will try this tomorrow, thank you for looking into it

**Comment by Mrwebente** [comment]
okay so reinstalling RL seems to solve the problem. Question is why though...

**Comment by SpoinkyNL** [comment]
OK strange, might be a cache issue, who knows!
