### ISSUE TITLE
Issues with Logitech G810

### ISSUE THREAD

**Issue by frenchname247** [SpoinkyNL/Artemis#26]
I noticed that it doesn't light up the logitech logo as well as the media keys, and when changing the colors in the audio visualization it doesn't change the led color on the keyboard until the artemis is restarted, and for some reason it stops communicating with the keyboard sometimes when I switch effect or change the "wave time to live" setting in the type wave effect, and have to restart artemis.

**Comment by SpoinkyNL** [comment]
We can't currently color some keys on Logitech keyboards. Logitech is planning to release an update for this, when they do Artemis will be updated as well.

**Comment by SpoinkyNL** [comment]
Hello, all of this should be fixed with 1.0.2, could you try and let me know? :)

**Comment by JewsOfHazard** [comment]
bump
