### ISSUE TITLE
[Error] DOTA2 - Not working

### ISSUE THREAD

**Issue by VeNzorrR** [SpoinkyNL/Artemis#261]
Hello,

First of all I love what you've done here and like the customisation items within Artemis.
I've just installed it and taken it for a bit of a test run on a few games and I've noticed that the profiles do not work for DOTA 2 whatsoever.

I've tried it on Rocket league and that works fine.

Alongside this, it would be nice to expand the dota profile if possible, to cover heroes that have a 5th and 6th ability. Also the ability to compare properties, for example I'd like a layer to flash gold if I'm dead and have more gold than the buyback cost. Right now I have to do it as a percentage growth effect.

If you need any more info hit me up on steam http://steamcommunity.com/id/VeNzorrR

**Comment by VeNzorrR** [comment]
Ignore the majority of this post. I needed to restart steam after installing.

In other news, Artemis does prevent use of XBONE pads for rocket league

**Comment by SpoinkyNL** [comment]
Hey, support for a 5th and 6th ability shouldn't be a problem, I myself haven't done a lot of Dota2 so I didn't know that was a thing 😅

Unless I misunderstand, you can show layers when certain conditions are met, for your example you could create something like this:
![layer](http://i.imgur.com/DzQwfLu.png)

And if you need more logic than that, there's always [LUA](https://github.com/SpoinkyNL/Artemis/wiki/LUA)  :)

As for Rocket League, does shutting down Artemis immediately make it work as expected? I use one myself and never had any trouble

**Comment by VeNzorrR** [comment]
Hey, that would be great.

In regards to the buyback thing it's something that would be beneficial. If you can compare one property to another directly within the conditions then it opens up a new level of configuability. In the example I refer to the buyback cost is a value that rises throughout the game. I was hoping to have a layer setup to glow a different colour if my gold is above that value.

I was looking into the LUA scripting but wanted to figure out what features I actually wanted. 

Another thing that would be great would be if it was possible to have non-oblong layout maps.

If you're ever looking for any assistance in base profiles and scripts, even with the code itself, I'm actually a software development by trade so would love to help out.

Thanks

VeNzorrR

**Comment by VeNzorrR** [comment]
In relation to Rocket League, it does not, I need to reconnect the wireless adapter/if I'm using wired unplug it and then plug it back in. I am using an Xbox One Elite controller and tested it this morning,

**Comment by SpoinkyNL** [comment]
Ok that's puzzling. I'm using a regular Xbox One controller with wireless adapter and it doesn't stop working with or without a wire.

Is it just not pairing or does the input stop working? Also, which RGB peripherals are you using? I'm not sure what could possibly be breaking XInput, because I'm not interacting with it within Artemis.. so I'm suspecting it's one of the RGB SDK's

**Comment by VeNzorrR** [comment]
It stays connected, but rocket league refuses to interact with the controller. I've not checked whether it's just rocket league, or whether it is in fact across the board.

In terms of peripherals I've got:

Corsair K70 Rapidfire RGB
Corsair Void Wireless RGB
Logitech G502 RGB

I will stress that it is the Elite controller, it has the extra four buttons on the back, could it be something to do with this that's affecting it?

**Comment by SpoinkyNL** [comment]
Hey thanks for the info, I realize your controller is different from mine but there's no interaction with controllers of any kind, so I think it's caused by something unrelated.

Could you try this version of Artemis when you have the time? 
https://www.dropbox.com/s/4820c7z1jxw827x/artemis-test.zip?dl=0

I've disabled support for the G502 in that version because I think it might have something to do with it

**Comment by SpoinkyNL** [comment]
Great, thanks for helping me narrow it down!

I'll have to look into the Logitech implementation, sadly their SDK only lets you talk to device types on a functionality-level and you have to switch between them on a system wide level.

Which ends up looking like this
```cs
// Set target to per-key RGB
LogitechGSDK.LogiLedSetTargetDevice(LogitechGSDK.LOGI_DEVICETYPE_PERKEY_RGB);
// Update the colors
LogitechGSDK.LogiLedSetLightingFromBitmap(OrionUtilities.BitmapToByteArray(bitmap));

// Set target to RGB
LogitechGSDK.LogiLedSetTargetDevice(LogitechGSDK.LOGI_DEVICETYPE_RGB);
// Update the color
LogitechGSDK.LogiLedSetLighting((int) (col.R/2.55), (int) (col.G/2.55), (int) (col.B/2.55));
```

It leaves me with no control over specific devices, and switching target devices rapidly seems to be causing issues

**Comment by SpoinkyNL** [comment]
Oh, and I really appreciate any help, if you'd like to expand the Dota profile some more you could look into [events](https://github.com/SpoinkyNL/Artemis/wiki/LUA-Events#profileupdating). 

It lets you read the game data in LUA, then you can access the [layers](https://github.com/SpoinkyNL/Artemis/wiki/Layers) in your profile and update them accordingly.

Any feedback on the LUA API and their docs is also really appreciated, it's all kinda new
