### ISSUE TITLE
HELP!1

### ISSUE THREAD

**Issue by 420leantti** [SpoinkyNL/Artemis#264]
Srsly. youtube keeps shutting down when i open it. and it didnt happen before i installed artemis.

**Comment by 420leantti** [comment]
It happened when i plugged in my headsett the first time and when i played music or something it just shut google down... And now when i uninstalled it and restarted my pc everything works just like before..

**Comment by SpoinkyNL** [comment]
Hey, I've never heard of this happening before. I can't really think of any reason Artemis should do that. If you reinstall it again, does the same happen?

**Comment by 420leantti** [comment]
yup it does. Prob something to do with the audio visualizer

**Comment by SpoinkyNL** [comment]
Very strange, the audio layer is [due for a rewrite](https://github.com/SpoinkyNL/Artemis/issues/228) though. If you throw away the audio layer, does the problem also stop?

**Comment by 420leantti** [comment]
yup. i tried that aswell. And it still happened. I was on chrome like 2 sec and then it closed every chrome tab.

**Comment by SpoinkyNL** [comment]
Ok, quitting Artemis doesn't make it go away either?

**Comment by SpoinkyNL** [comment]
Alright to try to narrow it down I have two versions here, this one has Logitech generic devices taken out (so Artemis wont control your headset)
https://www.dropbox.com/s/4820c7z1jxw827x/artemis-test.zip?dl=0

And this one also has the audio layer type taken out
https://www.dropbox.com/s/pss9md3ej7c56wp/artemis-test2.zip?dl=0

**Comment by SpoinkyNL** [comment]
Turns out to be caused by plugging in a new Logitech device while the SDK is in use by Artemis. Will put this in a seperate issue to keep things clear.
