### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by stuntguy3000** [SpoinkyNL/Artemis#266]
![image](https://cloud.githubusercontent.com/assets/1522389/21716584/2c225b16-d45b-11e6-8945-d9950782ef06.png)

I'm not familiar with C# so I don't know how to debug this.

**Comment by SpoinkyNL** [comment]
Hey,

Make sure you restore NuGet packages and build as x64. 
Not seen this error before, are you using Visual Studio 2015?

**Comment by stuntguy3000** [comment]
Indeed. I am building as x64 and using VS2015.

**Comment by SpoinkyNL** [comment]
Don't know if you ever figured this one out but you could try the latest build, if it's still a problem please open a new issue
