### ISSUE TITLE
Logitech generic device issues

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#267]
There are two issues with Logitech support that I currently know off, one is that it seems to break some USB devices, the Xbox One Elite controller in particular as described here: https://github.com/SpoinkyNL/Artemis/issues/261#issuecomment-270530137

~~Another issue occurs when plugging in a new device (the G933 headset at least) that can cause Chrome to act strangely as described here: https://github.com/SpoinkyNL/Artemis/issues/264~~

Would be best to get a confirmation on both from multiple sources to make sure they aren't system-specific issues but I can't test this myself (don't own a Logitech device other than G910)

**Comment by Arttumiro** [comment]
I have a G303 and it doesn't cause any problems with Chrome or the Nvidia shield controller atleast from what i have tested.

**Comment by SpoinkyNL** [comment]
@Arttumiro are you using it in combination with a Logitech keyboard?

**Comment by Arttumiro** [comment]
Yes i am using it with the G910 (sorry for late response)

**Comment by kalifck** [comment]
I have a g910 and G900 Mouse combi and when I start Artemis the leds in the g900 shuts off
( Hope I am in the right section ! ) didnt want to start a new issue for nothing. otherwise its all good

**Comment by Arttumiro** [comment]
@kalifck Do you have a Generic device layer? because to make Logitech mice and headsets work you need to use the Generic device type because the Logitech api works differently than the Corsair and Razer ones.

**Comment by kalifck** [comment]
I'm a idiot xD thank you I used the mouse  Layer didnt saw the generic one for logitech even tho I read it thanks again
