### ISSUE TITLE
No effects in The Division

### ISSUE THREAD

**Issue by SirMarty** [SpoinkyNL/Artemis#268]
Running Artemis first, I went into The Division settings, however, it doesn't allow me to enable 3rd Party LED support.  I did install the Visual C++ packages from the FAQ and it didn't make a difference. Rocket League and GTA V work great though.

CM Masterkeys Pro S on Win 10.

**Comment by SpoinkyNL** [comment]
Hey there,

I haven't tested The Division for a while, haven't gotten around to installing it after doing a fresh Windows install yet.

That you can't enable the 3rd Party LED support in the menu usually indicates that the right files aren't in place.

Could you get me a log file of you starting Artemis and then The Division? You can follow these steps:

1. Open up the settings menu and set the loggin level to ```debug```.
2. Restart Artemis and then start The Division, try and see if you can enable 3rd Party LED support.
3. Head into ```Documents > Artemis > logs```.
4. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
5. Optionally set the logging back to Info to keep your log files small.

Thanks!

**Comment by SirMarty** [comment]
[log-20170107.txt](https://github.com/SpoinkyNL/Artemis/files/691683/log-20170107.txt)

**Comment by SpoinkyNL** [comment]
Hey, sorry I haven't gotten back to you yet, bit short on time.

Those logs didn't show me much I'm afraid, the most recent log is always called just log.txt, could you repeat the process and include that one instead?

Thanks for your help :)

**Comment by SirMarty** [comment]
No problem.  No rush.  Here's the right log.  Thanks.

[log.txt](https://github.com/SpoinkyNL/Artemis/files/697699/log.txt)

**Comment by SpoinkyNL** [comment]
Hey, I've updated Artemis and included a fix for this. I couldn't test it however, because the servers are offline
