### ISSUE TITLE
Changing Audio Colors

### ISSUE THREAD

**Issue by AnAngryGoose** [SpoinkyNL/Artemis#27]
However I've found a bug I think. If I try to change the colors used in "Audio Visulization" they wont change unless I enable Debug effect on and off, then re-enable the Audio Visualization. Just thought you may wanna know.

If I change the colors, save changes, re-enable the effect, nothing happens. If I change, save, then enable debug on/off, THEN re-enable audio, it works fine.

**Comment by SpoinkyNL** [comment]
Fixed in 1.0.2
