### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by ferrixx** [SpoinkyNL/Artemis#272]
I will use "CPU > TotalUsage" and dosent work :c can you help me?

**Comment by SpoinkyNL** [comment]
Hey, please take a look at this guide
https://github.com/SpoinkyNL/Artemis/wiki/Dynamic-properties

That also works for CPU TotalUsage

**Comment by ferrixx** [comment]
dosent work :c

**Comment by ferrixx** [comment]
![grafik](https://cloud.githubusercontent.com/assets/25038588/21820350/9686284a-d76f-11e6-88ad-6290f7dd590d.png)

**Comment by SpoinkyNL** [comment]
It should be ```% of 100``` because the max usage of a CPU is 100%

**Comment by ferrixx** [comment]
yes and i will have to display it when it 50% and more it

**Comment by SpoinkyNL** [comment]
In that case set it up like this:
![image](https://cloud.githubusercontent.com/assets/8858506/21820500/34385d1a-d770-11e6-88f3-77f35f8b0570.png)

**Comment by ferrixx** [comment]
no dosent work

**Comment by ferrixx** [comment]
![grafik](https://cloud.githubusercontent.com/assets/25038588/21820567/7efe9828-d770-11e6-9a7f-034eab07cfb1.png)

**Comment by SpoinkyNL** [comment]
Now it should only show when your CPU usage is actually above 50%.

Try taking off that condition and see if the bar fills up at all. It works on my system

**Comment by ferrixx** [comment]
i have changed it to 5% and i have 10% CPU Usage

**Comment by SpoinkyNL** [comment]
Yeah the top lets you say when to show the layer, in this case when CPU usage is 50% or higher.
The bottom tells the layer to change its with based on how much CPU usage you have.

If you just want it to show how much CPU usage you have, just take the condition off altogether (click the recycle bin and save it) .

**Comment by ferrixx** [comment]
nice, it works :3

**Comment by SpoinkyNL** [comment]
Alright great 👍
