### ISSUE TITLE
Rocket League Patch  [Game Update] 

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#273]
sorry to be the bearer of bad news but RL recieved a Patch just yesterday, now RL support is broken again

**Comment by SpoinkyNL** [comment]
Noes, that's too bad :c

Thanks for letting me know though, busy with school but hopefully I'll get it fixed before the end of the week

**Comment by Mrwebente** [comment]
no rush thanks for your work!

**Comment by busaku** [comment]
hi,

is 1.7.1.0 the correct version or they arent an update available now?
Because the boost dont work in 1.7.1.0 at the moment ;)

thanks
paD

**Comment by busaku** [comment]
Hey, on 1.8.0 i have the same issue :(

**Comment by manskou** [comment]
we gotta do something about rl support xdd

**Comment by busaku** [comment]
i spend a few bux - blackmail for rl support xD

**Comment by SpoinkyNL** [comment]
Thanks for the support :) 
I'm having a bit of a busy time but I'll look into updating it tonight, it doesn't require a full Artemis update

**Comment by busaku** [comment]
Sounds nice :)

**Comment by SpoinkyNL** [comment]
Try now, make sure you restart Artemis to trigger a pointer update ^^

**Comment by busaku** [comment]
it works :) thx

**Comment by SpoinkyNL** [comment]
Good, thanks (feel free to open a new issue on the next update, heh)
