### ISSUE TITLE
Artemis doesn't auto update ligting effects

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#275]
Every time i change something i have to save the whole profile. It wasn't like that a couple patches ago. Im using the windows profile.

**Comment by SpoinkyNL** [comment]
Hey, the editor is a bit iffy this release. I reworked the way it takes control of the profile for the next release. 

Basically the way it'll work is as long as you have the editor open and the Artemis window on focus, the profile is in preview mode. As soon as you select a different tab in the program, you close the main window or you change focus to a different window the editor saves your profile and leaves preview mode. 

This way you'll always be seeing your latest changes when both previewing and when not

**Comment by Arttumiro** [comment]
okay cool. cant wait for next patch.
