### ISSUE TITLE
[DEVICE BUG] [G810] Keymap doesn't match device image, but image reflects the keyboard perfectly

### ISSUE THREAD

**Issue by manskou** [SpoinkyNL/Artemis#277]
I'm going to cut to the chase, here are some pics on the app and their results on my keyboard

![image](https://cloud.githubusercontent.com/assets/24620427/21902342/41c25c02-d904-11e6-85d7-040e8d4032a0.png)
*As (almost) expected, every key in the row from esc to F9 is lit, F10 is selected but not lit on the actual keyboard*

![image](https://cloud.githubusercontent.com/assets/24620427/21902400/78f6b95c-d904-11e6-9ee6-7a37d80261f7.png)
*By simply dragging & dropping a row below, we should see similar results. However, no key in my keyboard is actually lit!*

![image](https://cloud.githubusercontent.com/assets/24620427/21902513/da446736-d904-11e6-96d7-435be3eb3b87.png)
*By enlarging the area by a row, we get (almost) normal results, every selected key is lit, except the last keys from both the rows! (blue squares)*

![image](https://cloud.githubusercontent.com/assets/24620427/21902670/77c515b4-d905-11e6-8c3b-9376a6e9a275.png)
*Having decreased the area by a row from the bottom, we come back to the second picture, but with one key difference (moth metaphorically and literally), every key in the row is lit, except the (you guessed it) the last one*

![image](https://cloud.githubusercontent.com/assets/24620427/21902768/e0a59036-d905-11e6-9114-05553759d899.png)
*Why are you posting the first photo?, you might ask. Well, it's because I moved the selection back to this 1st row, and **no keys are lit***

![image](https://cloud.githubusercontent.com/assets/24620427/21902900/62034808-d906-11e6-91d6-466aade794bb.png)
*Seven looks half-selected and is not lit, 3 through 6 are tho...*

![image](https://cloud.githubusercontent.com/assets/24620427/21902940/8b90f3fa-d906-11e6-8d3e-1b7567654d9d.png)
*This is the selection I have to make in order to have "3" properly lit, I think the picture speaks for it self*

![image](https://cloud.githubusercontent.com/assets/24620427/21903018/dbe5b494-d906-11e6-8e4b-9bb6e9e86209.png)
*Selection shows L, but K is the only key lit up*

These is the general problem, if u want, I am offering to teamview (is that even a verb?) while pointing my webcam to the keyboard so you can 'experience' my struggles.

**Comment by SpoinkyNL** [comment]
Hey, thanks for the detailed report, it's not perfect for any keyboard but it seems it's really far off for the G810. 

This is because the pixels are drawn in a regular grid and the keys aren't in a regular grid some deviation is to be expected. However, I can manually compensate for the ones that are really far of, which is what I'll do for the G810 using these screenshots, thanks!

Won't be in the next update because that would delay it too much, but I'll definitely get on it. :)

**Comment by manskou** [comment]
When you get on it, feel free to hit me up if you need any help (more
screenshots/testing).

And no need for it to be on the next build anyway, I too don't have a lot
of time as a student to tamper with my keyboard 😂😂

**Comment by SpoinkyNL** [comment]
Will let you know when I have something ready, I'll also look into #215 at the same time

**Comment by manskou** [comment]
you could add this on the known issues ;)
@SpoinkyNL
