### ISSUE TITLE
Automaticly Change Default Output Device

### ISSUE THREAD

**Issue by MikeUNtested** [SpoinkyNL/Artemis#278]
Is there a way that the audio visiualisation gets showed even when I switch my default output device?

At this time I have to restart the programm for that.

**Comment by SpoinkyNL** [comment]
Hi, I'll hopefully be able to do this as part of #228

**Comment by SpoinkyNL** [comment]
I forgot to mention, since 1.8 the audio layer is capable of doing this. :)
