### ISSUE TITLE
Suggested Windows Profile Details

### ISSUE THREAD

**Issue by loganintech** [SpoinkyNL/Artemis#279]
* Email Received
* Email Received (from configurable email)
* Email Sent
* Calendar Appointment Coming Up (configurable time)
* RSS Feed Events
* Tracking Information from Various Websites (Travis-CI) 
* Application(s) Running

**Comment by SpoinkyNL** [comment]
Will look into this when events are expanded and lists are supported in data models

**Comment by Heinyy** [comment]
Can I add: A "profile" when session is locked.
