### ISSUE TITLE
Setting changes itself when trying to select keyboard type

### ISSUE THREAD

**Issue by DylanAlloy** [SpoinkyNL/Artemis#28]
When I bring the settings menu out, and change my keyboard type, I click "Save" but nothing happens.

After this, closing the settings menu reveals the setting in the dropdown changing itself again. Kinda like watching the fridge light turn off when you close the door. 

Can't stop it from setting my keyboard to a Logitech. I might take a look at the source and compile it myself though. Thanks!

**Comment by JewsOfHazard** [comment]
This is a known issue we are working on. The following fix has worked for some users.

* Exit and restart artemis (from the taskbar right click + exit)
* Assure that artemis is enabled
* Intentionally select logitech keyboard
* Select corsair keyboard
* Enable and disable artemis a few times
* Save settings

**Comment by DylanAlloy** [comment]
Hey, ran into you in the thread.

I can't restart Artemis anymore, it always thinks it's running and so I uninstalled, restarted my computer and everything. It still thinks it's running when it's not, even on boot when autostart kicks in. 

I've never heard of a program alive check going so wrong so I'm going to look into the source and maybe help out a little so I can learn something.

**Comment by DylanAlloy** [comment]
http://pastebin.com/EYVRQpYq

**Comment by DylanAlloy** [comment]
Lol okay now uninstalling and restarting my computer just brings it back without my instruction

**Comment by SpoinkyNL** [comment]
Hello, could you remove all traces of Artemis and try with the latest setup?

**Comment by DylanAlloy** [comment]
Hey sorry for a delayed reply, it's working great! Thanks a lot. Connect
with me on https://www.linkedin.com/in/dylan-moore-a00bbb81 if you want and
I'll vouch for you guys. You're doing a lot of work for free!

**Comment by SpoinkyNL** [comment]
Good stuff :) Ty for reporting back

**Comment by DylanAlloy** [comment]
Hi SpoinkyNL/Artemis,

I'd like to add you to my professional network on LinkedIn.

- Dylan

Confirm that you know Dylan: https://www.linkedin.com/e/v2?e=0-inl6whqf-8j&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=yvhDu0xc&invitationId=6131662660174962688








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-inl6whqf-8j&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGB960tZVx9PwAAAVRgK0_EILhJF4PNcm-l1Ke7w3fFEfDkwYzZpIAzVJMJ5yLVNtAs9bAHswQbFE0Wf6YGQKAtroV-cXv-otdgNUFV81q92TAQTYL_2R3MGZcNUKXNHpReBSnrJnPi0yMR3LmfkKYWQGZRRT36Rdw1jkYjN8GZO2cYlFV26K2TSZ6DENfEH2Jh&eid=0-inl6whqf-8j


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-inl6whqf-8j&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
