### ISSUE TITLE
ATS support

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#283]
I would like American Truck Sim to be supported. It wouldn't be that hard to implement as ets2-telemetry-server already has ATS support. I changed ETS2's ProcessName to 'ProcessName = "amtrucks";' and it worked.

**Comment by SpoinkyNL** [comment]
Hey, they basically share the same API so all I have to do is expand the data model a bit and add another folder selection bar, will try to get it in soon

**Comment by SpoinkyNL** [comment]
Hey, I saw you compiled Artemis yourself in your other issue. Could you try pulling the latest development branch and see how ATS works?

I also included a fix for #284

**Comment by rakosi2** [comment]
Oh my, Thank you so much. This is fantastic. It automatically found my steam library and is working for both ATS and ETS2.
