### ISSUE TITLE
General profile getting auto enabled

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#286]
I would prefer to have Artemis disabled while I am not gaming and run when I do game. I uncheck the Enable module from General profile and Artemis unhooks from Corsair. When I enter and game and then leave, the General profile is re-enabled.

**Comment by SpoinkyNL** [comment]
Hey, that shouldn't be happening, ty for the report

Op 18 jan. 2017 10:31 schreef "rakosi2" <notifications@github.com>:
