### ISSUE TITLE
Not really an issue, but...

### ISSUE THREAD

**Issue by LilJashy** [SpoinkyNL/Artemis#287]
I have an E-element Z88, which is definitely on the lower end of mechanical RGB keyboards, but I was wondering if you have any intent of modifying Artemis for keyboards outside of those big name brands

**Comment by Arttumiro** [comment]
It has predetermined colours. The RGB Lights cant be changed in software. You only have the settings it comes with.

**Comment by SpoinkyNL** [comment]
If it's capable of per-key lighting I'd need an SDK to control them. 

The way Artemis is built it's easy to add new keyboards as long as they have an SDK that allows control over the LEDs, should there be an SDK please give me a link and I'll take a look :)

**Comment by Arttumiro** [comment]
It doesn't allow control of the leds atleast from what i have looked at. It has 7 premade lightning effects that can't be changed through software, Also no SDK's available.

**Comment by LilJashy** [comment]
Let me preface by saying that I am no computer programmer. Is there any way to write an sdk and apply it to this? :D

**Comment by JewsOfHazard** [comment]
Nah @LilJashy sorry. 

@Arttumiro do you change the colors by pressing something on the keyboard? If so, it can't be controlled by Artemis.

**Comment by Arttumiro** [comment]
I dont own the keyboard but its with keyboard shortcuts. it was something like FN + to switch between them.

**Comment by JewsOfHazard** [comment]
Oh I get it yeah. No unfortunately @LilJashy we can't if they keyboard has no interface with the keyboard.

**Comment by LilJashy** [comment]
Ah, alright. Thanks guys :)
