### ISSUE TITLE
Startup - Windows 10 - Admin request

### ISSUE THREAD

**Issue by busaku** [SpoinkyNL/Artemis#288]
Hey,

did everyone have the same problem, that at windows start everytime comes up the request if i want start the artemis.exe?

Must confirm it every startup. Did everyone have any idea? :)

Best regards
Pad

**Comment by SpoinkyNL** [comment]
Hi, due to it's nature Artemis requires administrator permissions.

You can disable the message system-wide by disabling User Account Control. This isn't really recommended by Microsoft but it's the first thing I do on any new Windows installation.

If you want to do this, see this page for instructions: http://winaero.com/blog/how-to-turn-off-and-disable-uac-in-windows-10/ (option 1 is easiest)

**Comment by rakosi2** [comment]
What I would do is create a basic task in the Task Scheduler. Make a Name for the task, select to start on login, start a program, then point it to Artemis.exe. Then right click your task and click on properties, and check "Run with highest privileges". That will remove the UAC question. @SpoinkyNL you could try and use this method for the auto startup.

**Comment by manskou** [comment]
+1 on that rakosi, I think this should work np

**Comment by SpoinkyNL** [comment]
Will look into this method, thanks for the suggestion

**Comment by Mofeywalker** [comment]
Thanks for the method mentioned by rakosi2! I can confirm that this works

Another thing that's a little bit annoying is that artemis always starts in the forground for me. Is this normal? The best way would be to start in the tray.

Thanks for the great tool!
Best regards 
mofeywalker

**Comment by SpoinkyNL** [comment]
Hey, under settings you can disable 'show on startup'

Op 14 mrt. 2017 6:56 p.m. schreef "Mofeywalker" <notifications@github.com>:

**Comment by Mofeywalker** [comment]
Thank you very much!
I completely overlooked that option...

**Comment by SpoinkyNL** [comment]
Artemis can now auto-run without this message, thanks for the feedback!
