### ISSUE TITLE
Artemis connected but not working

### ISSUE THREAD

**Issue by yeungmoney** [SpoinkyNL/Artemis#289]
So a few days ago Artemis was working perfectly fine with some regular effects. 1-2 days ago Artemis stopped functioning (i.e. not showing desired effects), but it detects my keyboard and such. I just tried to uninstall and reinstall Artemis with no luck. Animations on the software look a bit sluggish, so maybe you might have an idea what is wrong. Thanks! I'm using a MasterKeys Pro L btw.

**Comment by SpoinkyNL** [comment]
Hey, I've pushed an update today please let me know if the issue persists in that version

**Comment by yeungmoney** [comment]
It still doesn't work for me :/

**Comment by yeungmoney** [comment]
Ok so after physically reconnecting the keyboard, it works!
