### ISSUE TITLE
Bunch of features that "should" be "easy" to implement.

### ISSUE THREAD

**Issue by mrskizzex** [SpoinkyNL/Artemis#29]
Autostart works so thats a plus but there are some minor things i would be glad if they were added:
- keybinds so i can change effect on the fly .
- implement some effects from existing Logitech Gaming Software with keybinds support, I really envy  
  Razer Blackwidow Chroma for being able to bind effects to macros/keybinds.
- https://insider.razerzone.com/index.php?threads/app-release-ambient-effect-for-blackwidow.9997/
  If possible add this to the program.

Add Snake and Pong game upon typing Snake/Pong and double tapping Enter :D

https://www.reddit.com/r/LogitechG/comments/3yaep6/play_snake_on_your_g910_orion_spark_sparksnake/

**Comment by SpoinkyNL** [comment]
Pretty sure all of this is possible now with either the LUA engine or the keybinds :)
