### ISSUE TITLE
Request for non-standard games/profiles

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#290]
I would love to be able to create a custom profiles for a specific game/program that is not the ones that are coded for. It would be nice for me to make some static lighting so some other games other than the general profile's rainbow effect. If possible it would also be nice to have general's effect like cpu/ram usage.

**Comment by SpoinkyNL** [comment]
Hey, you can do this by creating a folder and only showing it when a certain process is active like so:
![image](https://cloud.githubusercontent.com/assets/8858506/22332036/0bcfa462-e3cf-11e6-89ea-f5ec5baf0937.png)

**Comment by rakosi2** [comment]
OK thanks.
