### ISSUE TITLE
Corsair Scimitar Pro RGB does not work

### ISSUE THREAD

**Issue by thesainthell** [SpoinkyNL/Artemis#297]
So my Corsair Scimitar arrived today and well, it does not work with Artemis as expected. 
Log included. I don't know if I have to set some things up to get this to work. Maybe you can help me.
[log.txt](https://github.com/SpoinkyNL/Artemis/files/733278/log.txt)

**Comment by Arttumiro** [comment]
Well im not a part of the Artemis team but looking at the log it seems like an error with reading the boost data from rocket league.

**Comment by thesainthell** [comment]
Thx but I'm playing Overwatch right know and there it does not work either.

**Comment by thesainthell** [comment]
After a garbage clean up from my previous installed mouse (Razer Naga 2014; at this point Artemis was already installed) and a fresh re-install of Artemis, it is working now.
At least the windows profile is working, other profiles were not tested yet.

BUT when a take a look to the debugger it shows a RAZER SDK feed which is strange because I have all RAZER stuff removed. Now I have doubts that this is the correct setup or does the corsair mouse also use the RAZER SDK?
![image](https://cloud.githubusercontent.com/assets/3634531/22365124/202d547a-e476-11e6-8beb-e8da5deddf25.png)

**Comment by SpoinkyNL** [comment]
Hey, glad you fixed it :). That SDK feed is just a visualization of what
data Artemis intercepts from Overwatch, it doesn't show anything unless
you're running OW and doesn't represend what Artemis is sending to the
Razer SDK itself.


*Met vriendelijke groet,*
*Robert Beekman*

2017-01-27 9:54 GMT+01:00 thesainthell <notifications@github.com>:

**Comment by thesainthell** [comment]
Hi and thanks for your reply. Now I had some time to test the game profile and noticed something weird. Keyboard works fine in game but the mouse only works if I close Artemis and reload it. If I have to guess I would think it has to do with the start order of the Corsair UE  and Artemis itself. Are there any issues related to this one?

Have a nice day and I really appreciate your work you have done so far!

**Comment by SpoinkyNL** [comment]
Hey, Artemis does try to enable the mouse right away on startup, and not again afterwards unless you disable and re-enable Artemis.

To see what's happening to mouse support we could take a look at the logs

1. Open up the settings menu and set the loggin level to ```debug```.
2. Restart Artemis and let it load the default General profile
3. Head into ```Documents > Artemis > logs```.
4. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
5. Optionally set the logging back to Info to keep your log files small.

**Comment by thesainthell** [comment]
Hey,
I've uploaded tow log files. 1st is the log direct after windows comes alive (mouse profil is not working) and 2nd is after I closed and started Artemis (mouse profil is now working as expected)

[log_windows-startup.txt](https://github.com/SpoinkyNL/Artemis/files/737720/log_windows-startup.txt)
[log_after-re-init.txt](https://github.com/SpoinkyNL/Artemis/files/737721/log_after-re-init.txt)

**Comment by SpoinkyNL** [comment]
Hey, I've updated Artemis to 1.8.1.0, please let me know how it goes now :)

**Comment by thesainthell** [comment]
Hi - with Version 1.8.1.0 and the 15 seconds startup delay it is finally working. Thank you!
