### ISSUE TITLE
Cannot Switch to the Corsair Option, It stays stuck on Logitech.

### ISSUE THREAD

**Issue by rjparsons9** [SpoinkyNL/Artemis#30]

**Comment by JewsOfHazard** [comment]
This is a known issue we are working on. The following fix has worked for some users.

* Exit and restart artemis (from the taskbar right click + exit)
* Assure that artemis is enabled
* Intentionally select logitech keyboard
* Select corsair keyboard
* Enable and disable artemis a few times
* Save settings

**Comment by rjparsons9** [comment]
I did this and it stayed at a blank box. I then tried to enable an effect, but an error message came up and Artemis crashed
