### ISSUE TITLE
Generic device problems with linear gradient

### ISSUE THREAD

**Issue by Arttumiro** [SpoinkyNL/Artemis#300]
The transfer from one color to another isn't smooth and is stuttering a bit. I fixed a part of it by disabling the LGS lighting profile but there's still a bit of stuttering. It isn't that big of a deal just a bit annoying.

**Comment by SpoinkyNL** [comment]
I hard to turn down the resolution on which the generic device is rendered due to performance issues. Next update I hope to fix this with a better approach

**Comment by Arttumiro** [comment]
okay thanks i will wait for that.
