### ISSUE TITLE
Macro Scripting implementation.

### ISSUE THREAD

**Issue by Vanitied** [SpoinkyNL/Artemis#302]
This is undoubtedly the best RGB controller software out of anything online. I know some keyboards have macro scripting built in, but as an owner of a Masterkeys Pro, the all the macros are on the fly. 

I know it's possible with lua, but I tried and failed..
I think this feature could be amazing especially considering the parameters you can already use to change color sections, could now be used on the macros, for example, if league of legends is open, I have a specific lighting layout set, and now could have macros too. I appreciate the response, thank you!

**Comment by SpoinkyNL** [comment]
Hey, thanks for the kind words, glad you like it

You mean that you'd like to bind small LUA scripts to macro keys on your keyboard?

I'm planning to add key bindings to Artemis (and expand it to LUA) so that would allow for this to be done. When that's ready I'll provide some examples. 

This means you could also bind them to macro keys per example,, have a macro press ```Ctrl+Shift+1``` and bind that in LUA. I'll come up with some examples when the time is there :)

**Comment by Vanitied** [comment]
Well, when I was checking the LUA wiki I saw there was the event, "KeyboardKeyPressed," and the PressKeys function, so its assumed that there are ways to do scripting with just those if i put my mind to it.

What i mean for scripting is just a basic scripting element to the program, IE. Press Numpad5, types "Hello."

I know this is very easy to do with autohotkey and such but i think having this included could push it into the number 1 keyboard software slot.

Including LUA functions with this could also be awesome, as it could allow for things like cycling through a set of colors when the key is pressed for example. Just poking out some ideas. No immense need for anything i guess but always worth mentioning.

**Comment by SpoinkyNL** [comment]
Hey, I've released a beta with keybind support both on layers and in LUA
https://github.com/SpoinkyNL/Artemis/releases/tag/1.8.2.0

Here's some example LUA
```lua
-- Simply call a method
function kbTest()
	print("oohai!");
end
Keybind.SetKeybind("test1", "SHIFT+D", kbTest);

-- Call a method with argument(s)
function kbTest2(message)
	print(message);
	-- As a test, remove the keybind after being pressed once
	Keybind.RemoveKeybind("test2");
end
Keybind.SetKeybind("test2", "SHIFT+F", kbTest2, "hello!!!");
```

Let me know how it goes

**Comment by SpoinkyNL** [comment]
This is included in the latest release, for more info see the [wiki](https://github.com/SpoinkyNL/Artemis/wiki/LUA-Keybinds)
