### ISSUE TITLE
RAM usage 1.8.1

### ISSUE THREAD

**Issue by busaku** [SpoinkyNL/Artemis#307]
Hey, RAM Usage dosent work anymore :(

**Comment by SpoinkyNL** [comment]
Hi,

In 1.8.1 RAM usage was changed, make sure you update your layers.

Per example set it up like so:
Width: ```Performance -> RamUsed``` ```% of property``` ```Performance -> RamTotal``` ```Left to right```

**Comment by busaku** [comment]
thx, works perfect
