### ISSUE TITLE
[Request] iTunes support

### ISSUE THREAD

**Issue by squiddyt** [SpoinkyNL/Artemis#308]
Would it be possible to add support for iTunes similar to the existing Spotify/Google Play options?

**Comment by Arttumiro** [comment]
Not part of the Artemis team but it seems like it doesn't have an API like Spotify and Google play have. So getting song progress etc. is impossible.

**Comment by squiddyt** [comment]
I know it has some sort of API - I’ve used Rainmeter skins that give you track names, song progress, etc.

I’ve looked into it and apparently Apple stopped supporting it, but as of right now it still works.

**Comment by Arttumiro** [comment]
Rainmeter has its own plugin called NowPlaying that shows the details of almost every music software but i don't think there's anything that could work with Artemis.
