### ISSUE TITLE
[Enhancement] Ambilight Layer Transparency

### ISSUE THREAD

**Issue by manskou** [SpoinkyNL/Artemis#309]
Being able to set black=transparent. In example when you're gaming and have the ambilight on, Should you reach a dark area where your keyboard's lights shut off, have a faint color so you can see them. Once you reach a bright area again, the faint  shuts off and you see your normal Ambilight layer.

Also, on the long run, a decrease in latency on the Ambilight layer would be appreciated, unless its my CPU's fault.

**Comment by SpoinkyNL** [comment]
Just as a quick headsup you can decrease the latency by increasing the update rate under settings (top right of the main window) but this'll increase CPU usage.

Making it transparent shouldn't be hard, I'll look into adding an option

**Comment by manskou** [comment]
I'm sorry, I totally missed that option! !
