### ISSUE TITLE
Keyboard Does Not Switch to Corsair, It Stays Stuck at Logitech

### ISSUE THREAD

**Issue by rjparsons9** [SpoinkyNL/Artemis#31]
`An unexpected error occurred in Artemis.
Exception has been thrown by the target of an invocation.
Object reference not set to an instance of an object.
System.Reflection.TargetInvocationException
Message: Exception has been thrown by the target of an invocation.
Stack Trace: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean >constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] >arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] >parameters, CultureInfo culture) at Caliburn.Micro.ActionMessage.<.cctor>b__e(ActionExecutionContext context) at Caliburn.Micro.ActionMessage.Invoke(Object eventArgs) at System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.Controls.Primitives.ButtonBase.OnClick() at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent >newEvent) at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args) at System.Windows.Input.InputManager.ProcessStagingArea() at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport) at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 >timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel) at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr >wParam, IntPtr lParam, Boolean& handled) at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr >lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& >handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 >numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, >Int32 numArgs, Delegate catchHandler)
TargetSite: System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
Source: mscorlib
HResult: -2146232828
System.NullReferenceException
Message: Object reference not set to an instance of an object.
**Stack Trace: at Artemis.Modules.Effects.AudioVisualizer.AudioVisualizerModel.Enable() at Artemis.Models.MainModel.ChangeEffect(EffectModel effectModel) at Artemis.Models.MainModel.EnableEffect(EffectModel effectModel) at Artemis.Modules.Effects.AudioVisualizer.AudioVisualizerViewModel.ToggleEffect()**
TargetSite: Void Enable()
Source: Artemis
HResult: -2147467261-`

**Comment by SpoinkyNL** [comment]
Could you post this stack trace on http://pastebin.com/ for me?

**Comment by rjparsons9** [comment]
mhm http://pastebin.com/6X3Qcc9U

**Comment by DylanAlloy** [comment]
This also caused a crash wherein I cannot any longer restart the app.

Even if I restart my computer or uninstall and then reinstall Artemis. It always thinks it's running.

**Comment by SpoinkyNL** [comment]
Hello, could you remove all traces of Artemis and try with the latest setup?

**Comment by JewsOfHazard** [comment]
bump
