### ISSUE TITLE
Settings/Properties for scripts

### ISSUE THREAD

**Issue by Cr4xy** [SpoinkyNL/Artemis#312]
It would be amazing when a LUA script could have properties just like a layer, so that one could use it more than once in a profile.
For example a rain-script could have the property "Matrix", and when enabled, the rain would only be green.

Thanks and keep up the amazing work! :+1:

**Comment by SpoinkyNL** [comment]
Will have to see how feasible it is, you could just use layers for triggers as a workaround but a UI would be nicer

**Comment by SpoinkyNL** [comment]
There's the GUI module now: https://github.com/SpoinkyNL/Artemis/wiki/gui
And the storage module: https://github.com/SpoinkyNL/Artemis/wiki/storage

I'll leave this open until I've finished updating the wiki.

**Comment by Cr4xy** [comment]
Awesome!! :+1::+1::+1:
