### ISSUE TITLE
Key press effect not working on G910

### ISSUE THREAD

**Issue by maddtom1** [SpoinkyNL/Artemis#313]
Hello,
 I've encountered an issue with the 'Key Press' effect not working at all for my Logitech G910 Orion Spark. This always used to work but only after updating has it failed. Any words on this are much appreciated

Cheers,
Tom

**Comment by maddtom1** [comment]
Disregard said issue, seemed to fix itself after minimising Artemis

**Comment by SpoinkyNL** [comment]
Ok, ty for reporting back!
