### ISSUE TITLE
Artemis sitting at 25% CPU usage

### ISSUE THREAD

**Issue by Vanitied** [SpoinkyNL/Artemis#315]
Not sure what to do about this, because Artemis just constantly has 25%+ CPU usage and my effects will regularly freeze on the keyboard.

![](http://i.imgur.com/QYP9q9M.jpg)

Masterkeys Pro L
i5 6500 Intel

**Comment by SpoinkyNL** [comment]
Hey, that's strange, must be freezing up somewhere. Does it happen every time?

When it happens could you do the following for me to get a log:

1. Open up the settings menu and set the loggin level to ```debug```.
2. Wait for a bit (make sure the CPU usage is still high)
3. Head into ```Documents > Artemis > logs```.
4. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
5. Optionally set the logging back to Info to keep your log files small.

Ty!

**Comment by Vanitied** [comment]
Sure thing. Something strange about it that I've noticed is, when I start my pc, it will either be a session of freezing and cpu hogging, or it will be fine. The easiest way to ensure it doesn't freeze is just to restart and everything will be fine for the next few days. Very peculiar.
Log file incoming if it happens later

**Comment by Vanitied** [comment]
[log.txt](https://github.com/SpoinkyNL/Artemis/files/802081/log.txt)

**Comment by SpoinkyNL** [comment]
Hi, sorry for not getting back to you earlier, I've not had much free time recently :\

In the logs I can't find anything that's off, does it also happen if you disable the audio layer?
