### ISSUE TITLE
latest rocket league version not working on 1.8.2.0 (G910 keyboard)

### ISSUE THREAD

**Issue by aureshion** [SpoinkyNL/Artemis#318]
it appears rocket league has once again stopped working with artemis. for me at least. I have reinstalled the game and that didn't fix it. not sure if there are more people having this issue

**Comment by SpoinkyNL** [comment]
Thanks for the report, it's probably a game update that broke it. I'll look
into it!

Op 27 feb. 2017 21:35 schreef "aureshion" <notifications@github.com>:

**Comment by aureshion** [comment]
great! just give a holler once you update and I'll test for ya!

**Comment by SpoinkyNL** [comment]
Should work again upon an Artemis restart :)

**Comment by aureshion** [comment]
works! thanks a bunch!

**Comment by SpoinkyNL** [comment]
Great :)
