### ISSUE TITLE
Gif Speed

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#319]
I do like the Gif but I would a slider to slow down the gif. I am guessing that it is work in progress and animation slider does not work for it yet. My image is fine in chrome and Microsoft Photos but is really fast in Artemis and Irfan. 
![giphy](https://cloud.githubusercontent.com/assets/6037087/23541274/1b4dde08-ff9b-11e6-8d99-4364e6a23365.gif)

**Comment by SpoinkyNL** [comment]
Hi, I'll see if I can couple this to the animation speed slider, thanks for the suggestion

**Comment by SpoinkyNL** [comment]
This is included in the latest release.

I do want to point out that you can create the effect this GIF gives also with layers as seen here:
![image](https://cloud.githubusercontent.com/assets/8858506/24083747/733b7036-0cdd-11e7-9cd9-e5c975ff2f71.png)
