### ISSUE TITLE
[Request] Game Support: Ghost Recon Wildlands

### ISSUE THREAD

**Issue by Super-Salty** [SpoinkyNL/Artemis#320]
Are you going to make a game profile for Wildlands as soon as it's released?
I'm curious since the profile of "The Division" had a lot of cool features and I guess that Wildlands will be based on the same concept as Division.

**Comment by SpoinkyNL** [comment]
Hi, I'll look into it but during the beta I didn't notice support for any gaming gear (The Division supports Logitech which is how Artemis can support it too) and I'm not sure if I'll get the game myself.
