### ISSUE TITLE
Question about the dynamic options for keyboard, and a suggestion.

### ISSUE THREAD

**Issue by aureshion** [SpoinkyNL/Artemis#322]
I have been wondering what the dynamic options for the keyboard do, and how they are properly set up. I would like to play around with them to make something useful if possible.

On that note, I also have a suggestion:
An option to make separate general profiles have conditions as to when they should be active. (being triggered by an .exe and reverting back to a default setting when they are closed would be a good example) because as of right now you can only do something like this by making one giant profile with a ton of layers. this generally gets very buggy and doesn't work all that well.
the default software for most keyboards (as far as I know) get overridden by artemis. so such an option would be very much appreciated.

this also gives people the option to make custom gaming profiles for games that the dynamic ones don't cover. and I can imagine this will cut down the amount of gaming profile requests a little or perhaps a lot.

(If this, by any chance. Is already in artemis. I would like to apologize in advance.)

Sorry if this all seems like a jumbled mess, words have never been a strong trait of mine. ^^

P.s. feel free to reply in dutch if that is convenient to you. I am from the Netherlands as well.

**Comment by SpoinkyNL** [comment]
Hey, I'll stick to English in case this is of use to others :)

You can find some explaination on the dynamic options over here: https://github.com/SpoinkyNL/Artemis/wiki/Dynamic-properties. If anything is still unclear please let me know!

Right now the way I would make a profile support multiple applications is by splitting it up in folders, so your profile's root would just be folders like this:

- Photoshop
- Chrome
- Word

On these folders you put the condition requiring a certain .exe to be active. Any layer inside these folders will they only show if the folder's .exe is active. 

Of course this can result in a large amount of folders but it shouldn't cause bugs

**Comment by aureshion** [comment]
Many thanks for the link!

I'm not sure if I'm understanding this correctly. But are you saying that you want to implement the folder feature. or is it already there? because I can't seem to find a option for .exe's. Unless you mean the process-name.

On the buggy thing I mentioned, The visualization seems to freeze quite often. mostly when I switch focus to a different window. I think it's worth mentioning I have it set to activate when a certain word is in the window title. as process-name didn't seem to do anything at all.

I appreciate the fast reply by the way!

**Comment by SpoinkyNL** [comment]
Yep I was referring to the .exe one, it will active a certain profile when the specified .exe's window is in focus.

Haven't notices the audio freeze but I've not tried it in combination with the window title condition. 
Also a quick tip if you're curious what's going on, set debugging to Trace and in the log you'll be able to see what values the datamodel contains, such as the name of the currently focused .exe etc.

**Comment by manskou** [comment]
t  bh, I also found the window detection a bit buggy, as sometimes it will
not respond to windows title changes, a swift alt-tab fixes that tho

**Comment by SpoinkyNL** [comment]
Have you guys find a way to reliabily break it? That'll help me or
@DarthAffe fix it

Op 13 mrt. 2017 6:20 p.m. schreef "manskou" <notifications@github.com>:

**Comment by manskou** [comment]
I think the culprit is notifications.
I've set an ambilight layer to enable when the window contains the word 'Youtube'. That would mean that while being in the same process (chrome.exe) the tab change = window title change so in Facebook for example the ambilight should be off. What I found was that while being on youtube and the ambilight was on, I got a Skype notification, clicked the X on it, focus changed to skype so ambilight turned off, and when I got back to chrome it wouldn't turn on again, at least not without changing focus to another process, and the returning to chrome. Tried to change tabs, go from Youtube to Facebook and back to Youtube, but as I said, no changes.

So I think that's one way to break it.

**Comment by DarthAffe** [comment]
I'll try to reproduce this once i get home. Right now I'm not able to see any obvious reason why this case wouldn't work.

**Comment by SpoinkyNL** [comment]
Both me and DarthAffe are having some trouble reproducing this issue, could you confirm it still happens with 1.9 (even though I didn't do anything to fix it as far as I know) and if it still happens can you upload the profile that's having the issue?

Thanks!

**Comment by SpoinkyNL** [comment]
Haven't heard back from you but if you head into Artemis' global settings in the latest version, you can change the window detection to timer. It'll be a bit slower but it should always work.

![image](https://cloud.githubusercontent.com/assets/8858506/25776320/919aaf34-32bb-11e7-8529-d6e88d4c7c2b.png)

If you're still running into issues please open a new issue
