### ISSUE TITLE
README.md doens't state support for Cooler Master keyboards.

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#324]
> The following keyboards are supported
> 
> All Corsair RGB keyboards
> Logitech G910
> Logitech G810
> Logitech G410 (untested)
> Razer BlackWidow Chroma

No mention of Cooler Master.

> Other peripherals
> 
> All Corsair RGB mice
> All Corsair RGB headsets
> Logitech mice and headsets as generic devices

Not sure about Cooler Master Mice but that'll be tested today.

**Comment by SpoinkyNL** [comment]
Thanks for the heads up, added them to the list :)
