### ISSUE TITLE
[Request] Adding support for the Cooler Mastermouse series

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#325]
In Issue #324 I said that I would test if Cooler Master mice were supported, but after extensive testing (1 quick test) I have concluded that support is not yet available for the Mastermouse Series (correct me if I'm wrong though). I believe that Cooler Master has supplied everyone with an SDK at their website. Would it be possible to add support for the mice series? 

_Btw I really like the software, and it works great on the Masterkeys Pro L._

**Comment by SpoinkyNL** [comment]
I've not looked into mouse support yet for Cooler Master, I'll take a look when I can though, shouldn't be much effort.

**Comment by Supermuskox** [comment]
Great! If you even produce a beta with support for the Mastermouse series, lust let me know. I own a Mastermouse pro l and I'd be happy to run some tests.

**Comment by Supermuskox** [comment]
RBG Lights are working fine and well on my mouse. So I'd say it's a success for the Mastermouse pro L. Thank you very much!

**Comment by SpoinkyNL** [comment]
Great, was a bit of an educated guess on how it should work but I'm sure the Pro S should work too then.

Thanks for reporting back
