### ISSUE TITLE
[WIN 10][G810]Artemis Never Startup.

### ISSUE THREAD

**Issue by TurntWaga** [SpoinkyNL/Artemis#326]
Have the Logitech G810 and Windows 10.

~~Artemis has had never startup even though "Auto Startup" is enabled. I've tried to look to see if there is any solution but I can't find anything. I have no clue if it's just the LGS since that always starts up.~~

EDIT: I mean that it never starts up when I boot up PC which now I don't think that there is any.

**Comment by manskou** [comment]
Does it work normally with your G810 when you open it through the shortcut?

I have a G810 and did not experience any similar issues

**Comment by TurntWaga** [comment]
@manskou It works fine when I open it through the desktop shortcut. I'm just now thinking that the auto startup means that it will start Artemis once you open the shortcut..

**Comment by manskou** [comment]
Seems the auto startup is messed up, try putting the shortcut inside the Startup folder in your Start Menu.
Should be located here: C:/ProgramData/Microsoft/Windows/Start Menu/Programs/Startup

**Comment by TurntWaga** [comment]
@manskou That actually fixed the problem. The folder was empty but after putting the shortcut in, it starts up now. Thanks! Now I no longer have to keep opening the damn shortcut on the desktop.

**Comment by SpoinkyNL** [comment]
Hey, when you press Win+R, type ```shell: startup``` and press enter, there should open a folder, is the Artemis shortcut present in that folder?

If not, try toggling the auto-run off, applying settings, toggling it back on and applying settings again.

I know you resolved it but that should do the same thing as what you did, except in a different folder (this one is your personal startup fodler, the one @manskou linked is the system-wide one, they should work the same)

**Comment by TurntWaga** [comment]
@SpoinkyNL Yes, the Artemis shortcut is in there.

**Comment by SpoinkyNL** [comment]
Ok that's the one that should start Artemis upon startup. If you close Artemis and double click that shortcut does it start?
