### ISSUE TITLE
1.9.0.0 seems "zoomed in"

### ISSUE THREAD

**Issue by Nathan564** [SpoinkyNL/Artemis#327]
Lets say if I have one 1x1 square in the editor near the top it will cover at least 4 keys on my keyboard (Corsair Strafe RGB)

**Comment by manskou** [comment]
Could you post a screenshot of the issue?

**Comment by Nathan564** [comment]
![pic 1](https://cloud.githubusercontent.com/assets/14124854/24084088/9e288740-0cdb-11e7-88f4-47cce2022f2a.png)
![pic 2](https://cloud.githubusercontent.com/assets/14124854/24084089/a1857c22-0cdb-11e7-894c-4fb753933e9f.JPG)

**Comment by manskou** [comment]
Could be an issue with the addition of K95 RGB support, I think Artemis uses a unified keyboard layout that sometimes produces issues like #277.
We'll wait for @SpoinkyNL to have a look at it.

**Comment by Nathan564** [comment]
Only started happening since 1.9.0.0 previous version (1.8.2.0) is fine, but thanks anyway

**Comment by manskou** [comment]
yes, K95 support was added in 1.9.0.0

**Comment by SpoinkyNL** [comment]
Oops, will fix the alignment for the Strafe next update (I plan to do tiny updates more regularly so you wont have to wait forever)

**Comment by Nathan564** [comment]
Alright thanks man!

**Comment by SpoinkyNL** [comment]
Fixed in [1.9.0.1](https://github.com/SpoinkyNL/Artemis/releases/tag/1.9.0.1), just restart Artemis and you should have the corrected version :)
