### ISSUE TITLE
G910 RGB Issues

### ISSUE THREAD

**Issue by ElMeiser** [SpoinkyNL/Artemis#33]
An interesting issue with the G910 orion spark. Sometimes the preview would work but does not reciprocate on the keyboard, but when I launched Artemis on my start menu, it would not show the preview

**Comment by JewsOfHazard** [comment]
Does it say you are on corsair?

**Comment by ElMeiser** [comment]
it doesn't, I put on the Logitech gaming software and the preview works again, but not on the keyboard itself

**Comment by SpoinkyNL** [comment]
Did you try updating your Logitech Gaming Software? A check for software version will be included in 1.0.1

**Comment by ElMeiser** [comment]
The logitech software is updated to the latest version

**Comment by SpoinkyNL** [comment]
Hello, could you remove all traces of Artemis and try with the latest setup?

**Comment by ElMeiser** [comment]
It says couldn't connect to G910

**Comment by ElMeiser** [comment]
it works, Many Thanks!

**Comment by SpoinkyNL** [comment]
Great, thanks for reporting back!
