### ISSUE TITLE
CM Masterkeys Pro S: F7 to F9 no lights

### ISSUE THREAD

**Issue by benvill** [SpoinkyNL/Artemis#331]
http://imgur.com/a/ubKUg

Was working in previous version

**Comment by haqfleisch** [comment]
Affects me, too. Seems to be independent from the set profile/ overlay.

**Comment by SpoinkyNL** [comment]
Hey guys, I've noticed it too. It's an issue with the latest CM SDK (which is needed for mouse support). 

I've messaged CM and they are looking into it. As soon as there's an SDK update I'll push a new version of Artemis to address this.

**Comment by manskou** [comment]
Could be related to #327.
See my explanation there.

**Comment by SpoinkyNL** [comment]
Closing this one please refer to #328, I'll provide an update there when I know more
