### ISSUE TITLE
mouse cursor lag when starting up 

### ISSUE THREAD

**Issue by Aionicgames** [SpoinkyNL/Artemis#332]
hi. when theres a new update or something my cursor becomes really laggy when i first open the program. but then i log out and log back into windows and opens  it again it works like normal. Could it be because of the update?

**Comment by Aionicgames** [comment]
the mouse felt like 30 fps and i used msi afterburner and wallpaper engine at the same time

**Comment by SpoinkyNL** [comment]
Mouse lag is normal for the first 2 seconds or so. After that you shouldn't notice anything.
If it does stay longer than just a few seconds please do this:

1. Open up the settings menu and set the loggin level to ```debug```.
2. Restart Artemis and see if the mouse lag stays for longer than a few seconds
3. Head into ```Documents > Artemis > logs```.
4. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
5. Optionally set the logging back to Info to keep your log files small.

**Comment by Aionicgames** [comment]
yup it didnt happen after i tried the secound time! Thanks! i knew that was the case so i quickly logged off windows and back in and starterd it again. ive used it now for 20 mins with 0 problems

**Comment by SpoinkyNL** [comment]
Good to hear :) If anything does come up feel free to make a new issue!

**Comment by manskou** [comment]
I'm experiencing the same issue as mentioned in the betas' bugs, it only happens while launching Artemis and started to happen after 1.8.2.0 beta 3 in issue #276 
>when I launch Artemis, I'm getting laggy mouse/ low desktop FPS/high GPU usage for a second or so.

It's not a HUGE deal breaker but it's annoying during startup.

**Comment by busaku** [comment]
i have the same issue.. every time i change the resolution (in games e.g.) or going from a game into windows i have cursor lags to.. :/
