### ISSUE TITLE
[REQUEST] Audio visualizer

### ISSUE THREAD

**Issue by Aionicgames** [SpoinkyNL/Artemis#333]
Could u please add back the volume thing in the audio vizualiser? o.0 
And could u also add some more audio visualzer effects?  Cuz thats my favorite thing to use in ur program C:

**Comment by manskou** [comment]
Hi @Aionicgames , the Audio visualiser still exists, you can find it in the Overlays tab:
![image](https://cloud.githubusercontent.com/assets/24620427/24201479/ce789e0a-0f18-11e7-86ee-22b4bdf2ba60.png)

> could u also add some more audio visualzer effects?

What do you mean by that? Feel free to suggest your ideas!

**Comment by Aionicgames** [comment]
I mean the thing that u had there before thats removed. i forgot the name of it. and i know theres a audio visualizer. i just said it wrong xd

**Comment by manskou** [comment]
I don't think anything was removed, try going back to general and switching to the default audio visualization profile:
![image](https://cloud.githubusercontent.com/assets/24620427/24201755/af77b6fc-0f19-11e7-8320-774abaaf8914.png)

**Comment by Aionicgames** [comment]
yea u had. there were 2 volume slides. The one that if u had the slider full volume the audio wave things were higher etc. I remember something like that were here before

**Comment by Aionicgames** [comment]
or lets say. you could change height of the audio waves

**Comment by SpoinkyNL** [comment]
You can change lots of options if you create your own general profile and add an audio visualization layer to it.

To do so create a new profile, click on the + and make the layer as big as you want (for the best result make it cover your whole keyboard).

Then in the layers list double-click it and change it's type to Audio visualization. From there on you can change settings and see the result
