### ISSUE TITLE
Mouse Support?

### ISSUE THREAD

**Issue by sr23k** [SpoinkyNL/Artemis#334]
In your description, it says Artemis is compatible with mice.  However, I cannot figure out how to use my Corsair Scimitar RGB with Artemis.

**Comment by Supermuskox** [comment]
Artemis is compatible with a fair amount of mice. Cooler Master Mice are supported, which isn't stated in the README (Take notes Spoinky!), but all Corsair mice should also be supported, if the README is correct. See if you can edit the mouse's colors in the General profile and seeif the mouse responds to changes. If it doesn't, I suggest adding an issue.

**Comment by sr23k** [comment]
How do I make my mouse show up in the general profile?

**Comment by sr23k** [comment]
I understand, you don't have to have a keyboard selected to control the mouse.
