### ISSUE TITLE
Request: CPU Temps

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#338]
Would it be hard to get cpu temps into Artemis because I would like to have the cpu temp just like the Ram usage and ETS2 RPM gauge.

**Comment by DARKKi** [comment]
I think it could be easily extracted from speedfan or coretemp since few programs rely on them to provide temps. I have no further knowledge about this though :\

And i would like CPU/RAM/Netspeed/etc features also :)

**Comment by rakosi2** [comment]
CPU and RAM usage is already in Artemis in the dynamic's dropdown box.

**Comment by rakosi2** [comment]
@SpoinkyNL for Network speed: http://www.m0interactive.com/archives/2008/02/06/how_to_calculate_network_bandwidth_speed_in_c_/
for CPU temp, ROOT\WMI MSAcpi_ThermalZoneTemperature CurrentTemperature 
http://stackoverflow.com/revisions/3114251/4
