### ISSUE TITLE
Artemis crashes after clicking tabs (Blackwidow Chroma)

### ISSUE THREAD

**Issue by DARKKi** [SpoinkyNL/Artemis#341]
I have enabled my keyboard (Razer Blackwidow Chroma) from settings.

When ever i go to any tab maybe first one displays fine but after i click on second one then the whole app crashes. It does not matter which one i click (games, general and overlays).

I provided an picture of what happens and attached log. [log-20170415.txt](https://github.com/SpoinkyNL/Artemis/files/923200/log-20170415.txt)

![artemis-stopped-working](https://cloud.githubusercontent.com/assets/5562502/25059627/a6ff63fe-2192-11e7-836f-7addf342fcbf.png)

**Comment by SpoinkyNL** [comment]
Hey, please try this release:
https://github.com/SpoinkyNL/Artemis/releases/tag/1.9.0.2

Just grab the Setup.exe and please let me know how it goes :)

**Comment by DARKKi** [comment]
Worked just fine with that! :]
