### ISSUE TITLE
Can't move layer under another layer

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#342]
So I have a large layer over the whole keyboard and if I want to move a smaller layer that is under the larger layer, I can't. Even if the small layer that I want to move is selected and there is a highlighting box over around the small layer, when I try to move small layer it moves big layer.

Currently, the way to get around this is to disable the large layer, move small layer, then re-enable large layer.

**Comment by SpoinkyNL** [comment]
Yeah that's probably how I should make it work, will look into it

**Comment by SpoinkyNL** [comment]
I included this in the latest release, feels a lot more natural now thanks for the suggestion
