### ISSUE TITLE
How to have layer disabled by default?

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#343]
How do I have the layer disabled by default and be enabled by keybind. Currently I have to hit the keybind to disable it.

**Comment by SpoinkyNL** [comment]
Fixed in the latest release, as long as the 'Enable' keybind is the topmost one, it'll be disabled until pressed

So make sure it looks like this:
![image](http://i.imgur.com/yVS0pK9.png)

**Comment by rakosi2** [comment]
Thanks but with this implementation, I can imagine that other people would not know this and will wounder why the layer is not working without some sort of explanation.

**Comment by SpoinkyNL** [comment]
True, a better long term solution would be having a 'start enabled' and
'start disabled' option.

For now I'll make a wiki page about keybinds and mention this functionality

Op 7 mei 2017 01:07 schreef "rakosi2" <notifications@github.com>:
