### ISSUE TITLE
Bug: Alt-Tab brakes profile

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#345]
I have a profile set up so if I play a game, then it disables my backlight and audio visualization, and some game specific stuff. When I alt-tab out of the game, the game stuff still shows. also noticed that the audio visual crashes in the last sound wave, I have to disable Artemis and enable it to fix audio. The game that it always does it is Osu! and running at full screen.

**Comment by SpoinkyNL** [comment]
I've noticed audio visualization can stop working in some cases as well. I'll see what I can do. It's a bit annoying because it is a library I use but maybe I can find a fix

**Comment by rakosi2** [comment]
Ok so I set Artemis to trace log and when I alt-tab out of Osu and then back it says that the "ProcessName": "DisplayFusion", and doesn't go back to osu. I closed DisplayFusion and same thing happened but it says explorer instead. 

1. I am playing a youtube video so I can see if audio wave still works
2. Open video game Osu!
3. Audio wave gets disabled by folder disable for ProcessName osu!
4. alt-tab out of Osu! or close Osu!
5. audio wave is broken
6. right click on Artemis in the taskbar and disable
7. right click again and on enable and Audio wave gets fixed

[Artemis.zip](https://github.com/SpoinkyNL/Artemis/files/939656/Artemis.zip)

**Comment by SpoinkyNL** [comment]
Thanks for the detailed description, we'll have to take another look at the current process code, maybe @DarthAffe has an idea. 

The audio visualization stopping to work is a seperate issue I'll look into when I get the chance

**Comment by DarthAffe** [comment]
I'll look into the Alt-Tab thing once I get my PC finally running :p

@rakosi2 A few more things (I don't know if this is somewhere in the logs):
- What OS (and if Win10 which patchlevel) are you using?
- What devices are connected? 
- How many monitors are you using, was Osu running on the main monitor?

**Comment by rakosi2** [comment]
- Windows 10 Education 1703 15063.138 [THEREDDRAGON.txt](https://github.com/SpoinkyNL/Artemis/files/945759/THEREDDRAGON.txt)
- Corsair K95, YCCTEAM 2000, Wacom intuos, tp-link wifi dongle, Rii i8+, Logitech C920
- Have one monitor hooked up via DisplayPort and a TV via hdmi, TV is off and on main monitor only. Yes Osu! was running on main monitor.
Just tried it again today and it crashed again with the method.

**Comment by rakosi2** [comment]
found an easier method, I closed all of my programs expect chrome to make sure nothing interfered. 
1. Add a toggle shortcut to audio visual
2. Close Artemis's main menu
3. Hit shortcut
4. Wait a second
5. Hit shortcut again to enable audio visual

**Comment by SpoinkyNL** [comment]
Thanks for that, investigating the audio issue today

**Comment by SpoinkyNL** [comment]
Found what's causing the issue with some help from @DarthAffe! Will probably push an update tomorrow

**Comment by rakosi2** [comment]
So I just tried out the dev code and it is still happening to an extent. Now I have to wait 3 seconds for it to freeze but if I open the general tab and close it, that brief disable/keyboard-flash unfreezes the audio visual.
Also it is still having trouble detecting the active window as when I open Osu!, it main backlighting gets disabled, alt-tab out and backlight gets enabled, but doesn't get disabled if I alt-tab back, but if I hit Osu!'s boss key (default is the Insert key) backlight gets disabled even though Osu! is not active anymore, then I alt-tab/click on another window or the taskbar and backlight gets enabled.

**Comment by DarthAffe** [comment]
> So I just tried out the dev code and it is still happening to an extent.
It should happen just as with the other code since there isn't any fix committed until now :p
You could try out [this](https://github.com/DarthAffe/Artemis/tree/AudioVisualizerTest) - not the final fix but a (hopefully working) workaround.

About the process thing I have to admit, that I've absolutely no idea what the problem might be. I think I'll just add a optional second "mode" which regularly checks the active window instead of listening to OS-events. this might update be a bit slower in general but should work more solid.

**Comment by SpoinkyNL** [comment]
I haven't committed the fixes yet :p

**Comment by rakosi2** [comment]
Still having trouble with Osu! but the Audio visual freezing is fixed thanks.

1. Open Osu! and Osu!'s profile is on
2. alt-tab, Osu!'s profile gets disabled 
3. alt-tab still disabled
4. hold alt
5. tap tab and Osu!'s profile gets enabled 
6. let go of alt and Osu!'s profile gets disabled again because I just left Osu!

also the boss key(Insert) still has Osu! profile active even when Osu! is no longer visible.

**Comment by SpoinkyNL** [comment]
That's strange, did you go into Artemis' settings and change the window detection to timer based?

**Comment by rakosi2** [comment]
Ah, did not know that there is a new setting, it works fine now thanks.

**Comment by SpoinkyNL** [comment]
Cool, thanks for the help everyone!

**Comment by rakosi2** [comment]
Just noticed that if you enable/disable Windows Sonic(Windows built in surround sound support), then the audio visualiser crashes like before. I don't this is a big issue because I hadn't noticed it before until now but I thought you would like to know.
