### ISSUE TITLE
Artemis slows mouse

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#346]
While Artemis is starting up, the mouse becomes to stutter very badly and stops when Artemis has turned on. It would be nice to remove the stuttering even if Artemis has to turn on longer.

**Comment by SpoinkyNL** [comment]
For me this only happens for like a second, is it much longer for you? 

Could you also try with the latest beta? (it's under releases)

**Comment by rakosi2** [comment]
I have Artemis start as I log into windows so with everything else happening, it lags out about 2-3 seconds. a bit annoying. If I just start Artemis when everything has settled it's one seconds so maybe I should delay the start up.

**Comment by Mrwebente** [comment]
this happens to me too, but it's only when it starts so not really a problem. sometimes ap to 3 seconds but most of the time only 1second

**Comment by LokeYourLord** [comment]
Ye same problem for me, it is really annoying actually.

**Comment by SpoinkyNL** [comment]
Please give the latest release a shot, I've not had any lag upon startup with my recent fixes

**Comment by rakosi2** [comment]
Thanks, there is no more mouse lag.
