### ISSUE TITLE
Audio Visualizer "Dumbed down"

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#347]
**1:** Yo Spoinky, has been a while. Anyways, i saw the improvements you did to the Audio Visualizer, and i really enjoy them, like the fact that the Audio Visualizer is a bit more stable now and actually covers all keys. HOWEVER, there are some downsides. One thing is that the Audio Visualizer isn't so "immersive" anymore, because it is constantly trying (as you even said yourself) to keep itself at 75% of covering the keyboard (horizontal) so it lights up. This however makes it so that there is almost no animation at all unless there are REALLY high differences in tones, making the Audio Visualizer look "stiff". This could easily be fixed by adding back (which you also said you would at some point) the Volume/Sensitivity option to let us decide the input volume and how much it should respond to volume differences in different frequency areas. To give a short description of what i mean, just take two songs that are somewhat different. I have one Dubstep song, with a lot of Bass and high speed rythms, and then a Rock song. But for both songs, the left side of the Keyboard (the Bass side) is almost always lit to 75%, while going further to the right it seems to decrease, no matter how different the songs are, this is how it looks like 95% of the time, for songs, TV series, movies, games, etc. Here an example picture of what i mean: 
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/25304804/ea9446e8-276e-11e7-97a9-58e470bc0a83.png)

As you can see, to the left it is about 80% covering the Keyboard (vertically), and then steadily decreasing towards the right, going up a little and decreasing again. But however the song/movie/whatever might change in tones, the animation difference (height of the waves/key rows) is rarely if ever no more than at maximum one (horizontal) line of extra keys, meaning that the difference (even when the tone difference is gigantic) is no more than 8 on the NUMPAD lighting up or not lighting up, even if the tone difference should make it so that the entire NUMPAD lights up, not just that row where the 8 is. The top of the NUMPAD almost never lights up because the Visualizer seems to try and keep it self at that constant level of covering keys. If this is hard to understand (i am really bad at explaining visual things), then just ask me and i make a video to describe this.

**2:**~~Then there are the smaller things like if you Alt-TAB out of a game or sometimes just quit a Fullscreen application, that the Visualizer just stops completely, which then makes us having to disable and re-enable Artemis (not much of a problem, more an annoyance). Then there is that Mouse Lag (completely irrelevant, only listing it up),~~ as well as the Admin request at Windows startup (also irrelevant)(solutions have been provided before as far i can remember, there was a post with a solution for this).

For the sakes of not repeating exactly what the other guy in his post said, i am just going to redirect to his post: https://github.com/SpoinkyNL/Artemis/issues/333

Thanks for reading!

**Comment by Bluethefurry** [comment]
i second this, would be a great addition!

**Comment by SpoinkyNL** [comment]
Hey guys, I wanna get this in but I couldn't do it right now before going on holiday.
