### ISSUE TITLE
Artemis Program not showing up

### ISSUE THREAD

**Issue by Awesome4287** [SpoinkyNL/Artemis#35]
After the program has installed, whenever I click on the launcher it says "running, check system tray" I can see the program in Task Manager (more details) and my keyboard (G910) has the base "flash on push" but I cannot find a way to get the window open.

**Comment by SpoinkyNL** [comment]
Is it not in the bottom right, perhaps in the hidden icons section?

Like so: http://imgur.com/Flyc1MU

**Comment by SpoinkyNL** [comment]
Hello, could you remove all traces of Artemis and try with the latest setup?

**Comment by JewsOfHazard** [comment]
bump
