### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by techy105** [SpoinkyNL/Artemis#350]
Ive noticed that in Win10 (non-creators update) that after a while it uses a lot of memory. (See image below)

Win 10 64-Bit - Logitech G910

![artemis](https://cloud.githubusercontent.com/assets/10698679/25412335/e7342150-2a19-11e7-9b6f-f8c50daeb9e1.PNG)

**Comment by SpoinkyNL** [comment]
Hey, that's definitely not normal, with which profile was this? Does it
happen again?

Op 26 apr. 2017 01:50 schreef "techy105" <notifications@github.com>:

**Comment by techy105** [comment]
This was with a custom profile. The below is from when I just ran the program. 

![image](https://cloud.githubusercontent.com/assets/10698679/25497717/6b3ed936-2b7d-11e7-8607-7f919e9a0b97.png)

**Comment by SpoinkyNL** [comment]
Could you upload the profile? I cannot reproduce this myself atm

**Comment by techy105** [comment]
[Profiles.zip](https://github.com/SpoinkyNL/Artemis/files/967102/Profiles.zip)
Theres an overlay profile and general currently in use

**Comment by SpoinkyNL** [comment]
Hey, I tried your profile and left it running for 10 minutes but I saw no increase in memory usage. Could you confirm it still happens with the latest version?

Thanks!

**Comment by TReKiE** [comment]
I've been having the same problem for a while too.
<img src="http://i.imgur.com/sBpay46.png">
[trekie profile.zip](https://github.com/SpoinkyNL/Artemis/files/1070382/trekie.profile.zip)

I think there's more to it than simply using the profile itself, as when I restart it to start again, sometimes it can be days before it happens again, or in extreme cases, hours and I run my machine 24/7.
