### ISSUE TITLE
Sleep reverts to oem profile

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#352]
I set my Corsair software to have a red background so I can see when Artemis is not running and I noticed that when I put my computer to sleep and wake it up again, the keyboard goes all red but slowly changes back to the correct color when keys get updated, ex. audio visual wave.
This is not a big issue, especially since I don't put my computer on sleep often and when I do, it's just a visual bug. Just thought you should know.

**Comment by rakosi2** [comment]
Noticed that if I unplug my keyboard while Artemis is running, wait a few seconds and plug back in, same results happen where the whole keyboard shows oem profile.

**Comment by SpoinkyNL** [comment]
Hey, seems like a CUE bug. However, Artemis should detect returning from sleep and reconnect to CUE, I'll try to figure out if this is still working
