### ISSUE TITLE
Creators update introduces conflict between MSI Afterburner and Artemis needs further investigation [BUG]

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#353]
so the previous thread with the creators update someone brought fourth the fact that if Afterburner is active Artemis stops working/crashes/won't start. This is bad because i need afterburner for monitoring my hardware and overclocking my GPU  but i want the versatility of Artemis to customize my Keyboard lighting.
i would gladly help fix this by providing further data if possible.

**Comment by SpoinkyNL** [comment]
I'm back from holiday and I'll take a look over the weekend. Im using Afterburner myself and I've not had any issues so I might need to get you a special debug version. I'll get back to you tomorrow
