### ISSUE TITLE
Logitech Software Problem

### ISSUE THREAD

**Issue by datKaspah** [SpoinkyNL/Artemis#356]
Hello, I'm trying to connect my Logitech g810 to Artemis. But it gives me an error, and tells me that my Logitech software version is too old, which it isn't. As it's the latest version. I also went to the FAQ and did installed the things there, still no luck.

**Comment by SpoinkyNL** [comment]
Hey, what version is Artemis reporting?

One thing you could try is reinstalling LGS (make sure Artemis isn't running when you do so)

**Comment by datKaspah** [comment]
Hey.
I just checked to see what version it was reporting, and now it tells me The Visual C++ 2012 Redistributable v11..... wasn't found. Although I've reinstalled it twice today. 
And I did reinstall LGS twice too

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )
