### ISSUE TITLE
Problem with Logitech G502 [Bug]!

### ISSUE THREAD

**Issue by Mrwebente** [SpoinkyNL/Artemis#357]
okay so every time i start Artemis my G- Logo on my mouse stops working. I have not seen an Option in Artemis to address that. Has this happened before? I'm Guessing that the keyboard and the mouse are using the same protocol or port or something to control lighting.

**Comment by Mrwebente** [comment]
anyone here able to help?

**Comment by SpoinkyNL** [comment]
Might be an SDK issue, sorry I'm extremely short on time for the next few weeks. After that it'll be the opposite and I'll finally have time to spend on Artemis again.

I'll look into it when I can

**Comment by Mrwebente** [comment]
okay, no Problem.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by neetdev** [comment]
I have the G502 and I've tried all kinds of settings in Artemis but nothing seems to affect the LEDs on the mouse. Would really love a fix for this.
