### ISSUE TITLE
UT directory

### ISSUE THREAD

**Issue by secnum** [SpoinkyNL/Artemis#358]
Hi everybody.

 I can't add the Unreal Tournament's directory in Artemis. The message "Error please select a valid directory ..." is always shown.

![capture](https://cloud.githubusercontent.com/assets/25979720/26033204/5fa9cc66-38a7-11e7-9d8e-d5a6d0d8565b.PNG)

**Comment by SpoinkyNL** [comment]
Hello, the UT module will need some updating. I'm download UT now to see what needs fixing. Thanks for the report
