### ISSUE TITLE
Iracing

### ISSUE THREAD

**Issue by FNDwaffles** [SpoinkyNL/Artemis#359]
iracing has added LED flag support for razer and some Logitech keyboards and none for corsair, would it be possible to do through game support?

**Comment by SpoinkyNL** [comment]
Hello, I see that iRacing has an API available to read the data required. This means it'll be easy to add to Artemis when I have the time.

**Comment by FNDwaffles** [comment]
That is fantastic !!! this will be great and will make quite a few people happy! no rush mate and than you for your work!
