### ISSUE TITLE
Looking for "ripple" effect

### ISSUE THREAD

**Issue by bree9** [SpoinkyNL/Artemis#361]
Hello, I'm looking a sort of "ripple" effect for my logitech g810, where when you press one key, the ones surrounding it starts to glow in the pace of a wave. I've tried to customize this myself but have been have not been able to do so. If someone could share a profile like that which I could import, I would appreciate it!

**Comment by rakosi2** [comment]
In the General tab, create a layer and in its properties, change the type to "Keyboard - Key Press".
There is an example profile that comes with Artemis called "Default - Type waves", duplicate it and then you can start changing things like color, size, and type.

**Comment by A1rPun** [comment]
Here is a profile export of the basic ripple effect taken from "Default - Type waves" suggested by @rakosi2:

```
{"Layers":[{"LayerType":{"$type":"Artemis.Profiles.Layers.Types.KeyPress.KeyPressType, Artemis","TempBrush":null},"LayerCondition":{"$type":"Artemis.Profiles.Layers.Conditions.DataModelCondition, Artemis"},"LayerAnimation":{"$type":"Artemis.Profiles.Layers.Animations.NoneAnimation, Artemis"},"Name":"Ripple","Order":0,"Enabled":true,"RenderAllowed":true,"Expanded":false,"IsEvent":false,"Properties":{"$type":"Artemis.Profiles.Layers.Types.KeyPress.KeyPressPropertiesModel, Artemis","Scale":6,"RandomColor":false,"X":0.0,"Y":0.0,"Width":21.0,"Height":6.0,"Contain":true,"Opacity":1.0,"AnimationSpeed":1.55,"OpacityEaseTime":0.0,"HeightEaseTime":0.0,"WidthEaseTime":0.0,"WidthEase":null,"HeightEase":null,"OpacityEase":null,"ConditionType":0,"Conditions":[],"LayerKeybindModels":[],"DynamicProperties":[],"Brush":{"RadialGradientBrush":{"@Center":"0.5,0.5","@RadiusX":"0.5","@RadiusY":"0.5","@GradientOrigin":"0.5,0.5","@MappingMode":"RelativeToBoundingBox","@SpreadMethod":"Pad","@Opacity":"1","@xmlns":"http://schemas.microsoft.com/winfx/2006/xaml/presentation","RadialGradientBrush.GradientStops":{"GradientStop":[{"@Color":"#FFFFFFFF","@Offset":"0.85"},{"@Color":"#00FFFFFF","@Offset":"0.95"},{"@Color":"#FFFFFFFF","@Offset":"0.55"},{"@Color":"#00FFFFFF","@Offset":"0.45"}]}}}},"EventProperties":null,"Children":[]}],"Name":"Ripple","IsDefault":false,"KeyboardSlug":"logitech-g810","GameName":"GeneralProfile","Width":21,"Height":6,"LuaScript":null,"LuaStorage":"{}"}
```

**Comment by sainikarmann** [comment]
How do we export this profile?

**Comment by F8ER** [comment]
> How do we export this profile?

Might this is what were looking for: ![](https://i.imgur.com/CFAzE7y.png)

**Comment by luca1122334455** [comment]
Can someone pls tell me what app are u using ?

**Comment by F8ER** [comment]
> Can someone pls tell me what app are u using ?

I'm sorry, but may I ask you rephrase the question?

**Comment by luca1122334455** [comment]
Hey,i found the app but idk how to use it :)

**Comment by F8ER** [comment]
> Hey,i found the app but idk how to use it :)

I'd suggest you consider checking out the page: <https://github.com/Artemis-RGB/Artemis/blob/master/README.md>

**Comment by luca1122334455** [comment]
hey can u pls explain me from the beginning how can i add the ripple effect
