### ISSUE TITLE
Rename just duplicates

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#362]
I just tried to rename a profile and the name goes blank and I noticed that there is now two duplicated profiles with old and new name.

**Comment by SpoinkyNL** [comment]
Hey, good catch! Fixed it

**Comment by rakosi2** [comment]
Thanks new code removes the old name profile but it still annoyingly blanks the profile name so you have to click on it. When I leave focus the the profile name does come back.

**Comment by SpoinkyNL** [comment]
Strange, I noticed this as well and fixed it alongside the duplication bug. Maybe I missed a case, will take another look
