### ISSUE TITLE
DrawLine not working

### ISSUE THREAD

**Issue by Cr4xy** [SpoinkyNL/Artemis#363]
Edit: I was missing the `thickness` parameter.
The reason I didn't have it was because the [example](https://github.com/SpoinkyNL/Artemis/wiki/Drawing#drawline) was not using it yet. :P
##
### Works
`eventArgs.Drawing.DrawRectangle(redBrush, x1, y1, x2, y2)`
### Doesn't work
`eventArgs.Drawing.DrawLine(redBrush, x1, y1, x2, y2)`
## Error
`cannot convert a void to a clr type System.Double`

Thanks and keep up the good work!

**Comment by SpoinkyNL** [comment]
Thanks for the heads up, I've updated the Wiki :)
