### ISSUE TITLE
[Bug?] Issue with Razer Deathadder Chroma 

### ISSUE THREAD

**Issue by Czpl** [SpoinkyNL/Artemis#364]
Once I used Artemis for the first time (which works with my keyboard - CM Masterkeys Pro S) the chroma effects stopped working for my Razer Deathadder. 

Now even if I don't open Artemis, my Razer Deadthadder doesnt change color when I launch Overwatch. 
This is probably not exclusive to overwatch, (using as an example).

**Comment by Czpl** [comment]
okay looks like it was coincidence and it's synapse/overwatch issue. (still not working, but most likely not artemis fault)

**Comment by SpoinkyNL** [comment]
Hello, sorry for not replying earlier.

This could still be Artemis' fault. If you head into your Overwatch directory Artemis placed a file there called ```RzChromaSDK64.dll```. If that's present you can safely remove it and Overwatch functionality with Synapse should work again.

**Comment by Czpl** [comment]
yup, that was it. Thank you.

Does that mean I can't use both at the same time?

**Comment by SpoinkyNL** [comment]
Unfortunately not, but if you disable the Overwatch module you can use the
rest of Artemis just fine, it wont place that DLL again


*Met vriendelijke groet,*
*Robert Beekman*

2017-06-01 21:08 GMT+02:00 Mateusz Czapla <notifications@github.com>:
