### ISSUE TITLE
Can't connect Logitech G810 RGB keyboard.

### ISSUE THREAD

**Issue by bree9** [SpoinkyNL/Artemis#365]
It worked for a couple of days, but then randomly stopped and when I try to connect my Keyoard I get this error:

Couldn't connect to your logitech keyboard. Please check your cables and updating the Logitech Gaming Software. A minimum version of 8.81.15 is required (detected 8.75.30). If detected version differs from the version LGS is reporting, reinstall LGS or see the FAQ.

But my LGS software says 8.92. I tried reinstalling, restarting, I went to FAQ and downloaded the firmware, but still get the same error.

**Comment by TwitMyTwatter** [comment]
I'm getting the same issue, only I have the G910

**Comment by diogotr7** [comment]
Same issue here, g810

**Comment by NM1r** [comment]
Same here, G810

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by NM1r** [comment]
At least it doesn't crash anymore.

**Comment by NM1r** [comment]
Good news, everything works with the official version now.
