### ISSUE TITLE
[BUG] CMD window open occasionaly

### ISSUE THREAD

**Issue by ZeTioZ** [SpoinkyNL/Artemis#366]
Hello, I've a problem, when Artemis is running, sometime a cmd appear for like 1 second and it's realy annoying when I play a game because it make a windows back :/ Could you fix it ? Or tell me how I could fix it ? Thanks in advance.

**Comment by Supermuskox** [comment]
Not a problem with Artemis. For more details see this Reddit thread: https://nl.reddit.com/r/windows/comments/6dn6k4/command_prompt_popping_up_and_disappearing/

**Comment by ZeTioZ** [comment]
Oh yeah thank you, I that the moment when I installed Artemis and this bug was just a coincidence, so thank you ^^

**Comment by SpoinkyNL** [comment]
Noticed the same issue at work but as @Supermuskox pointed out it's an Office issue.
