### ISSUE TITLE
[Request] Game Support: Team Fortress 2

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#367]
Seeing as Artemis already supports Counter Strike: Global Offensive, I thought it wouldn't be too difficult to implement Team Fortress 2 as it uses the same engine, which is of course Valve's source engine. I believe that a similar layout like cs:go can be used, with perhaps options to show medic's Übercharge, the spy's cloak or the engineer's metal.

Tell me what you think of the suggestion and if it's actually doable.

**Comment by SpoinkyNL** [comment]
Hey, the way it works with CS:GO is that CS supports sending whatever is going on ingame to different programs using something they call [game state integration](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration).

Unfortunately TF:2 doesn't have such a thing even though it's both Source Engine :(
