### ISSUE TITLE
Ripple Color & Ingame effect at the same time?

### ISSUE THREAD

**Issue by lavalle00** [SpoinkyNL/Artemis#37]
A good enhancement would be to allow the ingame effect like RL boost, and also allow type ripple(wave). Or, show spectrogram(volume indicator), as the *height* of the boost meter rect?

**Comment by SpoinkyNL** [comment]
Hello, you can now configure a profile that shows your boost amount on, per example, Esc to Pause Break and add a background layer showing a color wave. 

Mixing the regular effects such as audio visualization and type waves isn't something that's planned right now.
