### ISSUE TITLE
New Hero isn't updated for Overwatch profile.

### ISSUE THREAD

**Issue by andi1up** [SpoinkyNL/Artemis#370]
Can't seem to add Orisa as one of the characters since she doesn't exist.

**Comment by TylerJaacks** [comment]
I added a pull request for this issue.

**Comment by TylerJaacks** [comment]
I added Doomfist and Orisa in my new pull request. https://github.com/SpoinkyNL/Artemis/pull/383

**Comment by SpoinkyNL** [comment]
Released, thanks for the feedback and PR!

Also, the Overwatch profiles should no longer need adjustments when a new hero is added, it's LUA based now :)
