### ISSUE TITLE
Discord Support?

### ISSUE THREAD

**Issue by therimmer96** [SpoinkyNL/Artemis#371]
https://twitter.com/logitechg/status/876934012161241089

**Comment by SpoinkyNL** [comment]
Hi, should be fairly easy.
This will be useful for me later so lemme drop this link here: https://discordapp.com/developers/docs/topics/rpc

**Comment by Doctor-Dank** [comment]
This would be amazing, if only so you can keep track of your mute/unmute status on your keyboard instead of having to alt+tab to check.

**Comment by SpoinkyNL** [comment]
I applied for the private beta of the API but they replied saying they weren't looking for new testers, unfortunately :c
