### ISSUE TITLE
Slider for the GUI

### ISSUE THREAD

**Issue by Cr4xy** [SpoinkyNL/Artemis#372]
The title says it all :D

Thanks and keep it up! :+1:

**Comment by rakosi2** [comment]
Can you explain further. Where would you like the slider to be added.

If you are talking about colors sliding across the keyboard then you can find it under Animations in the layer's properties.

**Comment by DarthAffe** [comment]
I think what he wants is a slider for the [lua-gui](https://github.com/SpoinkyNL/Artemis/wiki/gui).

**Comment by SpoinkyNL** [comment]
Hey, should be easy. I'll look into it next week when my internship is finally finished and my summer holiday starts. 

So much free time soon, can't wait

**Comment by TylerJaacks** [comment]
I have started the initial implementation. Maybe @SpoinkyNL could add the event handlers to LuaSlider.cs. I will submit a pull request for the Slider when my other pull request is accepted or denied to avoid conflicts.

**Comment by SpoinkyNL** [comment]
Released, thanks for the feedback and PR!
