### ISSUE TITLE
[Request] Game Support: ARMA 3

### ISSUE THREAD

**Issue by PandLantis** [SpoinkyNL/Artemis#373]
With a vast and well documented source code for modelers, this might prove to be an easy integration. The features that would be fun and immersive to have would be blinking indicators for weapon selection and switching colors for fire-mode. Feedback on the mouse for firing, with a red or orange flare and entire profile switching when you are either flying, driving or ground pounding.

**Comment by rakosi2** [comment]
https://forums.bistudio.com/forums/topic/201698-does-arma-3-have-an-api/

Quickly looking at google, I see that both the server and client would need a script.
