### ISSUE TITLE
[Request] Add support for Rainbow Six Siege

### ISSUE THREAD

**Issue by tyrel505** [SpoinkyNL/Artemis#375]
I would love to see a keyboard effect for the game Rainbow Six Siege. Maybe similar to CSGO. Anything would work honestly. Just don't want a plain keyboard while playing. Thanks again for the already supported games. They look great and I use them all the time.

**Comment by TheDjEzio** [comment]
I also want support for Tom Clancy's Rainbow Six Siege!

**Comment by SpoinkyNL** [comment]
There's currently no way to know what's happening in-game in Rainbow Six Siege :(

**Comment by jakobbouchard** [comment]
I'm not too sure what this api does, but maybe that can help?https://github.com/billy-yoyo/RainbowSixSiege-Python-API
