### ISSUE TITLE
[Request] Support for the Masterkeys Pro M

### ISSUE THREAD

**Issue by ldumancas** [SpoinkyNL/Artemis#376]
Hello, are there any plans to add support for the Masterkeys Pro M RGB? Thanks

**Comment by rakosi2** [comment]
The URL to the SDK

http://makerhub.coolermaster.com/custom-lighting/

**Comment by StachePL** [comment]
Merged into master today. Hopefully will go live with next build, or you can compile on your own right now :)

**Comment by SpoinkyNL** [comment]
Released, thanks for the feedback and PR!

**Comment by StachePL** [comment]
Sweet!
@SpoinkyNL I'm not gonna make a pr just for that, but you can add Masterkeys Pro M to Readme.md list. Totally forgot about that. Sorry!
