### ISSUE TITLE
Some keys not lighting up. Razer mouse not detected

### ISSUE THREAD

**Issue by Apicedda** [SpoinkyNL/Artemis#377]
So i got a Masterkeys pro L, everything was looking good then i noticed that some keys were not lighting up. picture: imgur.com/Yd8v2Lp ( they works fine without the software ofc)
Another thing is, i got a deathadder chroma and was hoping it would have been affected by this software too but it doesn't. It is not showing up here if it means something: imgur.com/0o4cL9r ( i have the razer sdk service running and chroma apps enabled.
Thanks for your help ;)

**Comment by swichers** [comment]
The keyboard thing is a known-issue due to the CM SDK. The upcoming 1.11 release may have a fix for it.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by Apicedda** [comment]
keyboard issue seems to be fixed. The deathadder thing looks the same, i'm not even sure it is an issue or it's just not implemented in the application
