### ISSUE TITLE
I don't understand why Artemis won't run for me.

### ISSUE THREAD

**Issue by GaRinaN** [SpoinkyNL/Artemis#378]
Just trying to get this setup before my G810 arrives on Tuesday. I have downloaded it and tried to run it but it never seems to work. Is it its own separate program because it always opens only in Visual Studio and without Visual Studio it literally won't open. I am really confused on how to get this working, and any help would be much appreciated.

**Comment by Mrwebente** [comment]
it seems like you downloaded the wrong files! it needs to be an executable file try downloading just the setup.exe from this link https://github.com/SpoinkyNL/Artemis/releases

**Comment by GaRinaN** [comment]
Ok I actually feel like a Grade A idiot. Thanks for the help!

**Comment by TylerCode** [comment]
@SpoinkyNL This issue can be closed.
