### ISSUE TITLE
Artemis won't start for me. :/

### ISSUE THREAD

**Issue by DieWeiseEule** [SpoinkyNL/Artemis#379]
Hi

Just wanted to try Artemis.
Downloaded the setup.exe from here: https://github.com/SpoinkyNL/Artemis/releases

The setup generated a desktop icon, but clicking this one does nothing.
Windows UAC comes up, which I grant access, but that's it.

I also went to C:\Users\...\AppData\Local\Artemis\app-1.10.0.0\ and tried to start Artemis.exe there, but it's the same.

Anything I am missing here?
I have Windows 10 Pro 64bit with the latest updates installed.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?

You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by jakobbouchard** [comment]
I have the same issue right now after upgrading from 1.10.0.0
It's weird because 1.10 worked. Is there any Registry keys maybe?

**Comment by jakobbouchard** [comment]
Well I fixed it by deleting the settings in the Documents folder!

**Comment by TudorBlue** [comment]
Cant get Artemis to install. My ps3 just restarts. Help, Im on 4.82 and cobra is enabled
