### ISSUE TITLE
Type effect wave freeze 

### ISSUE THREAD

**Issue by frenchname247** [SpoinkyNL/Artemis#38]
Just started up windows and opened up Artemis. Pressed a key to see if the effects work, yes they did but after every keystroke the wave would freeze and not end. Restarted Artemis and it started to work again. Keyboard is Logitech G810
![img_1701](https://cloud.githubusercontent.com/assets/17438568/13274583/5c633042-da7a-11e5-9e78-3c43a60b98ab.JPG)

**Comment by JewsOfHazard** [comment]
The G810 is not officially supported at the moment but we may add it in the future.

**Comment by frenchname247** [comment]
I know its not officially supported, just having fun testing the software, all the effects work. Its just a few bugs that's all

**Comment by SpoinkyNL** [comment]
Stuff like this should atleast be giving an error message. I'l look into it.

Also glad it seems to work on the G810 :)

**Comment by SpoinkyNL** [comment]
Hello, could you remove all traces of Artemis and try with the latest setup?

**Comment by JewsOfHazard** [comment]
bump

**Comment by frenchname247** [comment]
Hey G810 guy here, so far all features are working. The problems I notice with v1.0.2 is that when Artemis is set to start up with windows, it doesn't apply my selected effect right away when windows is started and my keyboard is detected. I have to first close it after my keyboard is detected and then relaunch it. Another issue I have is that when Artemis is opened at startup my effect settings aren't saved, it reverts to default effect settings.

**Comment by JewsOfHazard** [comment]
That's interesting we had another user with the saving issue. I doubt it is Logitech related but maybe something with loading the settings? We need to fix it for sure.

**Comment by SpoinkyNL** [comment]
Thanks for reporting back, that seems related to #58, I'll see what I can do :)
