### ISSUE TITLE
Last Windows 10 update - CoreAudioAPIException and log file size

### ISSUE THREAD

**Issue by SeiKen5** [SpoinkyNL/Artemis#384]
Hi,

two or three days ago, my computer got upgraded to the last Windows 10 update (1703 ?).

My keyboard artemis profile stopped working (keyboard reverted back to my Logitech G810 saved settings).
Alongside, my free disk space on my C: decreased dramatically.

Those two things seem to be related:
  - an error appeared in the logs, constantly, linked to an error in audio capture (had to reinstall my audio driver; recently deactivated the volume layer causing that and everything returned to normal):
_2017-08-06 19:05:37.7635|WARN|Artemis.Managers.AudioCaptureManager|Failed to start WASAPI audio capture CSCore.CoreAudioAPI.CoreAudioAPIException (0x88890004): IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".
   à CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   à CSCore.SoundIn.WasapiCapture.InitializeInternal()
   à CSCore.SoundIn.WasapiCapture.Initialize()
   à Artemis.Profiles.Layers.Types.Audio.AudioCapturing.AudioCapture.Start()_

  - the log file size is not limited (I was on the "warn" level): one of them went almost to 10GB for one day (every time Artemis tried to see audio level, I'm guessing).

First issue seems to be related to my driver issue when upgrading (don't know if you can replicate that easily).
Second issue may be fixed by putting a limit on the logfile size per day (clean the earlier issues in it).

Sorry for the lengthy description, keep up the good work.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )
