### ISSUE TITLE
Effects on new notification

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#385]
Inspired by this article: https://tweakers.net/nieuws/128395/steelseries-brengt-toetsenbord-uit-dat-lichteffecten-geeft-bij-discord-bericht.html (it's Dutch but that isn't a problem from spoinky*NL*). Would it be possible to have little flashes in the keyboard on new messages?

**Comment by SpoinkyNL** [comment]
I'd really love to do this, sadly the Discord API that's used for that is in closed beta. I applied for it but they responded saying they aren't accepting any new requests at the moment :(

I'll keep an eye on it though and dig around a bit for alternative methods
