### ISSUE TITLE
F7 F8 and F9 do not light up

### ISSUE THREAD

**Issue by ShelbyJunoGames** [SpoinkyNL/Artemis#386]
I'm using a Pro Keys S and after reinstalls and updates, nothing can get F7 F8 and F9 to light up. I really hate coolermasters software so I am hoping someone knows a fix :(

**Comment by SpoinkyNL** [comment]
Hi!
Looks like they fixed this in their SDK. I'll push an update with the new SDK soon.

**Comment by ShelbyJunoGames** [comment]
Amazing! Thank you =)
