### ISSUE TITLE
Corsair Glaive side lights are not controlled

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#387]
I just got the corsair Glaive and I noticed of the bat that side leds are not controlled. The side leds maintains what I set in the CUE and the logo led and front led are from Artemis. I would love to be able to set the zones individually like what you can do in CUE, I would be able to customize more.

**Comment by SpoinkyNL** [comment]
Hey, I'm not sure weather the side LEDs can be controlled. With the Corsair Scimitar the big side LED is used by CUE to show what profile you're on
![image](https://user-images.githubusercontent.com/8858506/30263980-4d9edac8-96d7-11e7-805f-964e6d24a7fe.png)

This cannot be changed through the SDK. Same might be true for the Glaive, I'll be able to tell for sure when I get my hands one one though.

**Comment by rakosi2** [comment]
When Artemis is off the glaive has three light zones that are controlled by CUE. When Artemis gets enabled. The front and logo light are controlled by Artemis and the side led is maintains the CUE profile. It is not a status light as it is programmable like the other zones.

**Comment by rakosi2** [comment]
So I looked at corsair's SDK and glaive is still not a supported device.

**Comment by SpoinkyNL** [comment]
I'll leave this issue open until the Glaive is supported

**Comment by SpoinkyNL** [comment]
I've got a fix for this ready in CUE.NET (The C# SDK wrapper Artemis uses) but it's not a nice solution so we're waiting on a reply from Corsair

**Comment by rakosi2** [comment]
Corsair has pushed a new CUE SDK and in the docs says that the GLAIVE RGB and the ST100RGB

**Comment by HazardDev** [comment]
Can you provide a link to that? All I see is [this Corsair forum post](http://forum.corsair.com/v3/showthread.php?t=156813&page=2) in 2015.

**Comment by HazardDev** [comment]
Also, as an owner of a scimitar, @SpoinkyNL I can tell you that https://github.com/SpoinkyNL/Artemis/issues/387#issuecomment-328448464 is not controllable, even by CUE itself.

**Comment by rakosi2** [comment]
@HazardDev http://www.corsair.com/en-us/downloads#download_form_6 search for sdk

**Comment by DarthAffe** [comment]
@rakosi2 We already got hands on a working sdk yesterday but there is some - lets call it design-flaw - with id usages. That's why SpoinkyNL was waiting for some clarification. But i see the official release of the new version as a bad sign ...

**Comment by HazardDev** [comment]
@SpoinkyNL @DarthAffe If we're at the point where the `hack` used in [CUE.NET](https://github.com/DarthAffe/CUE.NET) can't be changed due to the Corsair API, should we consider this "done"?

**Comment by DarthAffe** [comment]
I'd prefer to wait a bit longer for an answer - maybe we're just missing something and there isn't even an issue.

**Comment by SpoinkyNL** [comment]
The latest release also includes the new version of CUE.NET that contains this fix (with hack and all..!)
