### ISSUE TITLE
[Request] Allow Corsair keyboard to accept RGB signals from games meant for Logitech RGB keyboards

### ISSUE THREAD

**Issue by Isaiahfeldt** [SpoinkyNL/Artemis#39]
Some games like GTA 5 and The Divison Beta have 3rd party support for logitech RGB keyboards, is there anyway to convert that into something a Corsair keyboard can read?

**Comment by SpoinkyNL** [comment]
https://github.com/VRocker/LogiLed2Corsair offers this. When we've fixed our current issues and are ready for new features we can consider asking that dev for some help :)

**Comment by SpoinkyNL** [comment]
We do this for The Division and Overwatch
