### ISSUE TITLE
Keyboard effects laggy

### ISSUE THREAD

**Issue by JackSLR783** [SpoinkyNL/Artemis#390]
Whenever i use the default audio visualizer of key ripple, it will often freeze mid-animation. Any fix?

**Comment by ShelbyJunoGames** [comment]
Yeah happens for me too, also the F7 F8 and F9 keys do not light up on my pro keys S. Been using Aurora keyboard software for now but plan on swapping back once fixed =)

**Comment by SpoinkyNL** [comment]
@JackSLR783 which keyboard are you using? 
@ShelbyJunoGames I've got a fix for that ready, been working on World of Warcraft support which took a bit longer than expected, but I'll push the update asap

**Comment by SpoinkyNL** [comment]
Think I can reproduce it as well, you're seeing total freezes every second or so?

**Comment by JackSLR783** [comment]
Im using a G910 Orion Spectrum, and yes, it freezes every second

**Comment by H36615** [comment]
@SpoinkyNL Same here. Is normal for a second, then freeze for a second, stays looping like that. Otherwise great software tho :)

**Comment by Rechinan** [comment]
@SpoinkyNL I get the same freeze on the logitech k70 rgb, its on any general profile tbh

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by Rechinan** [comment]
Seems to have fixed it, using the audio visualizer and ambient modes fine. thanks

**Comment by H36615** [comment]
Works here too! been waiting for this :)
