### ISSUE TITLE
A place to share custom profiles?

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#391]
Hey everyone, 

So I had this bright idea, which is a place where Artemis users can share their custom profiles. Not sure if this is the right place to put this post, but perhaps there is a way to share custom profiles. If anyone has some further ideas for this, feel free to post them here.

**Comment by SpoinkyNL** [comment]
Hey, making a website where they can be shared is definitely something I'd like to do at some point.
