### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by aatroxfusiion** [SpoinkyNL/Artemis#392]
When running the setup.exe, I get a window telling me installation failed

**Comment by ch3mox** [comment]
i would like to recommend downloading

**Comment by ch3mox** [comment]
Try to download and install: https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679

Maybe some needed libraries are missing.

**Comment by SpoinkyNL** [comment]
Hey, please try the latest release. If it's still an issue with that version you can reopen this :)

Note: If you're doing a clean install, just download [artemis-setup-1.11.0.0.msi](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi).
