### ISSUE TITLE
[Logitech | G910] can't be enabled!

### ISSUE THREAD

**Issue by ch3mox** [SpoinkyNL/Artemis#393]
Hey there, my G910 can't be enabled, Artemis put out an Error Message:
![ErrorMsg](http://abload.de/img/errorftkqh.jpg)

I got the latest Logitech Gaming Software, also i have the latest VCRedist Update.
Reinstall of LGS doesn't fix it.

Please help, so i can test your Software ;)
unfortunately i need to use Aurora until you fixed it.

regards,
Andi

**Comment by traveler0815** [comment]
I had the same problem
1.I have to unmount the Keyboard
2. Logitech Game Software unistalized
3. Restart Pc
4.install Logitech Game Software
5. Plug in the keyboard
works for me

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by ch3mox** [comment]
Problem solved itself, i don't know how :D

**Comment by Panadur** [comment]
I have the same problem. Logitech software Version is 
![grafik](https://user-images.githubusercontent.com/4924073/33504848-698f28b2-d6e9-11e7-8e8a-9173af3e9bfb.png)
I installed artemis today the first time and already have the version you linked above.

**Comment by SpoinkyNL** [comment]
Thanks for the update guys, I'll close this now :)
