### ISSUE TITLE
Stuttering on K70 Rapidfire RGB w/ Audio Visualization 2.0

### ISSUE THREAD

**Issue by SKILLEDxKILLAH** [SpoinkyNL/Artemis#395]
I recently installed Artemis and chose the Audio Visualization 2.0 and it stutters ever 3 or 4 seconds. Like it stops and starts back up again.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )
