### ISSUE TITLE
Additional CS:GO States

### ISSUE THREAD

**Issue by BD3457** [SpoinkyNL/Artemis#396]
Missing some useful conditions including:

Round Conditions
- bomb (planted, defused, exploded) and a way to set up the timer/flashing (35 seconds with 10 second warning flash)
- win_team (t, ct) (per-round wins rather than total score)

Pastebin I found with a list of several game states:
https://pastebin.com/FLATE957

**Comment by SpoinkyNL** [comment]
Hello, the bomb one I believe is taken out to prevent abuse, I'll have a look at the win_team one though!

**Comment by SpoinkyNL** [comment]
I've added it to the latest release, thanks for the feedback!
