### ISSUE TITLE
[NOT AN ISSUE] Solution found for "fixing" Admin Request on Windows Boot - Guide

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#397]
So I was looking into a way of fixing the annoying UAC Admin Request when Windows starts without disabling UAC entirely, and there is a fix, and it is quite simple. For those of you interested in "fixing" this, just follow this short guide.

Step 1:
Install Artemis (obviously), then find the Shortcut it made and go into Properties. Then go into the "Shortcut" Tab, and find the path to the "Update.exe", which should look something like this:
C:\Users\ (Username Here)\AppData\Local\Artemis\Update.exe
You can find that in the "Target" box. Behind that should be the following:
--processStart "Artemis.exe"
This information is relevant for Step 4

Step 2: Open the Task Scheduler, and Create a New Task (Not an Easy Task).
Give the Task you created a name like "NoUAC Artemis" or so.
In the Description it doesn't matter what is written there, just skip it if it isn't important to you.
Leave the "Security Options" as they are BESIDES (and this is IMPORTANT) the box that is named "Run with Highest Privileges". You **_NEED_** to check that box _ON_.
Then put "Configure for:" to Windows 10.

Step 3: Go to the "Trigger" Tab in the top of the Task Creation Window.
Here you click "New", then when it asks you for a Type, choose "At Login".
Down below, check the box for "Delay by:" and choose 30 seconds, but replace the 30 with 15 manually (no shorter than 15 otherwise Artemis will fail to start due to the delayed LGS startup).
Then click OK.

Step 4: Go to the "Actions" Tab in the top of the Task Creation Window.
Here you also click "New", then you leave the Default "Start Program" option on.
Here comes the important part from Step 1.
In the "Program/Script:" box, add the "C:\Users\ (Username Here)\AppData\Local\Artemis\Update.exe",
and in the "Arguments (optional):" box, add the "--processStart "Artemis.exe"" line (both without the "", BESIDE the last "Artemis.exe" part, that _NEEDS_ the "" in it, but not the " after the "Artemis.exe"->"<-).
You can leave the last box empty, but if you want you can copy the text from the "Launch In" box into the last box, but it isn't necessary.
Then click OK.

Step 5: Go to the "Conditions" Tab in the top of the Task Creation Window.
Disable the first checkbox of the "Energy" section which says something about the Task only running when the PC is plugged in to Charge (only useful for Laptops, but disable it nonetheless to avoid Task Running Failure).

Step 6: Go to the last Tab, which is the "Settings" Tab, and make sure the first two checkboxes are _ENABLED_. Then make sure that the 4th checkbox is _DISABLED_.

Alright, that should be it, happy starting your PC without an UAC prompt :)

**Comment by SpoinkyNL** [comment]
Hi, that's a neat solution - I'll build this in at some point

**Comment by SpoinkyNL** [comment]
I've replaced the old autorun method with this one and it should work right away on the next update. 
You'll have to replace the task you made manually though, else two will run alongside each other :p

Thanks a lot!
