### ISSUE TITLE
ERROR: When Starting Artemis

### ISSUE THREAD

**Issue by 88Gamer88** [SpoinkyNL/Artemis#398]
Hello,

I get the next error when i start the program.
And after that it closes automatically.

Hopefully the logs will help you for a fix.

Using: 

Cosair K95 Platuim
Windows 10 64 Bit Creator update

```
An unexpected error occurred in Artemis.

Het doel van een aanroep heeft een uitzondering veroorzaakt.

Het doel van een aanroep heeft een uitzondering veroorzaakt.

De objectverwijzing is niet op een exemplaar van een object ingesteld.
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Het doel van een aanroep heeft een uitzondering veroorzaakt.

Stack Trace:
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   bij Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   bij System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   bij System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bij System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bij System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.Reflection.TargetInvocationException

Message:
Het doel van een aanroep heeft een uitzondering veroorzaakt.

Stack Trace:
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij Ninject.Infrastructure.Language.ExtensionsForIEnumerable.ToListSlow(IEnumerable series, Type elementType)
   bij System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   bij Ninject.Activation.Context.ResolveInternal(Object scope)
   bij Ninject.Activation.Context.Resolve()
   bij System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bij System.Linq.Enumerable.<CastIterator>d__95`1.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bij Artemis.ViewModels.ShellViewModel.ActivateViews()
   bij Artemis.ViewModels.ShellViewModel.ShowWindow()

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828
____________________________________________________
System.NullReferenceException

Message:
De objectverwijzing is niet op een exemplaar van een object ingesteld.

Stack Trace:
   bij Artemis.Modules.Games.RocketLeague.RocketLeagueViewModel.SetVersionText()
   bij DynamicInjector0007d1ebf45a4bd8a185e8919fe3bb06(Object[] )
   bij Ninject.Activation.Context.ResolveInternal(Object scope)
   bij Ninject.Activation.Context.Resolve()
   bij System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   bij System.Linq.Enumerable.<CastIterator>d__95`1.MoveNext()
   bij System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bij System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

TargetSite:
Void SetVersionText()

Source:
Artemis

HResult:
-2147467261
```

**Comment by SpoinkyNL** [comment]
Hi, seems an easy fix that just requires updating the Rocket League module. I'll get on it over the weekend

**Comment by 88Gamer88** [comment]
Hi, I was wondering if you have had time to patch the problem with Rocket Leugue ? 
Have deinstall Rocket leugue and remove Artemis, and re-install Artemis but the error about Rocket Leugue keeps comming up.

**Comment by SpoinkyNL** [comment]
Hi, sorry I fixed this issue but I'm having some issues releasing the new version (I had it ready last Monday :\)

The 3rd party auto-updater Artemis uses is giving false positives on virus scanners so I'm working on implementing an alternative but it's a hassle

**Comment by 88Gamer88** [comment]
Noticed that with Bitdefender "Malware reports"

Is it possible to test it with a manual installation?

**Comment by SpoinkyNL** [comment]
Sure, feel free to give this a shot:
https://www.dropbox.com/s/13gagdtax7062ur/artemis-1110-beta.zip?dl=0

Rocket League doesn't work but it also won't crash Artemis. It might freeze on startup, that's something I've been trying to figure out. In that case just restart it until it works :\

**Comment by 88Gamer88** [comment]
It starts now :), only Bitdefender and Windows defender all give Malware notification. Only excluding Quarantine does not make sense.

It's only crashing on WoW.

Mabye you can upload also the WoW profile ?

System.IO.FileNotFoundException

Message:
Kan bestand of assembly PcapDotNet.Core.dll of een van de afhankelijkheden hiervan niet laden. Kan opgegeven module niet vinden.

Stack Trace:
   bij Artemis.Modules.Games.WoW.WowPacketScanner.Stop()
   bij Artemis.Modules.Games.WoW.WoWModel.Dispose()
   bij Artemis.Managers.ModuleManager.ChangeActiveModule(ModuleModel moduleModel, LoopManager loopManager, Boolean storeAsLast)

FileName:
PcapDotNet.Core.dll

TargetSite:
Void Stop()

Source:
Artemis

**Comment by SpoinkyNL** [comment]
That file was removed by your virus scanner then, try re-extracting the zip

**Comment by SpoinkyNL** [comment]
UT I'll have to look at, shit's breaking left and right that's why I'm so hesitant to support new games

**Comment by 88Gamer88** [comment]
I believe that, It's a never-ending story :(.

Have found the profile in the "corsair-k95-rgb"folder only when i load it the program crash.
i'm using the K95 platinum.

**Comment by 88Gamer88** [comment]
Sometimes it will crash with the follow log:

System.Reflection.TargetInvocationException

Message:
Het doel van een aanroep heeft een uitzondering veroorzaakt.

Stack Trace:
   bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bij Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
   bij Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
   bij System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
   bij System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bij System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bij System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)

Source:
mscorlib

HResult:
-2146232828

**Comment by SpoinkyNL** [comment]
Hey, please try the latest release. It should auto-update if you restart Artemis twice or so, or do a manual update

Note: If you're doing a clean install, uninstall 1.10 and just download [artemis-setup-1.11.0.0.msi](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi).
