### ISSUE TITLE
Add G keys

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#403]
Can you add support for the G or M keys on Corsair keyboards like my K95 with the SDK's CorsairRegisterKeypressCallback function.

**Comment by HazardDev** [comment]
What exact functionality are you looking for? You should be able to color keys on keypress. Are you talking about the LUA functions in Artemis?

**Comment by rakosi2** [comment]
I am able to color the G keys using ripple with a key next to the G keys like with tab, but nothing happens when I click on the G keys themselves.

**Comment by SpoinkyNL** [comment]
That's an interesting new feature of the CUE SDK, I'll look into it, think @DarthAffe will want to add it to CUE. NET

**Comment by rakosi2** [comment]
OK it looks like @DarthAffe has added it to his CUE.NET

**Comment by Boscop** [comment]
Which version of the CUE SDK has `CorsairRegisterKeypressCallback()`?

I'm still on CUE Engine V1 because V2 used way too much CPU when I tested it (in like December).
Does CUE Engine V1.xx also offer `CorsairRegisterKeypressCallback()` when talking to it with the recent SDK?
