### ISSUE TITLE
[Request] Redragon support

### ISSUE THREAD

**Issue by Izitto** [SpoinkyNL/Artemis#404]
I have a redragon yama keyboard and I'm wondering if it's possible to add support for this keyboard. I believe it is possible, but I'm a beginner programmer at best, so I don't really know how to do it myself. Would appreciate it if you could at least let me know if you plan to add support or not

**Comment by rakosi2** [comment]
From what I see is that the lighting is controlled by function keys and not with software so there is no API that Artemis can hook into.

**Comment by SpoinkyNL** [comment]
As @rakosi2 said without the proper SDK it cannot be done.
