### ISSUE TITLE
[Problem] Razer Blackidow Chroma V2

### ISSUE THREAD

**Issue by SebasSebasIII** [SpoinkyNL/Artemis#406]
I'm trying to connect a Razer BlackWidow Chroma V2 to Artemis, but it says that it couldn't connect. Is there a way to solve this problem or SpoinkyNL should add the BlackWidow V2 support?

**Comment by SpoinkyNL** [comment]
Hi, could you try this with the latest version of Artemis? It includes an updated Razer SDK. If it still doesn't work it will probably require some further updating.

**Comment by SleepyAsh16** [comment]
I have the Blackwidow v2 too. It's not working with the 1.11 version of Artemis :/

**Comment by SebasSebasIII** [comment]
Thank you SpoinkyNL to reply, but I just downloaded the 1.11 version and it doesn't work

**Comment by Eldoradobull** [comment]
cant get my razer black widow x chroma to work too
