### ISSUE TITLE
logitech g910 keys mixed up

### ISSUE THREAD

**Issue by aureshion** [SpoinkyNL/Artemis#408]
as of today (first time I noticed) it seems that the keys are somewhat mixed up. the most obvious ones is that the "qwerty" row is somehow mapped to the row above, the keys also seem to have been moved to the left. for example assigning a collor to the 1 key will show up on W on the keyboard whereas assigning to W wont show on the keyboard at all. if I attempt to color one the G keys it will light both the G key and one of the F keys. the G6 and the F2 key for example.
All my drivers are up to date.

**Comment by SpoinkyNL** [comment]
Hi there, if you've got any version of Artemis installed could you uninstall it and try it with the latest version?
You can find the download link [over here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.0.0/artemis-setup-1.11.0.0.msi). Please let me know how it goes, thanks!

(If you chose not to reply, I'll close this issue in 7 days to clean up a bit :) )

**Comment by aureshion** [comment]
latest version version also has this problem for me, is there a way i could send you a video showing you my issue? it's rather hard to explain. that is, unless you already understood my explanation.

I tend to make my sentences unnecessarily long and complicated :(

**Comment by Natsu13** [comment]
![photo_2017-11-30_14-29-14](https://user-images.githubusercontent.com/3385155/33433184-e9c0ad22-d5da-11e7-978a-e3d1ccf5b649.jpg)
![bez nazvu](https://user-images.githubusercontent.com/3385155/33433189-ed738a84-d5da-11e7-9090-5c9f259a0513.png)

Hi i have the same issue how you can see on images. The key light is one row down :/

**Comment by aureshion** [comment]
yes! that is exactly what is happening. thank you.

**Comment by Natsu13** [comment]
New update is here and he don't do anything about this :/ that's bad

**Comment by SpoinkyNL** [comment]
@Natsu13 sorry, my time is limited, I'll try to fix it soon. Feel free to make a pull request :)

**Comment by Natsu13** [comment]
@SpoinkyNL sorry. i don't mean you is bad i only expect some message like ok for i know you know about it. Thanks.

**Comment by TeRRa4** [comment]
Hi, not trying to rush, just wondering if there's an ETA for a fix. It's not deal-breaking for me, as I've found a workaround for my needs, but thought I'd ask anyway. 

Really like the software so thanks so much for putting your time into this! 😀

**Comment by aureshion** [comment]
hiya! just dropping in. I was wondering if you have come around to fixing this yet, no rush. if you need any logs or stuff from our side, just ask! :D

**Comment by SpoinkyNL** [comment]
Hi sorry for the delay, I went through the G910 code (fun fact: That code has been in place for 232 days :p) and fixed it.

I'll roll out an update today with some other fixes as well

**Comment by aureshion** [comment]
awesome, thanks for the response. I'll let you know if it worked!

**Comment by aureshion** [comment]
just installed it. looks like it works now. thanks again!
