### ISSUE TITLE
[Request] Add support for Game: Factorio

### ISSUE THREAD

**Issue by rakosi2** [SpoinkyNL/Artemis#409]
Factorio was just updated to experimental 0.15.38 and it came with Razer Chroma support built in. You can see the developer talking about it at the bottom of this page https://www.factorio.com/blog/post/fff-218

**Comment by HazardDev** [comment]
I started working on a factorio data model and interface, but I stopped after school got a bit more strenuous. I'll see about finishing it up. I need a C# - Lua FFI.

**Comment by HazardDev** [comment]
Fat-fingered button sorry

**Comment by SpoinkyNL** [comment]
Ok that sounds good, I don't know anything about the game myself but perhaps you can use their [write_file](http://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.write_file) function and monitor the file in your Artemis module.

Let me know how it goes ^^

**Comment by HazardDev** [comment]
I want to update real quick to let people know I'm not ignoring this, I've just been trying to finish up my school quarter. I'll be working on this starting either this weekend (if I can get a VM working on my laptop) or early January when I'm back at my apartment with my desktop.

**Comment by HazardDev** [comment]
@rakosi2 I wanted to comment and let you know that this has been put on hold while development of v2 is in-progress. I'll let you know if anything changes.

**Comment by Happyrobot33** [comment]
any update on this?
Factorio has built in chroma support so if you can latch onto that then you don't need to do any additional data work
