### ISSUE TITLE
[Request] Add keyboard shortcuts to / automatically toggle audio visualizer when music is playing

### ISSUE THREAD

**Issue by NarwallMan** [SpoinkyNL/Artemis#41]
It would be useful so that we don't have to keep opening the application to turn it on when we listen to music.

**Comment by SpoinkyNL** [comment]
Hey, thanks for the suggestion. 

For now, you can also toggle the application by right-clicking the tray icon and selecting Enable / Disable Artemis

**Comment by SpoinkyNL** [comment]
With the keybind system this is possible nowadays
