### ISSUE TITLE
[REQUEST] Add Support to HyperX Mars RGB Keyboard

### ISSUE THREAD

**Issue by RodrigoWantuk** [SpoinkyNL/Artemis#410]
Is there a possibility to provide support for the new HyperX Mars RGB keyboard? Currently there's only this native Genesis software (https://www.hyperxgaming.com/genesis) that is very limited in terms of light effects and none integration with anything.

**Comment by rakosi2** [comment]
Artemis works by using Public SDK provided by Keyboard software. I did not install the program but it did not find an SDK included with the software nor was I able to find one on the internet. It seems that you can only access the [website in Brazil](https://www.hyperxgaming.com/us/keyboards/mars-rgb-mechanical-gaming-keyboard#v-overlay) so I had to use a vpn. I also found that the Genesis program came with the annoying song that is in the [demo video](https://www.youtube.com/watch?v=egLDC8tnBD0) so I hope that the software doesn't always play it.

**Comment by SpoinkyNL** [comment]
This can't be done without an SDK unfortunately

**Comment by azumukupoe** [comment]
> 
> 
> This can't be done without an SDK unfortunately

https://gitlab.com/CalcProgrammer1/OpenRGB
