### ISSUE TITLE
Setup Keyboard when select  WoW and a error when closing the program.

### ISSUE THREAD

**Issue by 88Gamer88** [SpoinkyNL/Artemis#412]
Hello,

I have a problem when i will select WoW.
Have setup the keyboard in the settings menu.

Have tried the WoW folder from the corsair-k95-rgb with the corsair-k95-rgb-platinum keyboard but it's  not working.

 When you have time is it possible to make a WoW module for the corsair-k95-rgb-platinum ?

![art1](https://user-images.githubusercontent.com/21025243/33452660-3c024586-d613-11e7-9aed-2226e98bc822.JPG)

The next error comes when is crash or when close Artemis.

> Kan bestand of assembly PcapDotNet.Core.dll of een van de afhankelijkheden hiervan niet laden. Kan opgegeven module niet vinden.
> ____________________________________________________
> System.Reflection.TargetInvocationException
> 
> Message:
> Het doel van een aanroep heeft een uitzondering veroorzaakt.
> 
> Stack Trace:
>    bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bij Caliburn.Micro.ActionMessage.<>c.<.cctor>b__33_0(ActionExecutionContext context)
>    bij Caliburn.Micro.ActionMessage.Invoke(Object eventArgs)
>    bij System.Windows.Interactivity.TriggerBase.InvokeActions(Object parameter)
>    bij System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bij System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bij System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
>    bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> TargetSite:
> System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
> 
> Source:
> mscorlib
> 
> HResult:
> -2146232828

____________________________________________________

> System.IO.FileNotFoundException
> 
> Message:
> Kan bestand of assembly PcapDotNet.Core.dll of een van de afhankelijkheden hiervan niet laden. Kan opgegeven module niet vinden.
> 
> Stack Trace:
>    bij Artemis.Modules.Games.WoW.WowPacketScanner.Stop()
>    bij Artemis.Modules.Games.WoW.WoWModel.Dispose() in C:\Repos\Artemis\Artemis\Artemis\Modules\Games\WoW\WoWModel.cs:regel 53
>    bij Artemis.Managers.MainManager.Dispose() in C:\Repos\Artemis\Artemis\Artemis\Managers\MainManager.cs:regel 75
>    bij Artemis.ViewModels.ShellViewModel.ExitApplication() in C:\Repos\Artemis\Artemis\Artemis\ViewModels\ShellViewModel.cs:regel 196
> 
> FileName:
> PcapDotNet.Core.dll
> 
> TargetSite:
> Void Stop()
> 
> Source:
> Artemis
> 
> HResult:
> -2147024770

**Comment by SpoinkyNL** [comment]
Hi,

In your error:

```
Kan bestand of assembly PcapDotNet.Core.dll of een van de afhankelijkheden hiervan niet laden. Kan opgegeven module niet vinden.
```

This means that something removed PcapDotNet.Core.dll. Probably a virus scanner? Try whitelisting Artemis's install directory in your antivirus (by default C:\Program Files\Artemis) and reinstalling. That could resolve the DLL being removed.

The WoW module supports any keyboard by the way, you just need to make a profile. There currently is no default profile for WoW because I've not had the time to make one yet.

**Comment by 88Gamer88** [comment]
Hi,

The PcapDotNet.Core.dll file is still in the Artemis folder.
Have replace the file or a new one from the last .zip file without succes.
(File size is 86.5 kB)

Artemis is in Whitelist (Bitdefender)

I think it's something else.

**Comment by SpoinkyNL** [comment]
Odd, I wasn't able to fix this yet but I put out a release anyway (I don't want to put off releases all the time anymore)

I'll investigate further

**Comment by SpoinkyNL** [comment]
It works fine for me right now, I happen to use Bitdefender as well and I've not even whitelisted the C:\Program Files\Artemis directory.

Here is the default profile I'm testing with on my K95 Platinum, should you get it working
[WoW K95 Platinum default.zip](https://github.com/SpoinkyNL/Artemis/files/1527277/WoW.K95.Platinum.default.zip)

**Comment by 88Gamer88** [comment]
Hi,

Have updated Artemis,
And have tried to load the new K95 Platinum file wihtout succes.

The message about the PcapDotNet.Core.dll  keeps coming back.

I think the error is wrong somewhere in the C: / repos link

**Comment by SpoinkyNL** [comment]
I'm trying but I simply cannot reproduce this :\

**Comment by 88Gamer88** [comment]
No problem :)

**Comment by SpoinkyNL** [comment]
You could try making a new folder, whitelisting it in your antivirus and then installing Artemis into that folder, perhaps that'll do the trick.

This is purely down to the DLL missing/access to the DLL being denied which I can only really contribute to antivirus.

**Comment by 88Gamer88** [comment]
Hi,

Have tried a clean install on a other disk but nothing changed.

Have check the log's file about the antivirus program but found nothing.
There are no .dll chenged or removed

**Comment by 88Gamer88** [comment]
Hello,

Artemis have install a addon.
This addon give sometimes a error and a optie from wow for disable of ignore.
I don't know mabye is this a fault why i get the message about PcapDotNet.Core.dll ??

Have tried a lot of thinks, disable Bitdefender fully. install Artemis but without succes.
