### ISSUE TITLE
[Request] Game support: PAYDAY 2

### ISSUE THREAD

**Issue by corndogninja** [SpoinkyNL/Artemis#413]
Payday 2 uses Alienware AlienFX by default, with options for a great deal of effects based on various ingame statuses.

A similar tool, [Aurora](https://github.com/antonpup/Aurora), has support for PAYDAY 2 (albeit glitched at the moment) so it does seem to be possible with non-Alienware keyboards. Would be awesome to see it added to Artemis!

**Comment by SpoinkyNL** [comment]
I had been [working on a module](https://github.com/SpoinkyNL/Artemis/tree/master/Artemis/Artemis/Modules/Games/LightFx) that supports any and all LightFX games (the stuff Alienware uses) and I had it working with Payday 2. I'll see where I left off
