### ISSUE TITLE
(Overwatch) Latest hero not added

### ISSUE THREAD

**Issue by corndogninja** [SpoinkyNL/Artemis#417]
The newest hero, Moira, isn't implemented for Overwatch profiles.

I'm also having some glitches with "Character" conditions not working for a custom OW keyboard profile. I guess this is a result of an outdated characters list in Artemis. If this isn't the case, I'll open a new Issue for the problems I'm having.

**Comment by SpoinkyNL** [comment]
Hi, I'll add Moira when I'm home, I need to run the game to be able to do that.

The character condition could behave a bit unpredictable right now if it cannot determine what character matches with the current color (since Moira is missing) I'll see if I can make that a bit better too.

**Comment by SpoinkyNL** [comment]
Well, currently Moira has the same color as Reaper in the native Razer integration. This means I can't distinguish between the two :/
