### ISSUE TITLE
CS:GO Bomb idea

### ISSUE THREAD

**Issue by TheAmazingTophat** [SpoinkyNL/Artemis#42]
I think it would be cool to use the numbpad on the G910 as the bomb, while its free it stays green and when its planted it flashes red in the same intervals as the bomb does, if you could do that, that would be awesome! better use of the whole keyboard

**Comment by SpoinkyNL** [comment]
This is one of the things that should be possible with the 1.1.0 update, which focuses better configurable effects

**Comment by antonpup** [comment]
I actually have made this for G910 with my own implementation here: https://github.com/antonpup/Logitech-CSGO

**Comment by SpoinkyNL** [comment]
This is included in the latest update. Should you have any problems with it please create a new issue :)
