### ISSUE TITLE
"program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing" error

### ISSUE THREAD

**Issue by p1co** [SpoinkyNL/Artemis#421]
Recently upgraded PC hardware and had to reinstall Windows 8.1. Did not have the following issue on previous Windows setup.

This error occurs every time I try to start the Artemis software. If the advice is to install Microsoft Visual C++ 2015 Redistributable (x64) version 14.0.24215, I get the following error: https://pastebin.com/6vn7x9Dy

Error (and screenshot):
---------------------------
Artemis.exe - System Error
---------------------------
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------

![image](https://user-images.githubusercontent.com/604213/34325081-134f058a-e83c-11e7-82e1-ae260c91e036.png)

**Comment by DarthAffe** [comment]
Installing the [universal c runtime](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) resolved the issue.
