### ISSUE TITLE
Support for RGB fusion

### ISSUE THREAD

**Issue by Supermuskox** [SpoinkyNL/Artemis#423]
Hey everyone!

I have searched through this repository, but could not find any mention of RGB Fusion by Gigabyte. The software has an SDK, which can be found [here](https://www.gigabyte.com/mb/rgb/sdk). I don't know how difficult it is to add this, but I hope it's possible.

**Comment by SpoinkyNL** [comment]
Hi there,

That SDK only supports motherboard lighting and since I don't own a Gigabyte motherboard I can't really implement it. I tried using it with my Gigabyte GTX1080 which has a LED on there but I can't control it through this SDK sadly.

**Comment by Alia5** [comment]
The sdk also supports RGB keyboard on laptops. ;)
I got a shiny new one from work, so maybe I'm willing to give this a shot in a few days :)
