### ISSUE TITLE
Won't install

### ISSUE THREAD

**Issue by Knakendraaier** [SpoinkyNL/Artemis#426]
Artemis won't install. 
No Anti-virus issue.
Please help.

**Comment by rakosi2** [comment]
Make sure that you are downloading from https://github.com/SpoinkyNL/Artemis/releases/tag/1.11.2.0

The .msi is the installer and should walk you through the installation. If it doesn't work then you can manually download the .zip and unzip it somewhere and double click on Artemis.exe.

If you still need help then you can join our chat at https://discordapp.com/invite/S3MVaC9

**Comment by Knakendraaier** [comment]
It worked. But my keyboard is not in the list and there's no software at all.
So i think it is not even possible to get 3rd party software on my keyboard.
Anyway, thanks for your help.
