### ISSUE TITLE
Audio Visual bug when using Spotify

### ISSUE THREAD

**Issue by mariush2** [SpoinkyNL/Artemis#427]
When I turn my spotify to "private session" (i.e. people who follow me can't see what im listening to), the audio visual layer doesn't respond.

**Comment by Bluethefurry** [comment]
this is probably a problem with the Spotify API not providing any informations to what you are listening.

**Comment by SpoinkyNL** [comment]
What @Bluethefurry said is correct, no way to get around this without completely moving away from using the API. Alternative would be to memory read the client which would break spotify support every time spotify updates
