### ISSUE TITLE
Add support for the Drevo Calibur 71/72

### ISSUE THREAD

**Issue by ian1467** [SpoinkyNL/Artemis#429]
The stock software looks nice for these keyboards, and is fully functional... Unless you have a US version. Crashes, breaks the keyboard BIOS, and generally doesn't work well. If you could add support for it, that would be great! 

Relevant links:
https://drive.google.com/drive/folders/16yO6YCokb4eVymSNJhYpl0dT4FW95ch6 -firmware and software
https://www.drevo.net/product/keyboard/calibur -keyboard

**Comment by rakosi2** [comment]
I can't find an SDK that Artemis can use to modify keyboard lighting. The only thing I can find is that someone asked on MassDrop a year ago and got no reply. I also don't like that they are using google drive for a 8mb download and that the install instruction was plug in keyboard and install (literally that's it).

**Comment by ian1467** [comment]
Yeah like I said their software is awful, but I'm requesting that they release an sdk or their source code, or hell, even tie it into CUE!

**Comment by ian1467** [comment]
However, I (being the very novice programmer that I am,) could not make sense of the firmware file. Potentially you could have a look? It's machine code of some kind but I have no clue what it says or what it points to, let alone how it handles input and output

**Comment by rao403** [comment]
Necro. Please make this a thing!

**Comment by LouWii** [comment]
+1 Would love to see that keyboard supported.

**Comment by HazardDev** [comment]
@ian1467 the firmware and software isn't really enough for us to be able to add this keyboard. We'd need some kind of API for us to talk to it. The only alternative is for us to write our own drivers which isn't impossible since we have the firmware but is very time consuming and perhaps out of the scope of this project.

**Comment by nSimonFR** [comment]
Is this the kind of project you are looking for ? https://github.com/FxPape/fdclct

**Comment by arK1LL** [comment]
guys can anyone help me to find the bravo calibur v1 71 keys software, please? for some reason, this one is not working for me
