### ISSUE TITLE
Logitech g910 error

### ISSUE THREAD

**Issue by piktok** [SpoinkyNL/Artemis#43]
Hello I have the logitech g910 and I get this error when i'm lunching Artemis

An exception was thrown while invoking the constructor 'Void .ctor(Caliburn.Micro.IWindowManager, Artemis.ViewModels.ShellViewModel)' on type 'SystemTrayViewModel'. ---> Unable to load DLL 'LogitechLedEnginesWrapper ': The specified module could not be found. (Exception from HRESULT: 0x8007007E) (See inner exception for details.)

Unable to load DLL 'LogitechLedEnginesWrapper ': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by JewsOfHazard** [comment]
No problem. It seems you are missing a dynamic link library. You're keeping the project contents together right? The original exe has to stay in the target folder. If you want to just make a shortcut to place somewhere else.

**Comment by piktok** [comment]
Yes im running the exe from the folder itself :o

**Comment by JewsOfHazard** [comment]
Just making sure you'd be surprised what I've had to talk people through. Give me 10 minutes and I'll be at my desk ready to help you. My first guess from my phone here is that Logitech gaming software is old or not running.

**Comment by SpoinkyNL** [comment]
Hey there, 

Could you try installing Visual C++ Redistributable for Visual Studio 2012 Update 4 from over here? https://www.microsoft.com/en-us/download/confirmation.aspx?id=30679

**Comment by piktok** [comment]
Thanks spoinkyNL!! I download visual C++ studio and its not working !

**Comment by SpoinkyNL** [comment]
Alright, if the DLL is in the folder but it's still not being loaded, something else is missing. Will look into this.

_Note to self: dumpbin /DEPENDENTS my.dll_

**Comment by SpoinkyNL** [comment]
Hey, could you remove all traces of the program and try with the latest setup?

**Comment by JewsOfHazard** [comment]
Hey if you want to cooperate you can try clearing the program off of your computer and installing the new version released more recently.
