### ISSUE TITLE
Nothing shows up upon opening Artemis.exe

### ISSUE THREAD

**Issue by cryzereye** [SpoinkyNL/Artemis#431]
Literally nothing shows up. I see the program's process running in Task Manager but it will immediately disappear.

**Comment by rakosi2** [comment]
Check the task bar. Artemis will minimize to task bar.

**Comment by cryzereye** [comment]
[https://imgur.com/a/Z3oQu](url)

Not app icon in taskbar

**Comment by SpoinkyNL** [comment]
Hi there, sorry that you're having trouble!

You might be missing [Visual C++ Redistributable for Visual Studio 2012 Update 4 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679), it's required for some API's we use. Could you try installing that?

If that doesn't help perhaps there's something in the logs, you can post them like this:
1. Head into ```C:\ProgramData\Artemis\logs``` (this is a hidden folder, just paste the path in Explorer).
2. Drag the ```log.txt``` file into the GitHub comment box, uploading it.
3. Optionally set the logging back to Info to keep your log files small.

**Comment by cryzereye** [comment]
Apparently, the issue is only happening when the .zip was used. Tried using .msi and it worked fine.

**Comment by cryzereye** [comment]
Closing.
