### ISSUE TITLE
ambient effect only working for primary monitor

### ISSUE THREAD

**Issue by DrDragonKiller** [SpoinkyNL/Artemis#432]
I have to monitors. The left one is my primary monitor and the one to the right is the secondary one. Both are 1920*1080.
I tried offsetting the ambient effect by 1920 pixels to the left, however then it is just all black.

PS: the toggle switch for the black-bar detection on the left is centered instead of alligned to the left

**Comment by HazardDev** [comment]
This is probably less of a bug and more of a side-effect of how the effect is implemented.
