### ISSUE TITLE
Freeze of the animations.

### ISSUE THREAD

**Issue by ZeTioZ** [SpoinkyNL/Artemis#434]
Hello, sometimes when I play the animation of the keyboard just freeze and I have to disable and enable again the module in artemis to get this work again. How can I fix it ? (I have a G910 keyboard).

**Comment by LokeYourLord** [comment]
I am facing the same issue, but it only happens when I start some few games that make the computer kind of "lag out" for a few seconds like Overwatch, Warframe or GTA V (as an example).
