### ISSUE TITLE
Can you support the Redragon K556 RGB? 

### ISSUE THREAD

**Issue by Bastian0930** [SpoinkyNL/Artemis#435]
I got this keyboard a while ago, and was wondering if I could add this. I probally messed this request up somehow. If I did, please tell me and I can resubmit it. Thanks!

**Comment by rakosi2** [comment]
Artemis needs an SDK to talk to the keyboard. Without the SDK it would be very difficult to add as we would need to reverse engineer the USB protocol and we don't have that keyboard plus it would take a lot of time. I tried to google it but I couldn't find anything [other then a reddit post saying the same thing](https://www.google.com/amp/s/amp.reddit.com/r/ffxiv/comments/6qojrf/are_some_rgb_keyboards_not_usable_with_those_fun/). Once Redragon adds SDK support then we can add it to Artemis.

**Comment by nodgear** [comment]
Redragon doesn't need SDK, most of then uses HID to control the lights
