### ISSUE TITLE
Logitech G410 Support not showing up.

### ISSUE THREAD

**Issue by ImMrMcCoy** [SpoinkyNL/Artemis#436]
When you go into the settings to select a keyboard it does not have a G410 option even though the app says it has support for the G410.

**Comment by rakosi2** [comment]
https://github.com/SpoinkyNL/Artemis/wiki/Frequently-Asked-Questions-(FAQ)#devices download the two links and install. Also read section https://github.com/SpoinkyNL/Artemis/wiki/Frequently-Asked-Questions-(FAQ)#what-does-the-generic-device-type-do ,Logitech uses generic layer.

**Comment by SpoinkyNL** [comment]
Hey, you can use either the G910 or G810 profiles, just select either of them in the drop down and see which matches the G410 the closest. Artemis 2 will have better support for this.
