### ISSUE TITLE
Would you ever be able to support Glorious' line of keyboards?

### ISSUE THREAD

**Issue by GandhiChan** [SpoinkyNL/Artemis#437]
I'm talking about [these](https://www.pcgamingrace.com/products/glorious-modular-mechanical-pc-gaming-keyboard-full-size-104-key-gateron-cherry-kailh-switches). They have their software available [here.](https://www.pcgamingrace.com/pages/gmmk-software-download)

**Comment by rakosi2** [comment]
We are going to need an SDK provided to be able to interface to keyboards. I couldn't find an SDK with a quick google search but if you found one then send the link so we can add the keyboard.
