### ISSUE TITLE
Software - Android Port?

### ISSUE THREAD

**Issue by LokeYourLord** [SpoinkyNL/Artemis#438]
I would like to know if this is even feasible in any way. I want to connect my G910 to my Android Tablet per USB, and would like that to react to Music on my Tablet as well, is it in any way possible to port this software over to Android so it functions in the same way or similar (Audio Visualizer functions are the most important to me :) ).

Thanks in advance :D!

**Comment by SpoinkyNL** [comment]
Nope, there's no SDK for any of the supported devices in Android not to mention that the UI is built in WPF which only works on Windows.
