### ISSUE TITLE
[REQUEST] Burnout Paradise: The Ultimate Box

### ISSUE THREAD

**Issue by SSonic70** [SpoinkyNL/Artemis#44]
I would honestly love to see support for Burnout Paradise: The Ultimate Box in Artemis. It's one of my favourite games of all time and I had this one idea (based off of the support for Rocket League) that I thought would be interesting.

The idea is essentially to have the same (or similar) style to how Rocket League support is right now, but to have another option to have the colour of the keyboard to match the type of boost you're using.

There's 5 different boosting types in the game: Stunt (Green), Speed (Yellow/Orange), Aggression (Red), Locked (Blue) and Switchable (Toggle between Stunt, Speed and Aggression).

The game is quite old (came out near the start of 2008), so memory reading could be an option. There are a couples of mods for the game, the main one being Vanity Pack (adding in tons of new cars, game modes, features, etc.)

Thanks for making this software, keep up the good work!

EDIT: Wanted to mention that the game does not have anti-cheat software implemented for online multiplayer.

**Comment by SpoinkyNL** [comment]
This one shouldn't be too much of a pain with memory reading, and low maintainability because it's unlikely they'll update this.

Can probably include this in the datamodel:
- BoostAmount
- BoostType
- CarHealth(?) I'm not sure if this is indicated ingame, it's been a while
