### ISSUE TITLE
Can I Run Artemis with just a headset and an arduino and no keyboard?

### ISSUE THREAD

**Issue by Wail3Y** [SpoinkyNL/Artemis#442]
I used this tutorial to connect my arduino nano and ws2812b strip to artemis, but I can't get them to work. I'm not sure if having a keyboard necessary for this to work.

https://github.com/SpoinkyNL/Artemis/wiki/Adding-a-non-keyboard-device-yourself

**Comment by rakosi2** [comment]
Artemis should not need a keyboard to work. The RGB strip will use the generic layer and Headsets have the headset layer. I am the one that wrote the code for the RGB strip and I am not able to help you with that limited info, you are going to have to tell me what is not working.
