### ISSUE TITLE
where do i download the artemis's imported file on logitech gaming software

### ISSUE THREAD

**Issue by ByDouu** [SpoinkyNL/Artemis#443]
the problem is as on title please help me

**Comment by SpoinkyNL** [comment]
Hey there, that's not how Artemis works.

Artemis runs as a replacement for the Logitech Gaming Software. You can find the latest installer [here](https://github.com/SpoinkyNL/Artemis/releases/download/1.11.2.0/artemis-setup-1.11.2.0.msi).

**Comment by ByDouu** [comment]
Okay, thank you my friend i managed to sync the artemis with lgs but i have a problem when im into artemis interface my left,down,right arrow and number 0 and comma on numpad is blinking on same color no matter what effect i use, could you please help me with that thank you

**Comment by ByDouu** [comment]
hello again, i believe my problem is my application's keyboard has shifted to the right for like 3-4 column according to the indivicual keybord that im using, so i believe that might cost some problems which i wroted on last post, im using logitech g810 btw, could you please help me about it, thank you

**Comment by SpoinkyNL** [comment]
Hi, this could be an issue with the G810, could you make a profile that
shows the issue and take a screenshot of Artemis and a picture of the
keyboard. That way I can see the offset

Op 6 mrt. 2018 22:33 schreef "ByDouu" <notifications@github.com>:

**Comment by ByDouu** [comment]
of course bro here are the pictures, here you can see (picture name 1) where i would like to put my layer and where actually it does on my keyboard (picture 2), at picture 3 and 4 you will see another example of this problem and please notice during these process my left, down, right, number 0 and coma keys are randomly blinking no matter what layer or effect i use

 
![1](https://user-images.githubusercontent.com/37085237/37062844-aa75040a-21a8-11e8-8617-c503d9dd45e2.jpg)
![2](https://user-images.githubusercontent.com/37085237/37062845-aa950fde-21a8-11e8-8dac-e59898070566.jpg)
![3](https://user-images.githubusercontent.com/37085237/37062846-aab6e082-21a8-11e8-9197-8cad681e3ed8.jpg)
![4](https://user-images.githubusercontent.com/37085237/37062847-aad552a6-21a8-11e8-999d-98cd34928c47.jpg)

**Comment by ByDouu** [comment]
Hello, bro could you tell me how do i change the picture of the keyboard layout on artemis app, the picture on the screen does have qwertz layout so i think that can fix the issue
