### ISSUE TITLE
G910 not found

### ISSUE THREAD

**Issue by cedrik1995** [SpoinkyNL/Artemis#449]
I have the latest version from Artemis (1.11.2.0) and latest lgs 9.0.42
Bought my Logitech G910 a few days ago and tried severall things to get it working but Artemis keeps telling me it can't find my keyboard, that i need to check the version i have installed. When i open lgs it tells me my keyboard is a G910v2. Could this be the reason why it isn't finding my keyboard?

**Comment by cedrik1995** [comment]
I had them installed, just tried reïnstalling them, i still got the same error

**Comment by SpoinkyNL** [comment]
Hi, please try with the latest version and let me know if it works again :)

**Comment by cedrik1995** [comment]
Works great now, thanks for the fix :)

**Comment by SpoinkyNL** [comment]
Great, thanks for letting me know!
