### ISSUE TITLE
Support for Motospeed ck108

### ISSUE THREAD

**Issue by lolitechk** [SpoinkyNL/Artemis#451]
Hello.
Is there any possible way to see future support for Motospeed k92(ck108)?
Its a great budget gaming keyboard and it will be shame not to get supported by a third-party software.

**Comment by rakosi2** [comment]
https://www.bountysource.com/issues/44004371-suggested-support-for-the-motospeed-ck108-keyboard

It is not possible without SDK from manufacturer and Motospeed has not provided an SDK. Sorry
