### ISSUE TITLE
Corsair K55 CueSDK.Initialize exception

### ISSUE THREAD

**Issue by yvalenty** [SpoinkyNL/Artemis#455]
Hi, I getting this exception when trying to enable Artemis on my Corsair K55 RGB keybord
https://pastebin.com/6vyy2xeW
Is there any way to fix it?
Thanks

**Comment by rakosi2** [comment]
Corsair has not yet included the K55 into their SDK and therefore Artemis can not access the K55.
Corsair has only added these devices to their sdk:
![image](https://user-images.githubusercontent.com/6037087/42128409-90977b14-7c5f-11e8-9c69-3200eb8f39e8.png)

**Comment by yvalenty** [comment]
Oh, ok thanks for the info
