### ISSUE TITLE
Artemis not detecting right version of LGS 

### ISSUE THREAD

**Issue by j-p87** [SpoinkyNL/Artemis#456]
Hi, 
Artemis haven't worked for me since I updated LGS to 9.0.42. 
I get an error message when I try to choose my keyboard G910:
![image](https://user-images.githubusercontent.com/41265486/42734649-ef633702-8847-11e8-9441-6941db0e8fed.png)

I have reinstalled LGS and Artemis - No work
I have also checked your FAQ and reinstalled Microsoft Visual C++ 2012 and 2015 - No work
I have also searched my registry for 8.83.85 - Not finding anything 

What can I do? 

Regards
Jean-Pierre

**Comment by jdfosterarmy** [comment]
I am also getting the same problem and did all what jean-pierre
