### ISSUE TITLE
GTA V - Wanted lights but not wanted

### ISSUE THREAD

**Issue by fotis016** [SpoinkyNL/Artemis#458]
Hello,
I have opened both artemis and gta v with admin priviliges, however the top part of my keyboard lights up like police siren strobe lights when my player is not wanted by police. Also I haven't messed up any settings in the profile options.
Thank you!
![40347690_296807267770376_3518952252771401728_n](https://user-images.githubusercontent.com/13164014/44820472-ad72fa00-abf9-11e8-94c5-ffe00849cea6.jpg)

**Comment by therimmer96** [comment]
Been having the same issue for a while.

My Logitech G560's don't respond to the game either, I'm assuming GTA or Logitech broke something and so Artemis can't talk to the game.

**Comment by fotis016** [comment]
Looks like this project is abandoned, a few people are having unresolved issues with other games and didn't get any replies. I'm switching to an alternative lightning software...
