### ISSUE TITLE
Masterkeys Pro S - Animation freezes when Spotify is open

### ISSUE THREAD

**Issue by blaklamp** [SpoinkyNL/Artemis#459]
When I open Spotify, whether I'm playing music or not, animations run for 1 second then freeze for 1 second, and it goes on and on. I've tried this for all animations.

![artemis spotify](https://user-images.githubusercontent.com/44107039/46901039-1a1c1e00-ce61-11e8-9c29-5cc0c4ba69a7.gif)

**Comment by Jeremiidesu** [comment]
Same issue here, with a G910 Orion Spectrum.

**Comment by VidyaGaeemrVlad** [comment]
I noticed this too, closing Spotify causes the lag to cease but that doesn't really help when I want the audio visualiser.
