### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by ThaDaVos** [SpoinkyNL/Artemis#467]
I stumbled across this project as I am looking for Unified RGB software but when trying to open the website I got greeted with an error:
![image](https://user-images.githubusercontent.com/5251028/85427823-98105200-b57c-11ea-900f-1159eadd9723.png)

**Comment by SpoinkyNL** [comment]
Hey, thanks for the report, I've been having some trouble with the server that's currently hosting the webpage, the site should be back up now :)
