### ISSUE TITLE
Steam Connection idea?

### ISSUE THREAD

**Issue by TheAmazingTophat** [SpoinkyNL/Artemis#48]
Would it be possible to have the G logo flash orange or maybe a user defined colour whenever steam gives you a notification, I'd say it would be useful if you're playing a game and don't notice you have a message but with the light you can be all like "oh hey, I have a message, I mustn't have seen it. Thanks SpoinkyNL and JewsOfHazard for making this awesome program."

**Comment by SpoinkyNL** [comment]
It would probably be very easy to actually have the keyboard indicate one way or another when anything is blinking in the task bar, good suggestion!

**Comment by SpoinkyNL** [comment]
I'd like to include this in the Windows Profile soon, so you can include it in a profile
