### ISSUE TITLE
Artemis stopped working...

### ISSUE THREAD

**Issue by TheAmazingTophat** [SpoinkyNL/Artemis#49]
All of a sudden none of the features were working, I turn on an effect and it works for a seconds and then lights off... any clue what I did wrong? i haven't messed with anything.

**Comment by SpoinkyNL** [comment]
Is there perhaps still one of the supported games running in the background? Maybe one didn't shut down properly.

You could maybe try rebooting see if that helps

**Comment by TheAmazingTophat** [comment]
Oh right... Thanks :D
