### ISSUE TITLE
Dark theme.

### ISSUE THREAD

**Issue by TheAmazingTophat** [SpoinkyNL/Artemis#51]
As the title suggests, it would be nice to get a dark theme option for the launcher, maybe a dark grey

**Comment by JewsOfHazard** [comment]
That is a feature for customization in a later patch. Stay tuned. 

Please excuse typos as this was sent from my iPhone

**Comment by SpoinkyNL** [comment]
Just a tiny update to show I haven't died!

Hard at work on a profiles in a [separate branch] (https://github.com/SpoinkyNL/Artemis/tree/profiles_new) which will also include support for a dark theme:

![Dark one](http://i.imgur.com/WA0HjW3.png)
![Dark two](http://i.imgur.com/tDGJXdw.png)
