### ISSUE TITLE
Multiple game requests

### ISSUE THREAD

**Issue by TheAmazingTophat** [SpoinkyNL/Artemis#53]
These are some games that IMO would work well with RGB lighting, I don't know if they have what they need to get the RGB working but here's the list anyway.

DayZ Standalone (Thirst, Hunger, Ammo, not sure if blood or health capacity is a thing)

Elite Dangerous (Boost, lots of technical stuff like capacity, Shield and Damage)

Fallout 4 (Has mod support(Health, weather, if you set a quest a red light shows up and goes green when complete, f1 to f12 could be compass))

L4D2 (Health, Ammo, Character?)

Rust (Thirst, Hunger, Health)

Tom Clancy games...

Keep talking and nobody explodes.

Main point, this would be cool with survival games

**Comment by SpoinkyNL** [comment]
Fallout 4 could be a thing, rest I'm not sure about as I don't see any way of getting data except for memory reading.
