### ISSUE TITLE
[Request] League of Legends

### ISSUE THREAD

**Issue by Lazyox** [SpoinkyNL/Artemis#54]
Hey I want to say that the quality and usability of this program is astounding and I always use it when I play CS:GO or rocket league. But for CS:GO I would suggest adding a part for the user to be able to change the colour of the keyboard depending on the team instead of having it the default red and blue.

However, on the main point, from watching you're video demonstrating the software, you stated that your main games are League of legends and Rocket league. And I understand making effects for Rocket league but why not make it for League of legends as well? If the reason is because you haven't got an ideas for what to do for effects. This one might be too complicated to code but you could trying having a default back lit colour of the user's choice then have the abilites turn a different colour when the cool down is on then make the key to flash white then change to the original colour. If you want a slightly less complicated suggestion you could have when you die it flashes red then turns grey, then when you respawn flash either blue or purple depending on the side you're on then it return to the original colour. 

Those are just a few ideas you could input into the software but I would be happy if there was effects dedicated to League of Legends as I play it as my main game. I already have one on the CUE but i think it looks awful compared to a CS:GO back lit I found. Anyway I hope you consider adding League of Legends effects

(Sorry if you've seen these suggestions in other places, I'm not trying to copy if I have and sorry if you are already making it)

**Comment by SpoinkyNL** [comment]
Hey, I woi

**Comment by SpoinkyNL** [comment]
Ignore the above, my phone failed.. 

Anyway, I'd love to to have LoL support since it's such a popular game. But we don't have a good way to get game data, except for memory reading, which takes a lot of maintenance and can be bannable :/

**Comment by Lazyox** [comment]
Ahh that's unfortunate I love other aspects of the program. keep up the the
good work

**Comment by Xelus22** [comment]
Try contacting Rito, they would most likely help.
