### ISSUE TITLE
[Request] Support for KM780 Ripjaw Keyboards

### ISSUE THREAD

**Issue by scumsuckinglandlord** [SpoinkyNL/Artemis#55]
I believe there is only one completely RGB Ripjaw Keyboard, but it'd be nice to have support for it. It's manufactured by G.Skill, and if there's anything you guys need that I can supply I'd be glad to.

**Comment by SpoinkyNL** [comment]
Hey, do they provide any kind of SDK? If so, we could certainly look into adding support. Would need someone to test it though!

**Comment by scumsuckinglandlord** [comment]
I emailed them about if they have an SDK, no response yet. I'd also be glad to test it.

**Comment by SpoinkyNL** [comment]
Did you ever have a response on this?

**Comment by scumsuckinglandlord** [comment]
Sadly, no I haven't got any response.

**Comment by SpoinkyNL** [comment]
Ok, sadly not much we can do than, sorry :(
I'm closing this, should they reply you can always open up a new issue of course :)
