### ISSUE TITLE
More idle-effects

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#56]
We should have some more idle effects, a few I was thinking off:
- Liquid, would be different colors, could react to button presses / mouse movement
- Configurable sliding colors kinda like the debug effect, but with more stuff
- Ambilight, if it's doable without a performance impact

Suggestions are welcome

**Comment by patmanblu3** [comment]
Liquid effect would be cool, Can't wait to see what the next update brings. Let me know if you need me to test anything.
