### ISSUE TITLE
Settings reset every time computer reboots

### ISSUE THREAD

**Issue by Weeberz** [SpoinkyNL/Artemis#58]
The only reason I currently use Artemis for is for Rocket League, but every time I reboot my computer it turns on type waves, and turns on the effects for Witcher 3 and CS:GO. I want it to stay only rocket league every time I start my computer

**Comment by JewsOfHazard** [comment]
That's odd. It works for me. Ok I'm sorry to ask this but just to cover all the bases, when you turn off an effect you click save settings right?

**Comment by Weeberz** [comment]
haha yes I click save settings. I can provide any more info you need, such as it seems the settings menu stays persistent but the effects menu does not. mostly its the game effects and type waves, although ill do some more testing to see specifically which things change.

also just to make sure its clear this only happens from a full reboot, it does not happen when I boot from sleep

**Comment by SpoinkyNL** [comment]
Hey, thanks for the report. 

Do the settings stay if you close the application using the tray icon and restart it again without rebooting?

**Comment by Weeberz** [comment]
They do seem to stay when disabling and reenabling

**Comment by JewsOfHazard** [comment]
I believe he means clicking exit though.

**Comment by SpoinkyNL** [comment]
Yeah, sorry, I meant clicking exit so it's completely gone, and then restarting it

**Comment by Weeberz** [comment]
Whoops, duh, I shouldnt try to think at 8am...

Yes when I exit out and return the settings change. I actually apparently had uninstalled it so when I clicked exit I had to reinstall it and I tried it all again, and it still happens but now its different settings that change. Before it kept turning on all game effects and type waves, but not it turns on all games and volume overlay. Also some times when I reboot my computer it does something that causes no lights to be on at all, but when I start up a game with the effect or turn on/off debugging really quick it goes back to normal

**Comment by SpoinkyNL** [comment]
No problem :p
Could you try with the portable version? I'm at a bit of a loss since the config system is basically something Microsoft provides and should be working.

**Comment by Weeberz** [comment]
Im on a K70 RGB, I used the portable version and now its not changing game effects, but it does keep turning on type waves, which seems to mess with game effects and doesnt do rocket league. Not sure about the other games I dont have them. Is it possible because I have type waves on in the corsair software?

**Comment by JewsOfHazard** [comment]
No it shouldn't be. The Api takes over from CUE and its settings are ignored.

**Comment by SpoinkyNL** [comment]
Could you try going to **C:\Users\<Username>\AppData\Local** and deleting the **Artemis** folder.

After that run Artemis with admin rights, and see if it persists now (this is just me trying things)

**Comment by Weeberz** [comment]
Did that, problem still persists

**Comment by SpoinkyNL** [comment]
Hey, sorry for the delay. I just want to make sure you are clicking Save Settings after disabling a game, could you confirm that?

**Comment by SpoinkyNL** [comment]
Type Waves being enabled was indeed a bug, it's fixed in 1.1.0. As for the games being re-enabled I'll see if it happens for me too.

**Comment by SpoinkyNL** [comment]
Hello, could you try this with the latest version and see how it goes?
