### ISSUE TITLE
Volume Overlay Ignoring Color Selection

### ISSUE THREAD

**Issue by lavalle00** [SpoinkyNL/Artemis#61]
Hi! Just noticed on the lastest release, after doing a clean install, that regardless of which color I select for the volume overlay, it'll always select green. Not sure if it's B/c of my previous corsair profile (before opening Artemis), or something specific to the Strafe, but thought I'd let you know :)

**Comment by JewsOfHazard** [comment]
Corsair profiles are unrelated. This is something we can look to fix for sure. We're planning on the next update being a bit of a bigger one so stay excited :)

**Comment by JewsOfHazard** [comment]
Hey would you mind trying to clear all traces of Artemis off of your computer and reinstalling? I know this would remove some configs but to test it should help out.

**Comment by SpoinkyNL** [comment]
Nah, it's broken. See #57

**Comment by JewsOfHazard** [comment]
Ahh ok
