### ISSUE TITLE
[Request] Logitech G810 Orion Spectrum RGB

### ISSUE THREAD

**Issue by wilchen558** [SpoinkyNL/Artemis#63]
Add support for Logitech G810 Orion Spectrum RGB

**Comment by SpoinkyNL** [comment]
Hey, did you test it? It should work when selecting the G910

**Comment by wilchen558** [comment]
Yes i tried. I get the "Couldn't connect to your Logitech G910" Firmwere on my g810 is v102.1.22

**Comment by SpoinkyNL** [comment]
Hey, sorry for not getting back to you earlier. 

Are you running the latest version of the Logitech Gaming Software? That's a seperate thing from your G910's firmware.

You can always grab the latest version over here: http://support.logitech.com/en_us/software/lgs

**Comment by SwitchBoardx** [comment]
Hi, I just posted my own issue like this, didn't see this thread already. I have a G910, and Artemis is not picking it up. I just installed the newest version of LGS and its still not picking it up.

**Comment by SpoinkyNL** [comment]
@SwitchBoardx I've replied to your issue :)

@wilchen558 Could you just confirm for me that you have "Allow games to control illumation" enabled in settings? 
http://i.imgur.com/kadN6Yc.png

And that you have Visual C++ Redistributable for Visual Studio 2012 Update 4 installed?
You can find it at Microsoft's site (https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679)

**Comment by SpoinkyNL** [comment]
@wilchen558 The issue seems to be related to #68 and #69. 
Could you also try completely removing LGS? After uninstalling it make sure it's folder is also gone (located at **C:\Program Files\Logitech Gaming Software**, that folder should be removed)
