### ISSUE TITLE
[Request] Rocket League Menu effect

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#65]
How about somekind of a Menu effect? Like a lighting effect that looks like a ball is rolling over keyboard or something similar

**Comment by JewsOfHazard** [comment]
It's possible. I'll look into it.

**Comment by SomaKhaos** [comment]
That would be great, cause in the menus my keyboard is kinda dark cause of the boost effect :D

**Comment by SpoinkyNL** [comment]
We'll be including this in the data model for Rocket League next update, so you can include it in a profile
