### ISSUE TITLE
[Request] Rocket League "Color Explosion" orange/blue on goal

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#66]

**Comment by SomaKhaos** [comment]
*Color 

Sry for typo, was on mobile

**Comment by JewsOfHazard** [comment]
This would be incredibly difficult to do given the current way we find boost. If psyonix gives us an API I'd gladly add this in a hearbeat.

**Comment by SomaKhaos** [comment]
just to make sure, was it closed because it has been implemented or was it closed because it's not possible at the moment due to we had to wait that psyonix will give you an API?
