### ISSUE TITLE
G SDK reporting wrong version?

### ISSUE THREAD

**Issue by juilinsandar** [SpoinkyNL/Artemis#68]
The G Key SDK appears to be reporting a different version number to the one installed: LogiLedGetSdkVersion is returning 8.70.59 even though the installed version of LGS is 8.81.15

**Comment by SpoinkyNL** [comment]
Hey,

Are you using the Logitech LED SDK and having an issue with that, or is there an issue with our application, Artemis?

**Comment by juilinsandar** [comment]
It's with both, I just noticed it because of Artemis.

After some investigation, I discovered that when I updated LGS, it didn't update LogitechLed.dll due to it being in use in my own application. The LGS installer doesn't throw an error if this occurs, it just ignores the file. Deleting the dll and reinstalling LGS solved the issue.

**Comment by SpoinkyNL** [comment]
Aha very interesting, that explains the issues some of people are having. Thanks for letting us know!
