### ISSUE TITLE
Artemis not finding Logitech G910

### ISSUE THREAD

**Issue by SwitchBoardx** [SpoinkyNL/Artemis#69]
Hey guys, I found out about Artemis on the /r/LogitechG website, and pretty interested in trying it. I downloaded it and at first Artemis didn't see my keyboard and was informed that I should update my Logitech Gaming Software to 8.81.15 which I did, but it still is not picking up the keyboard.

**Comment by SpoinkyNL** [comment]
Hey, 

Could you just confirm for me that you have "Allow games to control illumation" enabled in settings? 
http://i.imgur.com/kadN6Yc.png

And that you have Visual C++ Redistributable for Visual Studio 2012 Update 4 installed?
You can find it at Microsoft's site (https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679)

**Comment by SwitchBoardx** [comment]
I have the setting enabled as well as the Redistributable installed

**Comment by SpoinkyNL** [comment]
Hm strange. Did you reboot after updating?

**Comment by SwitchBoardx** [comment]
Yes, I actually didn't have a choice in the matter. Haha. It just did it with out telling me

**Comment by SpoinkyNL** [comment]
Alrighty, if you don't mind, would you run this version of Artemis? https://www.dropbox.com/s/b8qv37ky8w77fee/test-build.rar?dl=0

I changed the error message to include the version number it's found. If that's 0.0.0 then it is failing to connect to the keyboard. Perhaps you could post a screenshot of the error message?

Besides that, could you go to **C:\Program Files\Logitech Gaming Software\SDK\LED\x64** and look for a file called **LogitechLed.dll**. It should be the only file there, and it should be 48 kB in size. If anything seems off, could you include a screenshot of that folder too?

I'd really like to figure this one out, but it's 01:44 here in the Netherlands so I'm afraid I won't be able to get back to you untill tomorrow :(

**Comment by SwitchBoardx** [comment]
No problem, I will do as you ask, and post results. Get some sleep!

**Comment by SwitchBoardx** [comment]
http://puu.sh/nMLmW/0c3ca0e3fb.png So this is what it says, (Of course it says its the wrong version)

but then I checked LGS: http://puu.sh/nMLry/20b85fc1c8.jpg

**Comment by SpoinkyNL** [comment]
Because of #68 and what @juilinsandar reported back I think the same thing has happened to you. 

Could you remove LGS and make sure it's folder is completely gone (it's located in C:\Program Files\Logitech Gaming Software) 

Once it's completely gone reinstall LGS, and then Artemis should work

**Comment by SwitchBoardx** [comment]
This fixed the problem, thank you for the input!

**Comment by SpoinkyNL** [comment]
Great, thanks for reporting back! I'll update the error messages and FAQ to include this
