### ISSUE TITLE
Doesn't work with Windows Star

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#70]
Everytime i start my PC and the program loads with windows it doesn't work.
I have to close the program and restart it to get it to work.

**Comment by SpoinkyNL** [comment]
Hey,

Which keyboard are you using?
Op 21 mrt. 2016 13:06 schreef "SomaKhaos" <notifications@github.com>:

**Comment by SomaKhaos** [comment]
Logitech g910 Orion Spark

**Comment by SpoinkyNL** [comment]
Ok, thank you. It's probably got something to do with the Logitech driver
not being ready yet.

I'll look into it before the next release

**Comment by SomaKhaos** [comment]
Works with new Version. But on every Windows start i have to give administrative rights.

**Comment by SpoinkyNL** [comment]
Hello, Artemis indeed needs admin rights to run, so it can read and write to game folders.
