### ISSUE TITLE
[Request] Rainbow wave for audio visualization

### ISSUE THREAD

**Issue by dankeroni** [SpoinkyNL/Artemis#75]
It would be nice to have the option to use a rainbow wave instead of the three colors for the audio visualization. They keys that are not being used by the visualization should be less bright.

**Comment by SpoinkyNL** [comment]
Hey, what exactly do you mean with a rainbow wave? It should just shift through colors, lighting only the keys up according to the audio strength?

Also, keys that the audio visualization doesn't use should be turn off all together, what keyboard are you using?

**Comment by Dankeroni** [comment]
I'm using a k70. I got the idea from another program I am using, it's called RGB Spectrograph, can't remember where I downloaded it. 
Anyway, here is a video showing the feature: [https://www.youtube.com/watch?v=a0EyEbRIJsg](url)

**Comment by SpoinkyNL** [comment]
Ah like that. I'm working on a giant update right now regarding games. But I'll look into expanding the audio visualization later, and keep this in mind :)

**Comment by Dankeroni** [comment]
Don't mind me, I'm new here. Thanks for answering!

**Comment by SpoinkyNL** [comment]
The latest release has support for audio visualization layers now that allow you to do this :)
https://github.com/SpoinkyNL/Artemis/releases/tag/1.3.0.0
