### ISSUE TITLE
[Request] Idle color for Type waves effect

### ISSUE THREAD

**Issue by Scepthor** [SpoinkyNL/Artemis#76]
Hi I love the Type Waves effect on my G910 but i would really appreciate if there would be some default idle color preferable something we can choose and toggle off/on.
So when we are not pressing any buttons the keyboard would be still lit up under some color or effect.

I was also thinking if the keyboard would be idle for some period of time maybe it could generate fake random clicks to sort of look like a screensaver for a keyboard.
It's all just an idea but if it would have toggle off/on I think no one would complain and lots of people might appreciate this feature.

**Comment by SpoinkyNL** [comment]
Hello, it's something I'll look in to after the next update, thanks for the suggestions :)

**Comment by Continous** [comment]
Any chance of being able to add effects, such as type waves and the audio visualization as overlays in the 'windows profile' menu?

**Comment by SpoinkyNL** [comment]
Hey, yes that is something I'm planning to do :)

**Comment by Continous** [comment]
Good, perhaps it'll be easier to make custom effects now across multiple keyboards.
