### ISSUE TITLE
Windows 10 and failed to connect to g910

### ISSUE THREAD

**Issue by solareon** [SpoinkyNL/Artemis#77]
Clean install of windows 10 with LGS 8.82.151. Installed Version 1.0.2 of artemis and when I select G910 from the settings it says failed to connect and to update my LGS software. Any ideas or settings to change?

**Comment by SpoinkyNL** [comment]
Hello!

Could you try installing  [Visual C++ Redistributable for Visual Studio 2012 Update 4 - 64 bit](https://www.microsoft.com/en-au/download/confirmation.aspx?id=30679)?

**Comment by solareon** [comment]
When I went to install it only offered repair and uninstall. I did the repair, rebooted, and no change. Did the uninstall, reboot, reinstall with no change. The error that shows in artemis is attached.
![image](https://cloud.githubusercontent.com/assets/769465/14410935/c189112e-ff43-11e5-8bbf-efcfa6316396.png)

**Comment by SpoinkyNL** [comment]
Ah yes, I've seen that before.

Could you try shutting off Artemis and any other programs running in the background, then uninstalling the Logitech Gaming Software and reinstalling it again?

**Comment by solareon** [comment]
That did the trick. I guess installing Artemis first and then installing LGS gets it working on the new version.
