### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#80]
I've started work on a WordPress based website: http://artemis-rgb.com/

**A todo list since I like them:**
- [ ] Welcome page (I copy pasterino'd the GitHub readme for now)
- [ ] Feature showcase
- [ ] A promo video
- [ ] FAQ (Only General is done and the ordering needs to be logical)
- [ ] Blog 
- [ ] Downloads
- [ ] GitHub link

**Comment by JewsOfHazard** [comment]
Suggestion - It only needs to be static so why don't we use gh-pages?
