### ISSUE TITLE
Razer Blackwidow Chroma ETA

### ISSUE THREAD

**Issue by FireFlyForLife** [SpoinkyNL/Artemis#81]
Is there an eta for when support is added for this keyboard? since I already see the Razer keyboard provider in the code. What is stopping the keyboard from not being supported? I would be happy to help but I have no idea where to start looking to make the keyboard supported

**Comment by JewsOfHazard** [comment]
I can make you a dev build later this afternoon. It's going to be quite buggy though

**Comment by FireFlyForLife** [comment]
That would be great!

**Comment by SpoinkyNL** [comment]
Hey, here's a pre-release that includes Razer, we had it ready for a while but it would be nice if you could test it for us, since we both down own a Blackwidow

https://github.com/SpoinkyNL/Artemis/releases/tag/1.0.3

**Comment by KjeII** [comment]
Hi, I just tried to use Artemis on my Razer Blackwidow Chroma (I actually own the board, my friend Firefly knows more about programming tho :P) and on startup I get an 'exception' error, then the program stops working and closes.. 

This is the error:

An unexpected error occurred in Artemis.

An exception was thrown while invoking the constructor 'Void .ctor(Caliburn.Micro.IWindowManager, Artemis.ViewModels.ShellViewModel)' on type 'SystemTrayViewModel'. ---> De objectverwijzing is niet op een exemplaar van een object ingesteld. (See inner exception for details.)

De objectverwijzing is niet op een exemplaar van een object ingesteld.
____________________________________________________
Autofac.Core.DependencyResolutionException

Message:
An exception was thrown while invoking the constructor 'Void .ctor(Caliburn.Micro.IWindowManager, Artemis.ViewModels.ShellViewModel)' on type 'SystemTrayViewModel'. ---> De objectverwijzing is niet op een exemplaar van een object ingesteld. (See inner exception for details.)

Stack Trace:
   bij Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   bij Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   bij Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   bij Autofac.Core.Resolving.InstanceLookup.Execute()
   bij Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   bij Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   bij Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   bij Caliburn.Micro.Autofac.AutofacBootstrapper`1.GetInstance(Type service, String key)
   bij Caliburn.Micro.BootstrapperBase.DisplayRootViewFor(Type viewModelType, IDictionary`2 settings)
   bij Artemis.ArtemisBootstrapper.OnStartup(Object sender, StartupEventArgs e)
   bij System.Windows.Application.OnStartup(StartupEventArgs e)
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
System.Object Instantiate()

Source:
Autofac

HResult:
-2146233088
____________________________________________________
System.NullReferenceException

Message:
De objectverwijzing is niet op een exemplaar van een object ingesteld.

Stack Trace:
   bij Artemis.KeyboardProviders.Razer.BlackWidow.Enable()
   bij Artemis.Managers.KeyboardManager.EnableKeyboard(KeyboardProvider keyboardProvider)
   bij Artemis.Managers.KeyboardManager.EnableLastKeyboard()
   bij Artemis.Managers.MainManager.Start(EffectModel effect)
   bij Artemis.Managers.MainManager.EnableProgram()
   bij Artemis.ViewModels.SystemTrayViewModel..ctor(IWindowManager windowManager, ShellViewModel shellViewModel)
   bij lambda_method(Closure , Object[] )
   bij Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

TargetSite:
Void Enable()

Source:
Artemis

HResult:
-2147467261

**Comment by SpoinkyNL** [comment]
Yeah it's quite broken it seems, heh.. I'll update this post when I've got something that actually works

**Comment by SpoinkyNL** [comment]
I updated the release (https://github.com/SpoinkyNL/Artemis/releases/tag/1.0.3)

![It works on my machine](http://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)

**Comment by SpoinkyNL** [comment]
I've updated the download link yet again. Someone on reddit reported it wasn't working so I had another look. Any feedback is appreciated as I don't have a BlackWidow to test with

https://github.com/SpoinkyNL/Artemis/releases/download/1.0.3/artemis-1.0.3-setup.zip

**Comment by KjeII** [comment]
It works now :D Thanks! :smiley:

**Comment by SpoinkyNL** [comment]
Cool, I'll close this issue and if anything goes wrong feel free to create a new one
