### ISSUE TITLE
(G910) Audio Visualizer will hang/pause/freeze for a few seconds when toggling capslock/numlock/scrolllock

### ISSUE THREAD

**Issue by Clessiah** [SpoinkyNL/Artemis#83]
The visualizer does resume after that few seconds. Not sure whether the problem can be reproduced on G410 or G810.

**Comment by SpoinkyNL** [comment]
Hey, I tried on both the G910 and K95 but wasn't able to reproduce this on either.

What keyboard layout are you using?

**Comment by Clessiah** [comment]
I am using US layout.

I can replicated the problem on G810 too.

It doesn't happen every single time, but it does occur rather often.

**Comment by SpoinkyNL** [comment]
Hey, not much I can do about it now. With the new version we'll have a logging system. Should the issue still occur with that version the logs should tell me more.

Sorry!

**Comment by SpoinkyNL** [comment]
Hey, could you try with the latest version?

**Comment by Clessiah** [comment]
I am getting "Couldn't connect to your Logitech G910" error after the update. The Visual X 2012 Redistributable download link provided doesn't work and I am having slight trouble finding it via search engine. Will update when I get it to work.

**Comment by Thoth2020** [comment]
What do you mean doesn't work? What link do you see?

**Comment by Clessiah** [comment]
[I see this](http://i.imgur.com/DWfCjhf.png)

Didn't have this problem with previous version of Artemis.

**Comment by Thoth2020** [comment]
YAY I FIXD THING

**Comment by SpoinkyNL** [comment]
Cool, thanks for reporting back :)
