### ISSUE TITLE
Crashes when starting Rocket league

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#87]
Hey there, 

Sometimes Artemis crashes when i launch rocket league. It's not always just sometimes.

**Comment by SomaKhaos** [comment]
Would say, every second launch of rocket league or something like that

**Comment by SpoinkyNL** [comment]
Hi, does Artemis give you an error window? If so could you post a [PasteBin](http://pastebin.com/) link?

**Comment by SomaKhaos** [comment]
http://pastebin.com/Qi7C02KY

this is all information i get

**Comment by SpoinkyNL** [comment]
Ok thank you, those error messages actually say a lot :+1:.

I fixed this on the development version. That version isn't quite done yet so I'm afraid you'll have to work around it for now, sorry for the inconvenience, I hope to have a pre-release ready this week though, should the issue occur with that upcoming pre-release too, then please open a new issue
