### ISSUE TITLE
CS:GO can't get it working in a right way

### ISSUE THREAD

**Issue by Safritjuh** [SpoinkyNL/Artemis#88]
For some reason the CS:GO effect does not work as it should at my end.
very often it stays off(or the color set by LGS) .
Even when I disable the profiles in LGS some features will not work (like smoke or flash effect) and I've never seen the Ammo F-Keys working. 
Basically, the team color on the keyboard and the health status show op from time to time. 
Don't really know how to reproduce it. But any tips?

**Comment by SpoinkyNL** [comment]
Hi, it's broken on Valve's end, see #79. I'll try to contact them again but they haven't replied so far.
As for the colors not always working correctly, that's a bug with the latest LGS, I fixed it on the development branch but that version isn't quite ready for release yet.

**Comment by Safritjuh** [comment]
Must have missed that one. Was scanning issue names only :)

**Comment by Safritjuh** [comment]
As per comment, see issue [#79](https://github.com/SpoinkyNL/Artemis/issues/79)
