### ISSUE TITLE
"An instance of Artemis is already running (check your system tray.)"

### ISSUE THREAD

**Issue by medifin** [SpoinkyNL/Artemis#89]
I'm getting this error after trying to launch the app

[https://gyazo.com/b29bc4658415b67e72e254429944f2b3](url)

I can't find it in my system tray or task manager. What's wrong?

**Comment by SpoinkyNL** [comment]
Hi, I've released a hotfix for this, could you try uninstalling Artemis and reinstalling the [latest version](https://github.com/SpoinkyNL/Artemis/releases/tag/1.0.3.1)?

**Comment by medifin** [comment]
Thanks!
