### ISSUE TITLE
Suggestion: Overwatch support?

### ISSUE THREAD

**Issue by SomaKhaos** [SpoinkyNL/Artemis#91]
I wonder if it would be possible to add some Overwatch support. since there is no official Profile in the Logitech Gaming Software, i hope you will be able to do some kind of that. Would be great

**Comment by Cr4xy** [comment]
He is already doing it.
See development branch. :+1: 
https://github.com/SpoinkyNL/Artemis/tree/development

**Comment by SpoinkyNL** [comment]
Yes, Corsair was kind enough to provide the game, it'll be in the next update

**Comment by Thoth2020** [comment]
I just tried this out in the development branch and support works perfectly. If you're willing to put in the effort to make pretty profiles, you can do a lot of neat stuff. Profiles can be imported and exported, so hopefully someone more artistic than me can make something good.

**Comment by SpoinkyNL** [comment]
This is included in the latest update. Should you have any problems with it please create a new issue :)
