### ISSUE TITLE
I want to contribute but am new to github and don't know how to private message Spoinky

### ISSUE THREAD

**Issue by Thoth2020** [SpoinkyNL/Artemis#92]
I have enjoyed my G910 lately, but I'd love to have the kind of support with other games as I do with The Division. And I was thinking, heck, I could do it myself.

Clearly someone beat me to it by many, many months.

Even so, I couldn't help but notice it was written in C#. I've been working in C# for I guess, close to ten years now, and I am a Certified Microsoft Specialist in it. This is a project I'd love to contribute to, but I couldn't find a way to message you.

I'm also disappointingly new to GitHub so I'm sure this is about the dumbest way to ask to contribute. Even so, I'd like to help out. I don't have any specific ideas, except to try and add support for a game or two, but if there's something you need done and haven't had the time, maybe I can take a crack at it?

**Comment by SpoinkyNL** [comment]
Hey Thoth, thanks for your interest in Artemis.

10 years of C# experience, wow, I only started object oriented programming in early 2014!
GitHub doesn't actually have a PM system, oddly enough, but this'll work :)

It's great to see someone would like to contribute, I was hoping thous would happen. I'm sure we can find something exciting for you to add to Artemis if you'd like.

The code on the [development](https://github.com/SpoinkyNL/Artemis/tree/development) branch is miles ahead of main, I've been working on a big update for months now. I've converted almost everything to use dependency injection with [Ninject](http://www.ninject.org/) and game support is now oriented around layer-based profiles.

This means to add support for a game, all you need is extend a bunch of abstract classes to create a new module. Modules simply provide datamodel which contains all the game data that's available to Artemis, the module takes care of reading the data, be it by memory reading, be it using an API (preferred, especially for multiplayer games).

If you'd like to help, can you add me on Skype? target.robert
I would also love some feedback on the general codebase, I use Resharper to keep a consistent style and switching to dependency injection cleaned things up a lot, but there's always room for improvement

**Comment by medifin** [comment]
Any ETA for the update?

**Comment by SpoinkyNL** [comment]
Beta should be ready this week, can't make any promises though!
