### ISSUE TITLE
Device initialization improvements

### ISSUE THREAD

**Issue by SpoinkyNL** [SpoinkyNL/Artemis#93]
During Windows boot, Artemis may be started before the SDK(s) are ready Artemis must wait on them in a way that doesn't freeze the program.

Our CUE.NET implementation has a very crude solution to this (It literally just tries 10 times, completely freezing Artemis). This means switching to Corsair from the UI while you don't have a Corsair device Artemis will freeze until those 10 attempts are done. A nice generic solution would be a lot better.

**Comment by DarthAffe** [comment]
I could add an 'InitializeAsync'-Method to support event-/callback-based work. If you'd add some fancy loading-bar-stuff this might be enough.

**Comment by Thoth2020** [comment]
I was actually gonna try and work on this one, but I guess you can go for it if you want to?

**Comment by SpoinkyNL** [comment]
@DarthAffe Thoth is a new collaborator he didn't realise you ment just CUE.NET. We need a generic solution for every API we use, so it's probably best to do it at our end :)

I did have something else but I'll make an issue for that on CUE.NET's GitHub
